package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "airflow",
		Description: "Subcommand",
		Subcommands: []core.Subcommand{
			{Name: "celery", Description: "Celery components"},
			{Name: "broker_api", Description: "Broker API"},
			{Name: "flower_conf", Description: "Configuration file for flower"},
			{Name: "hostname", Description: "Set the hostname on which to run the server"},
			{Name: "log_file", Description: "Location of the log file"},
			{Name: "port", Description: "The port on which to run the server"},
			{Name: "stderr", Description: "Redirect stderr to this file"},
			{Name: "stdout", Description: "Redirect stdout to this file"},
			{Name: "url_prefix", Description: "URL prefix for Flower"},
			{Name: "autoscale", Description: "Minimum and Maximum number of worker to autoscale"},
			{Name: "concurrency", Description: "The number of worker processes"},
			{Name: "queues", Description: "Comma delimited list of queues to serve"},
			{Name: "umask", Description: "Set the umask of celery worker in daemon mode"},
			{Name: "config", Description: "View configuration"},
			{Name: "section", Description: "The section name"},
			{Name: "option", Description: "The option name"},
			{Name: "color", Description: "Do emit colored output (default: auto)"},
			{Name: "connections", Description: "Manage connections"},
			{Name: "conn_description", Description: "Connection description, optional when adding a connection"},
			{Name: "conn_extra", Description: "Connection `Extra` field, optional when adding a connection"},
			{Name: "conn_host", Description: "Connection host, optional when adding a connection"},
			{Name: "conn_json", Description: "Connection JSON, required to add a connection using JSON representation"},
			{Name: "conn_login", Description: "Connection login, optional when adding a connection"},
			{Name: "conn_password", Description: "Connection password, optional when adding a connection"},
			{Name: "conn_port", Description: "Connection port, optional when adding a connection"},
			{Name: "conn_schema", Description: "Connection schema, optional when adding a connection"},
			{Name: "conn_type", Description: "Connection type, required to add a connection without conn_uri"},
			{Name: "conn_uri", Description: "Connection URI, required to add a connection without conn_type"},
			{Name: "conn_id", Description: "Connection id, required to get/add/delete a connection"},
			{Name: "file_format", Description: "File format for the export"},
			{Name: "format", Description: "Deprecated -- use `--file-format` instead. File format to use for the export"},
			{Name: "file", Description: "Output file path for exporting the connections"},
			{Name: "(table, json, yaml, plain)", Description: "Output format. Allowed values: json, yaml, plain, table (default: table)"},
			{Name: "num_runs", Description: "Set the number of runs to execute before exiting"},
			{Name: "dags", Description: "Manage DAGs"},
			{Name: "conf", Description: "JSON string that gets pickled into the DagRun's conf attribute"},
			{Name: "end_date", Description: "Override end_date YYYY-MM-DD"},
			{Name: "pool", Description: "Resource pool to use"},
			{Name: "start_date", Description: "Override start_date YYYY-MM-DD"},
			{Name: "task_regex", Description: "The regex to filter specific task_ids to backfill (optional)"},
			{Name: "dag_id", Description: "The id of the dag"},
			{Name: "limit", Description: "Return a limited number of records"},
			{Name: "state", Description: "Only list the dag runs corresponding to the state"},
			{Name: "num_executions", Description: "The number of next execution datetimes to show"},
			{Name: "save", Description: "Saves the result to the indicated file"},
			{Name: "execution_date", Description: "The execution date of the DAG"},
			{Name: "exec_date", Description: "The execution date of the DAG"},
			{Name: "run_id", Description: "Helps to identify this run"},
			{Name: "db", Description: "Database operations"},
			{Name: "migration_wait_timeout", Description: "Timeout to wait for db to migrate"},
		},
		Options: []core.Option{
			{Name: "-h", Description: "Show this help message and exit"},
			{Name: "-A", Description: "Broker API"},
			{Name: "-D", Description: "Daemonize instead of running in the foreground"},
			{Name: "-c", Description: "Configuration file for flower"},
			{Name: "-H", Description: "Set the hostname on which to run the server"},
			{Name: "-l", Description: "Location of the log file"},
			{Name: "--pid", Description: "PID file location"},
			{Name: "-p", Description: "The port on which to run the server"},
			{Name: "--stderr", Description: "Redirect stderr to this file"},
			{Name: "--stdout", Description: "Redirect stdout to this file"},
			{Name: "-u", Description: "URL prefix for Flower"},
			{Name: "-a", Description: "Minimum and Maximum number of worker to autoscale"},
			{Name: "-q", Description: "Comma delimited list of queues to serve"},
			{Name: "-s", Description: "Don't start the serve logs process along with the workers"},
			{Name: "--without-gossip", Description: "Don't subscribe to other workers events"},
			{Name: "--without-mingle", Description: "Don't synchronize with other workers at start-up"},
			{Name: "-v", Description: "Make logging output more verbose"},
			{Name: "--color", Description: "Do emit colored output (default: auto)"},
			{Name: "--conn-description", Description: "Connection description, optional when adding a connection"},
			{Name: "--conn-extra", Description: "Connection `Extra` field, optional when adding a connection"},
			{Name: "--conn-host", Description: "Connection host, optional when adding a connection"},
			{Name: "--conn-json", Description: "Connection JSON, required to add a connection using JSON representation"},
			{Name: "--conn-login", Description: "Connection login, optional when adding a connection"},
			{Name: "--conn-password", Description: "Connection password, optional when adding a connection"},
			{Name: "--conn-port", Description: "Connection port, optional when adding a connection"},
			{Name: "--conn-schema", Description: "Connection schema, optional when adding a connection"},
			{Name: "--conn-type", Description: "Connection type, required to add a connection without conn_uri"},
			{Name: "--conn-uri", Description: "Connection URI, required to add a connection without conn_type"},
			{Name: "--file-format", Description: "File format for the export"},
			{Name: "--format", Description: "Deprecated -- use `--file-format` instead. File format to use for the export"},
			{Name: "--serialization-format", Description: "Output file path for exporting the connections"},
			{Name: "-o", Description: "Output format. Allowed values: json, yaml, plain, table (default: table)"},
			{Name: "--conn-id", Description: "If passed, only items with the specified connection ID will be displayed"},
			{Name: "-n", Description: "Set the number of runs to execute before exiting"},
			{Name: "-S", Description: "Start a standalone Dag Processor instance"},
			{Name: "--continue-on-failures", Description: "If set, the backfill will keep going even if some of the tasks failed"},
			{Name: "--delay-on-limit", Description: "Override end_date YYYY-MM-DD"},
			{Name: "-i", Description: "Run the task using the LocalExecutor"},
			{Name: "-m", Description: "Mark jobs as succeeded without running them"},
			{Name: "--pool", Description: "Resource pool to use"},
		},
	})
}
