package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "julia",
		Description: "The Julia Programming Language",
		Options: []core.Option{
			{Name: "-v", Description: "Display version information"},
			{Name: "-h", Description: "Print help message for julia (--help-hidden for more)"},
			{Name: "--help-hidden", Description: "Uncommon options not shown by `-h`"},
			{Name: "--project", Description: "Set given directory as the home project/environment"},
			{Name: "-J", Description: "Start up with the given system image file"},
			{Name: "-H", Description: "Set location of `julia` executable"},
			{Name: "--startup-file", Description: "Load `~/.julia/config/startup.jl`"},
			{Name: "--handle-signals", Description: "Enable or disable Julia's default signal handlers"},
			{Name: "--sysimage-native-code", Description: "Use native code from system image if available"},
			{Name: "--compiled-modules", Description: "Enable or disable incremental precompilation of modules"},
			{Name: "-e", Description: "Evaluate given expr"},
			{Name: "-E", Description: "Evaluate given expr and display the result"},
			{Name: "-L", Description: "Load given file immediately on all processors"},
			{Name: "-t", Description: "Number of threads"},
			{Name: "-p", Description: "Number of additional local worker processes"},
			{Name: "--machine-file", Description: "Run processes on hosts listed in given file"},
			{Name: "-i", Description: "Interactive mode; REPL runs and isinteractive() is true"},
			{Name: "-q", Description: "Quiet startup: no banner, suppress REPL warnings"},
			{Name: "--banner", Description: "Enable or disable startup banner"},
			{Name: "--color", Description: "Enable or disable color text"},
			{Name: "--history-file", Description: "Load or save history"},
			{Name: "--depwarn", Description: "Enable or disable method overwrite warnings"},
			{Name: "--warn-scope", Description: "Enable or disable warning for ambiguous top-level scope"},
			{Name: "-C", Description: "Level of optimization"},
			{Name: "-g", Description: "Enable / Set the level of debug info generation"},
			{Name: "--inline", Description: "Control whether inlining is permitted, including overriding @inline declarations"},
			{Name: "--check-bounds", Description: "Emit bounds checks always, never, or respect @inbounds declarations"},
			{Name: "--polly", Description: "Enable or disable the polyhedral optimizer Polly (overrides @polly declaration)"},
			{Name: "--math-mode", Description: "Enable or disable JIT compiler, or request exhaustive or minimal compilation"},
			{Name: "--output-o", Description: "Generate an object file (including system image data)"},
			{Name: "--output-ji", Description: "Generate a system image data file (.ji)"},
			{Name: "--output-unopt-bc", Description: "Generate unoptimized LLVM bitcode (.bc)"},
			{Name: "--output-jit-bc", Description: "Dump all IR generated by the frontend (not including system image)"},
			{Name: "--output-bc", Description: "Generate LLVM bitcode (.bc)"},
			{Name: "--output-asm", Description: "Generate an assembly file (.s)"},
			{Name: "--output-incremental", Description: "Generate an incremental output file (rather than complete)"},
			{Name: "--image-codegen", Description: "Force generate code in imaging mode"},
		},
	})
}
