package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "pac",
		Description: "7",
		Subcommands: []core.Subcommand{
			{Name: "admin", Description: "Work with your Power Platform Admin Account"},
			{Name: "list", Description: "List all environments from your tenant"},
			{Name: "create", Description: "Creates a Dataverse instance in your tenant"},
			{Name: "backup", Description: "Takes a manual backup of your environment"},
			{Name: "set-backup-retention-period", Description: "Takes a manual backup of your environment"},
			{Name: "delete", Description: "Deletes the environment from your tenant"},
			{Name: "reset", Description: "Reset the environment from your tenant"},
			{Name: "list-backups", Description: "Lists all backups of your environment"},
			{Name: "restore", Description: "Restores an environment to a given backup"},
			{Name: "copy", Description: "Copy Source Environment to Destination Environment"},
			{Name: "status", Description: "This command lists the status of all the operations in progress"},
			{Name: "assign-user", Description: "Assign a user to a target Dataverse environment with specified security role"},
			{Name: "assign-group", Description: "Assign group to target Dataverse environment with specified security role"},
			{Name: "list-app-templates", Description: "Lists all supported Dataverse templates of model-driven apps in Dynamics 365"},
			{Name: "list-service-principal", Description: "List Microsoft Entra ID applications which have access to Dataverse"},
			{Name: "set-governance-config", Description: "Enable, disable, and edit managed environments"},
			{Name: "list-tenant-settings", Description: "List tenant settings"},
			{Name: "update-tenant-settings", Description: "Update tenant settings"},
			{Name: "application", Description: "Work with Microsoft Entra ID applications"},
			{Name: "register", Description: "Register Microsoft Entra ID application with your tenant"},
			{Name: "unregister", Description: "Unregister Microsoft Entra ID application from your tenant"},
			{Name: "install", Description: "Installs Dataverse application to given environment"},
			{Name: "auth", Description: "Manage how you authenticate to various services"},
			{Name: "select", Description: "Select which authentication profile should be active"},
			{Name: "update", Description: "Update name or target environment of an existing authentication profile"},
			{Name: "name", Description: "Name or rename an existing authentication profile"},
			{Name: "clear", Description: "Clear all authentication profiles stored on this computer"},
			{Name: "canvas", Description: "Operating with Power Apps .msapp files"},
			{Name: "download", Description: "Download canvas app as .msapp file"},
			{Name: "pack", Description: "(Preview) Pack sources into an msapp file"},
			{Name: "unpack", Description: "(Preview) Extract an msapp file into sources"},
			{Name: "catalog", Description: "Commands for working with Catalog in Power Platform"},
			{Name: "submit", Description: "Submit catalog approval request"},
			{Name: "connection", Description: "Commands for working with Dataverse connection"},
			{Name: "connector", Description: "Commands for working with Power Platform Connectors"},
			{Name: "init", Description: "Initializes a new API Properties file for a Connector"},
			{Name: "copilot", Description: "Tools and utilities for copilot scenarios"},
			{Name: "predict", Description: "Sends text or prompt to AI Model"},
			{Name: "data", Description: "Import and export data from Dataverse"},
			{Name: "export", Description: "Export data"},
			{Name: "import", Description: "Import data"},
			{Name: "help", Description: "Show help for the Microsoft Power Platform CLI"},
			{Name: "modelbuilder", Description: "Code Generator for Dataverse APIs and Tables"},
			{Name: "build", Description: "Builds a code model for Dataverse APIs and Tables"},
			{Name: "org", Description: "Work with your Dataverse organization"},
			{Name: "who", Description: "Displays information about the current Dataverse organization"},
			{Name: "fetch", Description: "Performs FetchXML query against Dataverse"},
			{Name: "list-settings", Description: "List environment settings"},
			{Name: "update-settings", Description: "Update environment settings"},
			{Name: "package", Description: "Commands for working with Dataverse package projects"},
		},
		Options: []core.Option{
			{Name: "--environment", Description: "List all environments that contain given string in their name or ID"},
			{Name: "--type", Description: "List all environments with the given type"},
			{Name: "--name", Description: "List all environments that contain given string in their name"},
			{Name: "--organization-id", Description: "List all environments that contain given string in their organization ID"},
			{Name: "--application", Description: "Creates a Dataverse instance in your tenant"},
			{Name: "--region", Description: "Sets the environment's region name. [defaults to unitedstates]"},
			{Name: "--currency", Description: "Sets the currency used for your environment. [defaults to USD]"},
			{Name: "--language", Description: "Sets the language used for your environment. [defaults to English]"},
			{Name: "--templates", Description: "Optional boolean argument to run pac verbs asynchronously, defaults to false"},
			{Name: "--team-id", Description: "Team ID as Guid"},
			{Name: "--max-async-wait-time", Description: "Max asynchronous wait time in minutes. The default value is 60 minutes"},
			{Name: "--user", Description: "Takes a manual backup of your environment"},
			{Name: "--label", Description: "Sets the backup label as provided"},
			{Name: "--notes", Description: "**ignored**: Additional notes for this backup"},
			{Name: "--backup-retention-period", Description: "Optional boolean argument to run pac verbs asynchronously, defaults to false"},
			{Name: "--domain", Description: "Sets the name of the environment"},
			{Name: "--purpose", Description: "Sets the description used to associate the environment with a specific intent"},
			{Name: "--source-env", Description: "Environment URL or ID of the source environment required for restore"},
			{Name: "--target-env", Description: "DateTime of the backup in 'mm/dd/yyyy hh:mm' format OR string 'latest'"},
			{Name: "--skip-audit-data", Description: "Switch indicating whether audit data should be skipped"},
			{Name: "--async", Description: "Optional boolean argument to run pac verbs asynchronously, defaults to false"},
			{Name: "--application-user", Description: "ID of business unit to associate application user with"},
			{Name: "--group", Description: "Microsoft Entra ID object ID of group to assign to target Dataverse environment"},
			{Name: "--group-name", Description: "Name of the group or team to create in Dataverse"},
			{Name: "--role", Description: "Name or ID of security role to be applied to user"},
			{Name: "--team-type", Description: "Type of team"},
			{Name: "--membership-type", Description: "Team membership type"},
			{Name: "--business-unit", Description: "ID of business unit to associate application user with"},
			{Name: "--filter", Description: "Application name 'starts with' filter"},
			{Name: "--max", Description: "Max number of applications to show. Default: 20"},
			{Name: "--exclude-analysis", Description: "Exclude usage insights for the environment from the weekly digest email"},
			{Name: "--include-insights", Description: "Include insights in the Power Platform Admin Center homepage cards"},
			{Name: "--limit-sharing-mode", Description: "Limit sharing mode"},
			{Name: "--max-limit-user-sharing", Description: "Solution checker validation mode"},
			{Name: "--settings-file", Description: "The .json file to output tenant settings"},
			{Name: "--application-id", Description: "Application Id"},
			{Name: "--application-list", Description: "Manage how you authenticate to various services"},
			{Name: "--kind", Description: "The kind of authentication profile you're creating"},
			{Name: "--url", Description: "The resource URL to connect to"},
			{Name: "--username", Description: "Optional: The password to authenticate with"},
		},
	})
}
