package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "sam",
		Description: "Host of locally emulated Lambda container",
		Subcommands: []core.Subcommand{
			{Name: "init", Description: "Init an AWS SAM application"},
			{Name: "text", Description: "Template name"},
			{Name: "validate", Description: "Validate an AWS SAM template"},
			{Name: "build", Description: "Build your Lambda function code"},
			{Name: "local", Description: "Run your Serverless application locally for quick development & testing"},
			{Name: "invoke", Description: "Invokes a local Lambda function once"},
			{Name: "start-api", Description: "Sets up a local endpoint you can use to test your API"},
			{Name: "start-lambda", Description: "Starts a local endpoint you can use to invoke your local Lambda functions"},
			{Name: "package", Description: "Package an AWS SAM application"},
			{Name: "deploy", Description: "Deploy an AWS SAM application"},
			{Name: "delete", Description: "Delete an AWS SAM application and the artifacts created by `sam deploy`"},
			{Name: "logs", Description: "Fetch logs for a function"},
			{Name: "publish", Description: "Publish a packaged AWS SAM template to the AWS Serverless Application Repository"},
			{Name: "traces", Description: "[Beta Feature] Fetch AWS X-Ray traces"},
			{Name: "sync", Description: "[Beta Feature] Sync a project to AWS"},
			{Name: "pipeline", Description: "Manage the continuous delivery of the application"},
			{Name: "bootstrap", Description: "Generates the required AWS resources to connect your CI/CD system"},
		},
		Options: []core.Option{
			{Name: "--config-env", Description: "Host of locally emulated Lambda container"},
			{Name: "--container-host-interface", Description: "Additional arguments to be passed to the debugger"},
			{Name: "--debugger-path", Description: "Host path to a debugger to mount into the Lambda container"},
			{Name: "--docker-network", Description: "Location basedir where the SAM file exists"},
			{Name: "-n", Description: "JSON file containing values for Lambda function environment variables"},
			{Name: "--force-image-build", Description: "Whether the image should be rebuilt"},
			{Name: "--force-upload", Description: "Show help for sam"},
			{Name: "--host", Description: "Local hostname or IP address to bind to"},
			{Name: "--image-repository", Description: "Specify mapping of Function Logical ID to ECR Repo uri"},
			{Name: "-ii", Description: "Container image URIs for invoking functions or starting api and function"},
			{Name: "--kms-key-id", Description: "Location where Layers your template uses will be downloaded to"},
			{Name: "-l", Description: "Log file to send runtime logs to"},
			{Name: "--metadata", Description: "Does not showcase a progress bar when uploading artifacts to s3"},
			{Name: "--parameter-overrides", Description: "Local port to listen on"},
			{Name: "--profile", Description: "Select a specific profile from your credential file to get AWS credentials"},
			{Name: "-g", Description: "Set the AWS Region of the service"},
			{Name: "--resolve-s3", Description: "The prefix name is a path name (folder name) for the S3 bucket"},
			{Name: "--signing-profiles", Description: "A string that contains Code Sign configuration parameters"},
			{Name: "--shutdown", Description: "AWS SAM template file"},
			{Name: "--use-json", Description: "Specific how SAM manages the containers for each function"},
			{Name: "--no-interactive", Description: "Architectures your Lambda function will run on"},
			{Name: "-r", Description: "Lambda Runtime for your app"},
			{Name: "-p", Description: "Package type for your app"},
			{Name: "-i", Description: "Lambda Image of your app"},
			{Name: "-d", Description: "Dependency manager for your Lambda runtime"},
			{Name: "-o", Description: "Where to output the initialized app into"},
			{Name: "--app-template", Description: "Identifier of the managed application template you want to use"},
			{Name: "--no-input", Description: "Disable Cookiecutter prompting and accept default values defined template config"},
			{Name: "--extra-context", Description: "Override any custom parameters in the template's cookiecutter.json configuration"},
			{Name: "-u", Description: "If your functions depend on packages that have natively compiled dependencies,"},
			{Name: "-e", Description: "Input environment variables through command line to pass into build containers,"},
			{Name: "-ef", Description: "Container image URIs"},
			{Name: "-b", Description: "Path to a folder where the built artifacts will be stored"},
			{Name: "-cd", Description: "The folder where the cached artifacts are stored with `--cached` is specified"},
			{Name: "-s", Description: "Resolve relative paths to function's source code with respect to this folder"},
			{Name: "-m", Description: "Path to a custom dependency manifest to use instead of the default one"},
			{Name: "-c", Description: "Should beta features be enabled"},
			{Name: "--output-template-file", Description: "Deploy an AWS SAM application"},
			{Name: "--no-prompts", Description: "Specify this flag to allow SAM CLI to skip through the guided prompts"},
			{Name: "--semantic-version", Description: "The value provided here overrides SemanticVersion in the template metadata"},
		},
	})
}
