package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "tmuxinator",
		Description: "Project",
		Subcommands: []core.Subcommand{
			{Name: "commands", Description: "Lists commands available in tmuxinator"},
			{Name: "completions", Description: "Used for shell completion"},
			{Name: "copy", Description: "Copy an existing project to a new project and open it in your editor"},
			{Name: "source", Description: "The source project name"},
			{Name: "target", Description: "The target project name"},
			{Name: "debug", Description: "Output the shell commands that are generated by tmuxinator"},
			{Name: "attach-session", Description: "Attach to tmux session"},
			{Name: "name", Description: "Give the session a different name"},
			{Name: "project-config", Description: "Path to project config file"},
			{Name: "delete", Description: "Deletes given project"},
			{Name: "project", Description: "The project name"},
			{Name: "doctor", Description: "Look for problems in your configuration"},
			{Name: "help", Description: "Describe available commands or one specific command"},
			{Name: "command", Description: "The tmuxinator commands"},
			{Name: "implode", Description: "Deletes all tmuxinator projects"},
			{Name: "list", Description: "Lists all tmuxinator projects"},
			{Name: "local", Description: "Start a tmux session using ./.tmuxinator.y[a]ml"},
			{Name: "new", Description: "Create a new project file and open it in your editor"},
			{Name: "tmux-session", Description: "The tmux session name"},
			{Name: "edit", Description: "Open a project file it in your editor"},
			{Name: "open", Description: "Open a project file it in your editor"},
			{Name: "stop", Description: "Stop a tmux session using a project's tmuxinator config"},
			{Name: "version", Description: "Display installed tmuxinator version"},
		},
		Options: []core.Option{
			{Name: "-a", Description: "Attach to tmux session after creation"},
			{Name: "-n", Description: "Give the session a different name"},
			{Name: "-p", Description: "Path to project config file"},
			{Name: "-l", Description: "Create local project file at ./.tmuxinator.y[a]ml"},
		},
	})
}
