package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "adb",
		Description: "Forward-lock the app",
		Subcommands: []core.Subcommand{
			{Name: "devices", Description: "List connected devices"},
			{Name: "help", Description: "Show this help message"},
			{Name: "get-state", Description: "Print offline | bootloader | device"},
			{Name: "get-serialno", Description: "Print <serial-number>"},
			{Name: "get-devpath", Description: "Print <device-path>"},
			{Name: "jdwp", Description: "List pids of processes hosting a JDWP transport"},
			{Name: "root", Description: "Restart adbd with root permissions"},
			{Name: "unroot", Description: "Restart adbd without root permissions"},
			{Name: "usb", Description: "Restart adbd listening on USB"},
			{Name: "sideload", Description: "Sideload the given full OTA package"},
			{Name: "tcpip", Description: "Restart adbd listening on TCP on PORT"},
			{Name: "disable-verity", Description: "Disable dm-verity checking on userdebug builds"},
			{Name: "enable-verity", Description: "Re-enable dm-verity checking on userdebug builds"},
			{Name: "wait-for-device", Description: "Wait for state=device"},
			{Name: "wait-for-recovery", Description: "Wait for state=recovery"},
			{Name: "wait-for-rescue", Description: "Wait for state=rescue"},
			{Name: "wait-for-sideload", Description: "Wait for state=sideload"},
			{Name: "wait-for-bootloader", Description: "Wait for state=bootloader"},
			{Name: "wait-for-disconnect", Description: "Wait for state=disconnect"},
			{Name: "wait-for-usb-device", Description: "Wait for usb in state=device"},
			{Name: "wait-for-usb-recovery", Description: "Wait for usb in state=recovery"},
			{Name: "wait-for-usb-rescue", Description: "Wait for usb in state=rescue"},
			{Name: "wait-for-usb-sideload", Description: "Wait for usb in state=sideload"},
			{Name: "wait-for-usb-bootloader", Description: "Wait for usb in state=bootloader"},
			{Name: "wait-for-usb-disconnect", Description: "Wait for usb in state=disconnect"},
			{Name: "wait-for-local-device", Description: "Wait for local in state=device"},
			{Name: "wait-for-local-recovery", Description: "Wait for local in state=recovery"},
			{Name: "wait-for-local-rescue", Description: "Wait for local in state=rescue"},
			{Name: "wait-for-local-sideload", Description: "Wait for local in state=sideload"},
			{Name: "wait-for-local-bootloader", Description: "Wait for local in state=bootloader"},
			{Name: "wait-for-local-disconnect", Description: "Wait for local in state=disconnect"},
			{Name: "wait-for-any-device", Description: "Wait for any in state=device"},
			{Name: "wait-for-any-recovery", Description: "Wait for any in state=recovery"},
			{Name: "wait-for-any-rescue", Description: "Wait for any in state=rescue"},
			{Name: "wait-for-any-sideload", Description: "Wait for any in state=sideload"},
			{Name: "wait-for-any-bootloader", Description: "Wait for any in state=bootloader"},
			{Name: "wait-for-any-disconnect", Description: "Wait for any in state=disconnect"},
			{Name: "keygen", Description: "Generate adb public/private key; private key stored in FILE"},
			{Name: "logcat", Description: "Show device log (logcat --help for more)"},
			{Name: "version", Description: "Show version num"},
			{Name: "connect", Description: "Connect to a device via TCP/IP [default port=5555]"},
			{Name: "disconnect", Description: "Disconnect from given TCP/IP device [default port=5555], or all"},
			{Name: "uninstall", Description: "Remove this app package from the device"},
			{Name: "bugreport", Description: "Write bugreport to given PATH [default=bugreport.zip];"},
			{Name: "pair", Description: "Pair with a device for secure TCP/IP communication"},
			{Name: "ppp", Description: "Run PPP over USB"},
			{Name: "emu", Description: "Run emulator console command"},
			{Name: "install", Description: "Push a single package to the device and install it"},
			{Name: "install-multiple", Description: "Push multiple APKs to the device for a single package and install them"},
			{Name: "install-multi-package", Description: "Push one or more packages to the device and install them atomically"},
		},
		Options: []core.Option{
			{Name: "-l", Description: "Forward-lock the app"},
			{Name: "-r", Description: "Replace existing application"},
			{Name: "-t", Description: "Allow test packages"},
			{Name: "-d", Description: "Allow version code downgrade (debuggable packages only)"},
			{Name: "-s", Description: "Install on SD card instead of internal storage"},
			{Name: "-g", Description: "Grant all runtime permissions"},
			{Name: "-R", Description: "Reboot device"},
			{Name: "-k", Description: "Keep the data and cache directories"},
			{Name: "-p", Description: "Partial application install (install-multiple only)"},
			{Name: "-e", Description: "Choose escape character, or `none` default '~'"},
			{Name: "-n", Description: "Don't read from stdin"},
			{Name: "-T", Description: "Disable pty allocation"},
			{Name: "-tt", Description: "-tt: force pty allocation"},
			{Name: "-x", Description: "Disable remote exit codes and stdout/stderr separation"},
			{Name: "--list", Description: "List all forward socket connections"},
			{Name: "--remove", Description: "Remove specific forward socket connection"},
			{Name: "--remove-all", Description: "Remove all forward socket connections"},
			{Name: "--no-rebind", Description: "Reverse connection"},
		},
	})
}
