package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "bundle",
		Description: "Gem",
		Subcommands: []core.Subcommand{
			{Name: "install", Description: "Install the gems specified by the Gemfile or Gemfile.lock"},
			{Name: "update", Description: "Update dependencies to their latest versions"},
			{Name: "exec", Description: "Execute a command in the context of the bundle"},
			{Name: "add", Description: "Add gem to the Gemfile and run bundle install"},
			{Name: "binstubs", Description: "Install the binstubs of the listed gems"},
			{Name: "show", Description: "Show the source location of a particular gem in the bundle"},
			{Name: "outdated", Description: "Show all of the outdated gems in the current bundle"},
			{Name: "console", Description: "Start an IRB session in the current bundle"},
			{Name: "open", Description: "Open an installed gem in the editor"},
			{Name: "lock", Description: "Generate a lockfile for your dependencies"},
			{Name: "viz", Description: "Generate a visual representation of your dependencies"},
			{Name: "init", Description: "Generate a simple Gemfile, placed in the current directory"},
			{Name: "gem", Description: "Create a simple gem, suitable for development with Bundler"},
			{Name: "platform", Description: "Display platform compatibility information"},
			{Name: "clean", Description: "Clean up unused gems in your Bundler directory"},
			{Name: "doctor", Description: "Display warnings about common problems"},
		},
		Options: []core.Option{
			{Name: "--binstubs", Description: "Create binstubs in dir"},
			{Name: "--clean", Description: "Remove unused gems after install"},
			{Name: "--deployment", Description: "For Production and CI use"},
			{Name: "--force", Description: "Redownload all gems"},
			{Name: "--frozen", Description: "Do not allow lock file to update"},
			{Name: "--full-index", Description: "Cache the full index locally"},
			{Name: "--gemfile", Description: "The gemfile to use"},
			{Name: "--jobs", Description: "Maximum number of parallel installs"},
			{Name: "--local", Description: "Use only gems already downloaded or cached"},
			{Name: "--no-cache", Description: "Do not use vendor/cache"},
			{Name: "--no-prune", Description: "Do not remove stale gems"},
			{Name: "--path", Description: "Path the install gems too"},
			{Name: "--quiet", Description: "Do not print to stdout"},
			{Name: "--retry", Description: "Retry failed network requests N times"},
			{Name: "--shebang", Description: "Uses the specified ruby executable for binstubs"},
			{Name: "--standalone", Description: "Makes a bundle that can work without depending on Rubygems or Bundler at runtime"},
			{Name: "--system", Description: "Use system Rubygems location"},
			{Name: "--trust-policy", Description: "Apply the Rubygems security policy"},
			{Name: "--with", Description: "Groups to install"},
			{Name: "--without", Description: "Groups to NOT install"},
			{Name: "--all", Description: "Update all gems specified in Gemfile"},
			{Name: "--group", Description: "Only update the gems in the specified group"},
			{Name: "--source", Description: "The name of a :git or :path source used in the Gemfile"},
			{Name: "--ruby", Description: "Update the locked version of Ruby to the current version of Ruby"},
			{Name: "--bundler", Description: "Update the locked version of bundler to the invoked bundler version"},
			{Name: "--patch", Description: "Prefer updating only to next patch version"},
			{Name: "--minor", Description: "Prefer updating only to next minor version"},
			{Name: "--major", Description: "Prefer updating to next major version (default)"},
			{Name: "--strict", Description: "Do not allow any gem to be updated past latest --patch | --minor | --major"},
			{Name: "--conservative", Description: "Do not allow shared dependencies to be updated"},
			{Name: "--keep-file-descriptors", Description: "Pass all file descriptors to the new process"},
			{Name: "--version", Description: "Specify version requirements"},
			{Name: "--skip-install", Description: "Adds the gem to the Gemfile but does not install it"},
			{Name: "--optimistic", Description: "Adds optimistic declaration of version"},
			{Name: "--dry-run", Description: "Locks the Gemfile before running the command"},
			{Name: "--paths", Description: "List the paths of all gems that are required by your Gemfile"},
			{Name: "--pre", Description: "Check for newer pre-release gems"},
			{Name: "--parseable", Description: "Use minimal formatting for more parseable output"},
			{Name: "--groups", Description: "List gems organized by groups"},
			{Name: "--update-strict", Description: "Prefer updating only to next minor version"},
		},
	})
}
