package sys

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "cci",
		Description: "CumulusCI command line interface",
		Subcommands: []spec.Subcommand{
			{Name: "flow", Description: "Commands for finding and running flows for a project"},
			{Name: "doc", Description: "Exports RST format documentation for all flows"},
			{Name: "info", Description: "Displays information for a flow"},
			{Name: "FLOW_NAME", Description: "Name of the flow"},
			{Name: "list", Description: "List available flows for the current context"},
			{Name: "run", Description: "Runs a flow"},
			{Name: "TEXT", Description: "Name of the target org"},
			{Name: "org", Description: "Commands for connecting and interacting with Salesforce orgs"},
			{Name: "browser", Description: "Opens a browser window and logs into the org using the stored OAuth credentials"},
			{Name: "ORGNAME", Description: "Name of the org"},
			{Name: "connect", Description: "Connects a new org's credentials using OAuth Web Flow"},
			{Name: "default", Description: "Sets an org as the default org for tasks and flows"},
			{Name: "import", Description: "Import an org from Salesforce DX"},
			{Name: "prune", Description: "Removes all expired scratch orgs from the current project"},
			{Name: "remove", Description: "Removes an org from the keychain"},
			{Name: "scratch", Description: "Connects a Salesforce DX Scratch Org to the keychain"},
			{Name: "plan", Description: "Commands for getting information about MetaDeploy plans"},
			{Name: "PLAN_NAME", Description: "Name of the plan"},
			{Name: "robot", Description: "Commands for working with Robot Framework"},
			{Name: "install_playwright", Description: "Install libraries necessary to use playwright with robot framework"},
			{Name: "uninstall_playwright", Description: "Uninstalls the robotframework-browser package and node modules"},
			{Name: "service", Description: "Commands for connecting services to the keychain"},
			{Name: "connected_app", Description: "Connect a Connected App service to CumulusCI"},
			{Name: "devhub", Description: "Connect a DevHub service to CumulusCI"},
			{Name: "github", Description: "Connect a GitHub service to CumulusCI"},
			{Name: "github_enterprise", Description: "Connect a GitHub Enterprise service to CumulusCI"},
			{Name: "marketing_cloud", Description: "Connect a Marketing Cloud service to CumulusCI"},
			{Name: "metaci", Description: "Connect a MetaCI service to CumulusCI"},
			{Name: "metadeploy", Description: "Connect a MetaDeploy service to CumulusCI"},
			{Name: "oauth2_client", Description: "Connect an OAuth2 Client service to CumulusCI"},
			{Name: "rename", Description: "Rename a service"},
			{Name: "update", Description: "Allow users to update attribute values of a particular service"},
			{Name: "shell", Description: "Drop into a Python shell"},
			{Name: "task", Description: "Commands for finding and running tasks for a project"},
			{Name: "version", Description: "Print the current version of CumulusCI"},
			{Name: "error", Description: "Get or share information about an error"},
			{Name: "gist", Description: "Creates a GitHub gist from the latest logfile"},
			{Name: "project", Description: "Commands for interacting with project repository configurations"},
			{Name: "init", Description: "Initialize a new project for use with the cumulusci toolbelt"},
		},
		Options: []spec.Option{
			{Name: "--project", Description: "Include project-specific flows only"},
			{Name: "--help", Description: "Help for flow doc"},
			{Name: "--plain", Description: "Print the table using plain ascii"},
			{Name: "--json", Description: "Print a json string"},
			{Name: "--org", Description: "Specify the target org. By default, runs against the current default org"},
			{Name: "--delete-org", Description: "If set, deletes the scratch org after the flow completes"},
			{Name: "--debug", Description: "Drops into pdb, the Python debugger, on an exception"},
			{Name: "-o", Description: "Task specific options"},
			{Name: "--no-prompt", Description: "Help for flow run"},
			{Name: "-p", Description: "Navigate to the specified page after logging in"},
			{Name: "-r", Description: "Display the target URL, but don't open a browser"},
			{Name: "--sandbox", Description: "If set, connects to a Salesforce sandbox org"},
			{Name: "--login-url", Description: "If set, login to this hostname"},
			{Name: "--default", Description: "If set, sets the connected org as the new default org"},
			{Name: "--global-org", Description: "If set, the connected org is available to all CumulusCI projects"},
			{Name: "--include-active", Description: "Remove all scratch orgs, regardless of expiry"},
			{Name: "--devhub", Description: "If provided, overrides the devhub used to create the scratch org"},
			{Name: "--days", Description: "If set, don't set a password for the org"},
			{Name: "--python", Description: "Python code to run directly"},
			{Name: "--messages", Description: "Show only plan messages"},
			{Name: "-n", Description: "Dry run"},
			{Name: "--login_url", Description: "Default Salesforce Login URL to be used with this Connected App"},
			{Name: "--callback_url", Description: "Callback URL configured on the Connected App"},
			{Name: "--client_id", Description: "Client ID/Consumer Key from the Connected App"},
			{Name: "--client_secret", Description: "Client Secret/Consumer Secret from the Connected App"},
			{Name: "--username", Description: "Username or alias of the SFDX org to use as a Dev Hub"},
			{Name: "--email", Description: "Personal Access Token for GitHub. Leave blank to log in via browser"},
			{Name: "--token", Description: "Personal Access Token"},
			{Name: "--oauth2_client", Description: "Set this service as the global default"},
			{Name: "--app_name", Description: "The Heroku app name"},
			{Name: "--url", Description: "The main url to the MetaCI site"},
			{Name: "--auth_uri", Description: "The URI for where users are directed to login"},
			{Name: "--token_uri", Description: "The URI for where we request an access token"},
			{Name: "-s", Description: "Help for cci service remove"},
			{Name: "--script", Description: "Path to a script to run"},
			{Name: "--resolution-strategy", Description: "The resolution strategy to use. Defaults to production"},
		},
	})
}
