package sys

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "gum",
		Description: "Background Color",
		Subcommands: []spec.Subcommand{
			{Name: "choose", Description: "Choose an option from a list of choices"},
			{Name: "confirm", Description: "Ask a user to confirm an action"},
			{Name: "prompt", Description: "Prompt to display"},
			{Name: "filter", Description: "Filter items from a list"},
			{Name: "format", Description: "Format a string using a template"},
			{Name: "template", Description: "Template string to format"},
			{Name: "input", Description: "Prompt for some input"},
			{Name: "join", Description: "Join text vertically or horizontally"},
			{Name: "text", Description: "Text to join"},
			{Name: "spin", Description: "Display spinner while running a command"},
			{Name: "style", Description: "Apply coloring, borders, spacing to text"},
			{Name: "write", Description: "Prompt for long-form text"},
			{Name: "file", Description: "Pick a file from a folder"},
			{Name: "path", Description: "The path to the folder to begin traversing"},
			{Name: "table", Description: "Render a table of data"},
			{Name: "pager", Description: "Scroll through a file"},
			{Name: "content", Description: "Display content to scroll"},
		},
		Options: []spec.Option{
			{Name: "--background", Description: "Background Color"},
			{Name: "--foreground", Description: "Foreground Color"},
			{Name: "--border", Description: "Border Style"},
			{Name: "--border-background", Description: "Border Background Color"},
			{Name: "--border-foreground", Description: "Border Foreground Color"},
			{Name: "--align", Description: "Text Alignment"},
			{Name: "--height", Description: "Text height"},
			{Name: "--width", Description: "Text width"},
			{Name: "--margin", Description: "Text margin"},
			{Name: "--padding", Description: "Text padding"},
			{Name: "--bold", Description: "Bold text"},
			{Name: "--faint", Description: "Faint text"},
			{Name: "--italic", Description: "Italicize text"},
			{Name: "--strikethrough", Description: "Strikethrough text"},
			{Name: "--underline", Description: "Underline text"},
			{Name: "--cursor", Description: "Prefix to show on item that corresponds to the cursor position"},
			{Name: "--cursor-prefix", Description: "Prefix to show on the cursor item"},
			{Name: "--selected-prefix", Description: "Prefix to show on selected items"},
			{Name: "--unselected-prefix", Description: "Prefix to show on unselected items"},
			{Name: "--selected", Description: "Options that should start as selected"},
			{Name: "--limit", Description: "Maximum number of options to pick"},
			{Name: "--no-limit", Description: "Pick unlimited number of options (ignores limit)"},
			{Name: "--affirmative", Description: "The title of the affirmative action"},
			{Name: "--negative", Description: "The title of the negative action"},
			{Name: "--default", Description: "Default confirmation action"},
			{Name: "--timeout", Description: "Timeout for confirmation"},
			{Name: "--indicator", Description: "Character for selection"},
			{Name: "--placeholder", Description: "Placeholder value"},
			{Name: "--prompt", Description: "Prompt to display"},
			{Name: "--value", Description: "Initial filter"},
			{Name: "--reverse", Description: "Display from the bottom of the screen"},
			{Name: "--type", Description: "Format to use"},
			{Name: "--char-limit", Description: "Maximum value length"},
			{Name: "--password", Description: "Mask input characters"},
			{Name: "--horizontal", Description: "Join (potentially multi-line) strings horizontally"},
			{Name: "--vertical", Description: "Join (potentially multi-line) strings vertically"},
			{Name: "--show-output", Description: "Show output of command"},
			{Name: "--spinner", Description: "Spinner type"},
			{Name: "--title", Description: "Text to display to user while spinning"},
			{Name: "--show-cursor-line", Description: "Show cursor line"},
		},
	})
}
