package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "meroxa",
		Description: "The Meroxa CLI",
		Subcommands: []core.Subcommand{
			{Name: "accounts", Description: "Manage Meroxa Accounts"},
			{Name: "ls", Description: "List Meroxa Accounts"},
			{Name: "set", Description: "Set active account"},
			{Name: "api", Description: "Invoke Meroxa API"},
			{Name: "app", Description: "Manage Turbine Data Applications"},
			{Name: "deploy", Description: "Deploy a Turbine Data Application"},
			{Name: "describe", Description: "Describe a Turbine Data Application"},
			{Name: "init", Description: "Initialize a Turbine Data Application"},
			{Name: "log", Description: "View relevant logs to the state of the given Turbine Data Application"},
			{Name: "open", Description: "Open the link to a Turbine Data Application in the Dashboard"},
			{Name: "rm", Description: "Remove a Turbine Data Application"},
			{Name: "run", Description: "Execute a Turbine Data Application locally"},
			{Name: "upgrade", Description: "Upgrade a Turbine Data Application"},
			{Name: "auth", Description: "Authentication commands for Meroxa"},
			{Name: "login", Description: "Login or Sign up to the Meroxa Platform"},
			{Name: "logout", Description: "Clears local login credentials of the Meroxa Platform"},
			{Name: "whoami", Description: "Display the current logged in user"},
			{Name: "billing", Description: "Open your billing page in a web browser"},
			{Name: "build", Description: "Inspect Process Builds on Meroxa"},
			{Name: "completion", Description: "Generate completion script"},
			{Name: "cfg", Description: "Manage your Meroxa CLI configuration"},
			{Name: "env", Description: "Manage environments on Meroxa"},
			{Name: "create", Description: "Create an environment"},
			{Name: "repair", Description: "Repair environment"},
			{Name: "update", Description: "Update an environment"},
			{Name: "resource", Description: "Manage resources on Meroxa"},
			{Name: "add", Description: "Add a resource to your Meroxa resource catalog"},
			{Name: "rotate-tunnel-key", Description: "Rotate the tunnel key for a resource"},
			{Name: "validate", Description: "Validate a resource"},
			{Name: "transform", Description: "Manage transforms on Meroxa"},
			{Name: "version", Description: "Display the Meroxa CLI version"},
			{Name: "help", Description: "Help about any command"},
		},
		Options: []core.Option{
			{Name: "--no-headers", Description: "Display output without headers"},
			{Name: "--docker-hub-access-token", Description: "DockerHub access token to use to build and deploy the app"},
			{Name: "--docker-hub-username", Description: "DockerHub username to use to build and deploy the app"},
			{Name: "--env", Description: "Environment (name or UUID) where application will be deployed to"},
			{Name: "--path", Description: "Path to the app directory (default is local directory)"},
			{Name: "--skip-collection-validation", Description: "Skips unique destination collection and looping validations"},
			{Name: "--spec", Description: "Deployment specification version to use to build and deploy the app"},
			{Name: "--verbose", Description: "Prints more logging messages"},
			{Name: "--lang", Description: "Language to use (js|go|py) (required)"},
			{Name: "--mod-vendor", Description: "Path where application will be initialized (current directory as default)"},
			{Name: "--skip-mod-init", Description: "Whether to run 'go mod init' while initializing a Go application"},
			{Name: "--force", Description: "Skip confirmation"},
			{Name: "--config", Description: "Environment cloud provider to use"},
			{Name: "--region", Description: "Environment region"},
			{Name: "--type", Description: "Environment type, when not specified"},
			{Name: "--yes", Description: "Skip confirmation prompt"},
			{Name: "--yolo", Description: "Skip confirmation"},
			{Name: "--ca-cert", Description: "Trusted certificates for verifying resource"},
			{Name: "--client-cert", Description: "Client certificate for authenticating to the resource"},
			{Name: "--client-key", Description: "Client private key for authenticating to the resource"},
			{Name: "--metadata", Description: "Resource metadata"},
			{Name: "--password", Description: "Password"},
			{Name: "--private-key-file", Description: "Path to private key file"},
			{Name: "--ssh-private-key", Description: "SSH tunneling private key"},
			{Name: "--ssh-url", Description: "SSH tunneling address"},
			{Name: "--ssl", Description: "Use SSL"},
			{Name: "--token", Description: "API Token"},
			{Name: "--url", Description: "Resource url"},
			{Name: "--username", Description: "Username"},
			{Name: "--types", Description: "List resource types"},
			{Name: "--name", Description: "New resource name"},
			{Name: "--api-url", Description: "API url"},
			{Name: "--cli-config-file", Description: "Meroxa configuration file"},
			{Name: "--debug", Description: "Display any debugging information"},
			{Name: "--json", Description: "Output json"},
			{Name: "--timeout", Description: "Set the duration of the client timeout in seconds"},
			{Name: "--help", Description: "Display help"},
		},
	})
}
