package sys

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "nextflow",
		Description: "Session ID",
		Subcommands: []spec.Subcommand{
			{Name: "clean", Description: "Clean up project cache and work directories (Default: last run)"},
			{Name: "clone", Description: "Clone a project into a folder"},
			{Name: "config", Description: "Print a project configuration"},
			{Name: "console", Description: "Launch Nextflow interactive console"},
			{Name: "drop", Description: "Delete the local copy of a project"},
			{Name: "help", Description: "Print the usage help for a command"},
			{Name: "info", Description: "Print project and system runtime information"},
			{Name: "kuberun", Description: "Execute a workflow in a Kubernetes cluster (experimental)"},
			{Name: "list", Description: "List all downloaded projects"},
			{Name: "log", Description: "Print executions log and runtime info"},
			{Name: "pull", Description: "Download or update a project"},
			{Name: "run", Description: "Execute a pipeline project"},
			{Name: "secrets", Description: "Handle and manage sensitive information for pipeline execution in a safe manner"},
			{Name: "get", Description: "Allows retrieving a secret value e.g. nextflow secrets get FOO"},
			{Name: "delete", Description: "Allows deleting an existing secret e.g. nextflow secrets delete FOO"},
			{Name: "self-update", Description: "Update nextflow runtime to the latest available version"},
			{Name: "view", Description: "View project script file(s)"},
		},
		Options: []spec.Option{
			{Name: "-after", Description: "Clean up runs executed after the specified one"},
			{Name: "-before", Description: "Clean up runs executed before the specified one"},
			{Name: "-but", Description: "Clean up all runs except the specified one"},
			{Name: "-n", Description: "Print names of file to be removed without deleting them (Default: false)"},
			{Name: "-f", Description: "Force clean command (Default: false)"},
			{Name: "-h", Description: "Print the command usage (Default: false)"},
			{Name: "-k", Description: "Do not print names of files removed (Default: false)"},
			{Name: "-hub", Description: "Service hub where the project is hosted (Default: GitHub)"},
			{Name: "-r", Description: "Revision to clone - It can be a git branch, tag or revision number"},
			{Name: "-user", Description: "Private repository user name"},
			{Name: "-flat", Description: "Print config using flat notation (Default: false)"},
			{Name: "-profile", Description: "Choose a configuration profile"},
			{Name: "-properties", Description: "Prints config using Java properties notatio (Default: false)"},
			{Name: "-a", Description: "Show all configuration profiles"},
			{Name: "-sort", Description: "Sort config attributes (Default: false)"},
			{Name: "-u", Description: "Check for remote updates (Default: false)"},
			{Name: "-d", Description: "Show detailed information (Default: false)"},
			{Name: "-o", Description: "Output format, either: text (default), json, yaml"},
			{Name: "-E", Description: "Exports all current system environment (Default: false)"},
			{Name: "-ansi-log", Description: "Enable/disable ANSI console logging"},
			{Name: "-bucket-dir", Description: "Remote bucket where intermediate result files are stored"},
			{Name: "-cache", Description: "Enable/disable processes caching"},
			{Name: "-disable-jobs-cancellation", Description: "Prevent the cancellation of child jobs on execution termination"},
			{Name: "-dsl1", Description: "Execute the workflow using DSL1 syntax (Default: false)"},
			{Name: "-dsl2", Description: "Execute the workflow using DSL2 syntax (Default: false)"},
			{Name: "-dump-channels", Description: "Dump channels for debugging purpose"},
			{Name: "-dump-hashes", Description: "Dump task hash keys for debugging purpose (Default: false)"},
			{Name: "-e", Description: "Entry workflow name to be executed"},
			{Name: "-head-cpus", Description: "Specify number of CPUs requested for the Nextflow pod (Default: 0)"},
			{Name: "-head-memory", Description: "Specify amount of memory requested for the Nextflow pod"},
			{Name: "-latest", Description: "Pull latest changes before run (Default: false)"},
			{Name: "-lib", Description: "Library extension path"},
			{Name: "-main-script", Description: "The script file to be executed when launching a project directory or repository"},
			{Name: "-name", Description: "Assign a mnemonic name to the a pipeline run"},
			{Name: "-offline", Description: "Do not check for remote project updates (Default: false)"},
			{Name: "-params-file", Description: "Load script parameters from a JSON/YAML file"},
			{Name: "-plugins", Description: "Specify the plugins to be applied for this run e.g. nf-amazon,nf-tower"},
			{Name: "-pod-image", Description: "Specify the container image for the Nextflow pod"},
			{Name: "-process", Description: "Set process options. Syntax: -process.key=value (Default: {}"},
			{Name: "-qs", Description: "Max number of processes that can be executed in parallel by each executor"},
		},
	})
}
