package sys

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "nylas",
		Description: "A command line interface for Nylas",
		Subcommands: []spec.Subcommand{
			{Name: "api", Description: "Access the Nylas API endpoints"},
			{Name: "a", Description: "A API commands"},
			{Name: "accounts", Description: "Accounts commands"},
			{Name: "delete", Description: "Delete an Account"},
			{Name: "get", Description: "Return All Accounts"},
			{Name: "accounts:downgrade", Description: "Accounts:downgrade commands"},
			{Name: "post", Description: "Cancel an Account"},
			{Name: "accounts:revoke-all", Description: "Accounts:revoke-all commands"},
			{Name: "accounts:token-info", Description: "Accounts:token-info commands"},
			{Name: "accounts:upgrade", Description: "Accounts:upgrade commands"},
			{Name: "applications", Description: "Gets your application info"},
			{Name: "calendars", Description: "Calendars API commands"},
			{Name: "availability", Description: "Availability commands"},
			{Name: "availability:consecutive", Description: "Availability:consecutive commands"},
			{Name: "free-busy", Description: "Free-busy commands"},
			{Name: "put", Description: "Update A Calendar"},
			{Name: "connect", Description: "Connect API commands"},
			{Name: "detect-provider", Description: "Detect-provider commands"},
			{Name: "contacts", Description: "Contacts API commands"},
			{Name: "groups", Description: "Groups commands"},
			{Name: "picture", Description: "Picture commands"},
			{Name: "delta", Description: "Delta API commands"},
			{Name: "latest:cursor", Description: "Latest:cursor commands"},
			{Name: "longpoll", Description: "Longpoll commands"},
			{Name: "streaming", Description: "Streaming commands"},
			{Name: "drafts", Description: "Drafts API commands"},
			{Name: "events", Description: "Events API commands"},
			{Name: "to-ics", Description: "To-ics commands"},
			{Name: "files", Description: "Files API commands"},
			{Name: "download", Description: "Download commands"},
			{Name: "folders", Description: "Folders API commands"},
			{Name: "ip-addresses", Description: "Gets a list of Nylas IP addresses (paid customers only)"},
			{Name: "job-statuses", Description: "Job-Statuses API commands"},
			{Name: "labels", Description: "Labels API commands"},
			{Name: "messages", Description: "Messages API commands"},
			{Name: "neural", Description: "Neural API commands"},
			{Name: "categorize", Description: "Categorize commands"},
			{Name: "categorize:feedback", Description: "Categorize:feedback commands"},
			{Name: "conversation", Description: "Conversation commands"},
			{Name: "conversation:feedback", Description: "Conversation:feedback commands"},
			{Name: "ocr", Description: "Ocr commands"},
			{Name: "ocr:feedback", Description: "Ocr:feedback commands"},
			{Name: "sentiment", Description: "Sentiment commands"},
			{Name: "sentiment:feedback", Description: "Sentiment:feedback commands"},
			{Name: "signature", Description: "Signature commands"},
			{Name: "signature:feedback", Description: "Signature:feedback commands"},
			{Name: "resources", Description: "Resources API commands"},
			{Name: "send", Description: "Send API commands"},
			{Name: "send-rsvp", Description: "Send-Rsvp API commands"},
			{Name: "threads", Description: "Threads API commands"},
		},
		Options: []spec.Option{
			{Name: "--display_columns", Description: "Return All Accounts"},
			{Name: "--body", Description: "Request body (or use < to redirect a JSON file)"},
			{Name: "--limit", Description: "This is usage"},
			{Name: "--country", Description: "Returns the contacts matching the contact's exact physical addresses"},
			{Name: "--group", Description: "Returns the contacts belonging to the Contact Group matching this ID"},
			{Name: "--postal_code", Description: "Returns the contacts matching the one of the contact's exact street address"},
			{Name: "--cursor", Description: "The data cursor from `/delta/latest_cursor`"},
			{Name: "--view", Description: "Streaming commands"},
			{Name: "--any_email", Description: "Return threads containing messages that were CC'd to this email address"},
			{Name: "--in", Description: "Return threads whose first message was received after this Unix-based timestamp"},
			{Name: "--started_before", Description: "Return threads whose first message was received before this Unix-based timestamp"},
			{Name: "--subject", Description: "Return threads with a matching literal subject"},
			{Name: "--thread_id", Description: "Return messages belonging to a specific thread"},
			{Name: "--to", Description: "Return threads containing messages sent to this email address"},
			{Name: "--calendar_id", Description: "Return events belonging to the specified calendar ID"},
			{Name: "--count", Description: "See [Count](/docs/api/#overview--count-view) for more information"},
			{Name: "--description", Description: "Return events matching the specified description"},
			{Name: "--ends_before", Description: "Return events ending before the specified unix timestamp"},
			{Name: "--event_id", Description: "Return the event matching the specified event ID"},
			{Name: "--metadata_key", Description: "Return events starting after the specified unix timestamp"},
			{Name: "--starts_before", Description: "Return events starting before the specified unix timestamp"},
			{Name: "--title", Description: "Return events matching the specified title"},
			{Name: "--content_type", Description: "Return objects matching the specified content type"},
			{Name: "--message_id", Description: "Return objects matching the specified message ID"},
			{Name: "--from", Description: "Return threads containing messages sent from this email address"},
			{Name: "--received_before", Description: "Return messages received before this unix timestamp"},
			{Name: "--callback_domain", Description: "The domain for the callback URL"},
			{Name: "--forward", Description: "Address to forward requests to (e.g. http://localhost:3000)"},
			{Name: "--print", Description: "Prints the (json) payload to the console"},
			{Name: "--triggers", Description: "The triggers to register for your webhooks"},
			{Name: "--websocket_domain", Description: "The domain for the websocket server"},
			{Name: "--access_token", Description: "Nylas account access token"},
			{Name: "--config_dir", Description: "Config directory"},
			{Name: "--config_file", Description: "Config file (default is config.yaml)"},
			{Name: "--dashboard_api_url", Description: "Dashboard API URL"},
			{Name: "--debug", Description: "Enable debugging output"},
			{Name: "--disable_telemetry", Description: "Disables sending telemetry data"},
			{Name: "--nylas_api_url", Description: "Nylas API URL"},
			{Name: "--output", Description: "Output format (e.g. json, table)"},
			{Name: "--region", Description: "Nylas Region (values: us, ireland, canada, australia)"},
		},
	})
}
