package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "sanity",
		Description: "Displays help information about Sanity",
		Subcommands: []core.Subcommand{
			{Name: "help", Description: "Displays help information about Sanity"},
			{Name: "build", Description: "Builds the current Sanity configuration to a static bundle"},
			{Name: "codemod", Description: "Runs a code modification script"},
			{Name: "configcheck", Description: "Checks if the required configuration files for plugins exists and are up to date"},
			{Name: "cors", Description: "Interact with CORS-entries for your project"},
			{Name: "add", Description: "Allow a new origin to use your project API through CORS"},
			{Name: "origin", Description: "The origin to allow"},
			{Name: "delete", Description: "Delete an existing CORS-origin from your project"},
			{Name: "list", Description: "List all origins allowed to access the API for this project"},
			{Name: "dataset", Description: "Interact with datasets in your project"},
			{Name: "alias", Description: "You can manage your dataset alias using this command"},
			{Name: "create", Description: "Create a new dataset within your project"},
			{Name: "export", Description: "Export dataset to local filesystem as a gzipped tarball"},
			{Name: "import", Description: "Import documents to given dataset from ndjson file"},
			{Name: "visibility", Description: "Set visibility of a dataset"},
			{Name: "debug", Description: "Gathers information on Sanity environment"},
			{Name: "deploy", Description: "Deploys a statically built Sanity studio"},
			{Name: "docs", Description: "Opens the Sanity documentation"},
			{Name: "documents", Description: "Interact with documents in your project"},
			{Name: "get", Description: "Get and print a document by ID"},
			{Name: "query", Description: "Query for documents"},
			{Name: "exec", Description: "Runs a script in Sanity context"},
			{Name: "graphql", Description: "Interact with GraphQL APIs"},
			{Name: "undeploy", Description: "Remove a deployed GraphQL API"},
			{Name: "hook", Description: "Interact with hooks in your project"},
			{Name: "attempt", Description: "Print details of a given webhook delivery attempt"},
			{Name: "logs", Description: "List latest log entries for a given hook"},
			{Name: "init", Description: "Initialize a new Sanity project or plugin"},
			{Name: "install", Description: "Installs a Sanity plugin to the current Sanity configuration"},
			{Name: "logout", Description: "Logs out of the Sanity.io session"},
			{Name: "manage", Description: "Opens the Sanity project management UI"},
			{Name: "projects", Description: "Interact with projects connected to your logged in user"},
			{Name: "start", Description: "Starts a web server for the Content Studio"},
			{Name: "uninstall", Description: "Removes a Sanity plugin from the current Sanity configuration"},
			{Name: "upgrade", Description: "Upgrades all (or some) Sanity modules to their latest versions"},
			{Name: "users", Description: "Manage users of your project"},
			{Name: "invite", Description: "Invite a new user to the project"},
			{Name: "versions", Description: "Shows the installed versions of Sanity CLI and core components"},
		},
		Options: []core.Option{
			{Name: "--source-maps", Description: "Enable source maps for built bundles (increases size of bundle)"},
			{Name: "--no-minify", Description: "Skip minifying built JavaScript (speeds up build, increases size of bundle)"},
			{Name: "-y", Description: "Use unattended mode, accepting defaults and using only flags for choices"},
			{Name: "--dry", Description: "Dry run (no changes are made to files)"},
			{Name: "--extensions", Description: "Skip verification before running codemod"},
			{Name: "--credentials", Description: "Allow credentials (token/cookie) to be sent from this origin"},
			{Name: "--no-credentials", Description: "Disallow credentials (token/cookie) to be sent from this origin"},
			{Name: "--force", Description: "Skips security prompt and forces link command"},
			{Name: "--detach", Description: "Start the copy without waiting for it to finish"},
			{Name: "--attach", Description: "Attach to the running copy process to show progress"},
			{Name: "--skip-history", Description: "Don't preserve document history on copy"},
			{Name: "--list", Description: "Lists all dataset copy jobs corresponding to a certain criteria"},
			{Name: "--offset", Description: "Start position in the list of jobs. Default 0. With --list"},
			{Name: "--limit", Description: "Maximum number of jobs returned. Default 10. Maximum 1000. With --list"},
			{Name: "--visibility", Description: "Set visibility for this dataset (public/private)"},
			{Name: "--raw", Description: "Extract only documents, without rewriting asset references"},
			{Name: "--no-assets", Description: "Export only non-asset documents and remove references to image assets"},
			{Name: "--no-drafts", Description: "Export only published versions of documents"},
			{Name: "--no-compress", Description: "Skips compressing tarball entries (still generates a gzip file)"},
			{Name: "--types", Description: "Defines which document types to export"},
			{Name: "--overwrite", Description: "Overwrite any file with the same name"},
			{Name: "--asset-concurrency", Description: "Concurrent number of asset downloads"},
			{Name: "--missing", Description: "On duplicate document IDs, skip importing document in question"},
			{Name: "--replace", Description: "On duplicate document IDs, replace existing document with imported document"},
			{Name: "--allow-failing-assets", Description: "Skip assets that cannot be fetched/uploaded"},
			{Name: "--replace-assets", Description: "Skip reuse of existing assets"},
			{Name: "--secrets", Description: "Include API keys in output"},
			{Name: "--no-build", Description: "Opens the Sanity documentation"},
			{Name: "--watch", Description: "Write the documents whenever the target file or buffer changes"},
			{Name: "--json5", Description: "Specify a document ID to use. Will fetch remote document ID and populate editor"},
			{Name: "--dataset", Description: "NAME to override dataset"},
			{Name: "--pretty", Description: "Colorized JSON output"},
			{Name: "--api-version", Description: "API version to use (defaults to `v1`)"},
			{Name: "--with-user-token", Description: "Preload access token from CLI config into 'part:@sanity/base/client' part"},
			{Name: "--mock-browser-env", Description: "Mocks a browser-like environment using jsdom"},
			{Name: "--tag", Description: "Deploy API to given tag (defaults to 'default')"},
			{Name: "--generation", Description: "API generation to deploy (defaults to 'gen3')"},
			{Name: "--non-null-document-fields", Description: "Set document interface fields (_id, _type etc) as non-null"},
			{Name: "--playground", Description: "Deploy a GraphQL playground for easily testing queries (public)"},
			{Name: "--no-playground", Description: "Skip playground prompt (do not deploy a playground)"},
		},
	})
}
