package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "sysctl",
		Description: "Variable name",
		Options: []core.Option{
			{Name: "-A", Description: "List all the currently available non-opaque values"},
			{Name: "-b", Description: "Force the value of the variable(s) to be output in raw, binary format"},
			{Name: "-d", Description: "Print the description of the variable instead of its value"},
			{Name: "-e", Description: "Separate the name and the value of the variable(s) with '='"},
			{Name: "-h", Description: "Format output for human, rather than machine, readability"},
			{Name: "-i", Description: "Ignore unknown OIDs"},
			{Name: "-N", Description: "Show only variable names, not their values"},
			{Name: "-n", Description: "Show only variable values, not their names"},
			{Name: "-o", Description: "Show opaque variables (which are normally suppressed)"},
			{Name: "-q", Description: "Suppress some warnings generated by sysctl to standard error"},
			{Name: "-X", Description: "Equivalent to -x -a (for compatibility)"},
		},
	})
}
