package sys

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "wp",
		Description: "Path to the WordPress files",
		Subcommands: []core.Subcommand{
			{Name: "cache", Description: "Adds, removes, fetches, and flushes the WP Object Cache object"},
			{Name: "add", Description: "Adds a value to the object cache"},
			{Name: "key", Description: "Cache key"},
			{Name: "value", Description: "Value to add to the key"},
			{Name: "expiration", Description: "Define how long to keep the value, in seconds. 0 means as long as possible"},
			{Name: "decr", Description: "Decrements a value in the object cache"},
			{Name: "offset", Description: "The amount by which to decrement the item’s value"},
			{Name: "delete", Description: "Removes a value from the object cache"},
			{Name: "flush", Description: "Flushes the object cache"},
			{Name: "get", Description: "Gets a value from the object cache"},
			{Name: "incr", Description: "Increments a value in the object cache"},
			{Name: "replace", Description: "Replaces a value in the object cache, if the value already exists"},
			{Name: "set", Description: "Sets a value to the object cache, regardless of whether it already exists"},
			{Name: "type", Description: "Attempts to determine which object cache is being used"},
			{Name: "cap", Description: "Adds, removes, and lists capabilities of a user role"},
			{Name: "role", Description: "Key for the role"},
			{Name: "list", Description: "Lists capabilities for a given role"},
			{Name: "remove", Description: "Removes capabilities from a given role"},
			{Name: "cli", Description: "Reviews current WP-CLI info, checks for updates, or views defined aliases"},
			{Name: "alias", Description: "Retrieves, sets and updates aliases for WordPress Installations"},
			{Name: "update", Description: "Updates an alias"},
			{Name: "clear", Description: "Clears the internal cache"},
			{Name: "prune", Description: "Prunes the internal cache"},
			{Name: "check-update", Description: "Checks to see if there is a newer version of WP-CLI available"},
			{Name: "cmd-dump", Description: "Dumps the list of installed commands, as JSON"},
			{Name: "completions", Description: "Generates tab completion strings"},
			{Name: "has-command", Description: "Detects if a command exists"},
			{Name: "command_name", Description: "The command"},
			{Name: "info", Description: "Prints various details about the WP-CLI environment"},
			{Name: "param-dump", Description: "Dumps the list of global parameters, as JSON or in var_export format"},
			{Name: "version", Description: "Prints WP-CLI version"},
			{Name: "comment", Description: "Creates, updates, deletes, and moderates comments"},
			{Name: "approve", Description: "Approves a comment"},
			{Name: "id", Description: "The IDs of the comments to approve"},
			{Name: "count", Description: "Counts comments, on whole blog or on a given post"},
			{Name: "post-id", Description: "The ID of the post to count comments in"},
			{Name: "create", Description: "Creates a new comment"},
			{Name: "exists", Description: "Verifies whether a comment exists"},
			{Name: "generate", Description: "Generates some number of new dummy comments"},
			{Name: "meta", Description: "Adds, updates, deletes, and lists comment custom fields"},
			{Name: "patch", Description: "Update a nested value for a meta field"},
			{Name: "options", Description: "Patch action to perform"},
			{Name: "key-path", Description: "The name(s) of the keys within the value to locate the value to patch"},
			{Name: "pluck", Description: "Get a nested value from a meta field"},
			{Name: "recount", Description: "Recalculates the comment_count value for one or more posts"},
			{Name: "spam", Description: "Marks a comment as spam"},
			{Name: "status", Description: "Gets the status of a comment"},
			{Name: "trash", Description: "Trashes a comment"},
			{Name: "unapprove", Description: "Unapproves a comment"},
			{Name: "unspam", Description: "Unmarks a comment as spam"},
		},
		Options: []core.Option{
			{Name: "--path", Description: "Path to the WordPress files"},
			{Name: "--url", Description: "Perform operation against a remote WordPress installation over HTTP"},
			{Name: "--user", Description: "Set the WordPress user"},
			{Name: "--skip-plugins", Description: "Skip loading all themes, or a comma-separated list of themes"},
			{Name: "--skip-themes", Description: "Skip loading all themes, or a comma-separated list of themes"},
			{Name: "--skip-packages", Description: "Skip loading all installed packages"},
			{Name: "--require", Description: "Load PHP file before running the command (may be used more than once)"},
			{Name: "--exec", Description: "Execute PHP code before running the command (may be used more than once)"},
			{Name: "--color", Description: "Whether to colorize the output"},
			{Name: "--no-color", Description: "Whether to colorize the output"},
			{Name: "--debug", Description: "Suppress informational messages"},
			{Name: "--grant", Description: "Lists capabilities for a given role"},
			{Name: "--format", Description: "Render output in a particular format"},
			{Name: "--show-grant", Description: "Display all capabilities defined for a role including grant"},
			{Name: "--set-user", Description: "Set user for alias"},
			{Name: "--set-url", Description: "Set url for alias"},
			{Name: "--set-path", Description: "Set path for alias"},
			{Name: "--set-ssh", Description: "Set ssh for alias"},
			{Name: "--set-http", Description: "Set http for alias"},
			{Name: "--grouping", Description: "For grouping multiple aliases"},
			{Name: "--config", Description: "Config file to be considered for operations"},
			{Name: "--patch", Description: "Only list patch updates"},
			{Name: "--minor", Description: "Only list minor updates"},
			{Name: "--major", Description: "Only list major updates"},
			{Name: "--field", Description: "Prints the value of a single field for each update"},
			{Name: "--fields", Description: "Render output in a particular format"},
			{Name: "--line", Description: "The current command line to be executed"},
			{Name: "--point", Description: "Detects if a command exists"},
			{Name: "--with-values", Description: "Display current values also"},
			{Name: "--stable", Description: "Update to the latest stable release. Skips update check"},
			{Name: "--nightly", Description: "Update to the latest built version of the master branch. Potentially unstable"},
			{Name: "--yes", Description: "Do not prompt for confirmation"},
			{Name: "--insecure", Description: "Prints WP-CLI version"},
			{Name: "--porcelain", Description: "Output just the new comment id"},
			{Name: "--force", Description: "Skip the trash bin"},
			{Name: "--count", Description: "How many comments to generate?"},
			{Name: "--post_id", Description: "Assign comments to a specific post"},
			{Name: "--all", Description: "Delete all meta for the object"},
			{Name: "--keys", Description: "Limit output to metadata of specific keys"},
			{Name: "--orderby", Description: "Set orderby which field"},
		},
	})
}
