package sys

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "zapier",
		Description: "Change the way structured data is presented. If",
		Subcommands: []spec.Subcommand{
			{Name: "build", Description: "Build a pushable zip from the current directory"},
			{Name: "path", Description: "Relative to your current path - IE: `.` for current directory"},
			{Name: "delete:integration", Description: "Delete your integration (including all versions)"},
			{Name: "delete:version", Description: "Delete a specific version of your integration"},
			{Name: "version", Description: "Specify the version to delete. It must have no users or Zaps"},
			{Name: "date", Description: "The date (YYYY-MM-DD) when Zapier will make the specified version unavailable"},
			{Name: "describe", Description: "Describe the current integraiton"},
			{Name: "env:get", Description: "Get environment variables for a version"},
			{Name: "env:set", Description: "Set environment variables for a version"},
			{Name: "env:unset", Description: "Unset environment variables for a version"},
			{Name: "keys...", Description: "The keys to unset. Keys are case-insensitive"},
			{Name: "history", Description: "Get the history of your integration"},
			{Name: "init", Description: "Initialize a new Zapier integration with a project template"},
			{Name: "integrations", Description: "List integrations you have admin access to"},
			{Name: "link", Description: "Link the current directory with an existing integration"},
			{Name: "login", Description: "Configure your `~/.zapierrc` with a deploy key"},
			{Name: "logout", Description: "Deactivate your active deploy key and reset `~/.zapierrc`"},
			{Name: "logs", Description: "Print recent logs"},
			{Name: "migrate", Description: "Migrate users from one version of your integration to another"},
			{Name: "fromVersion", Description: "The version FROM which to migrate users"},
			{Name: "toVersion", Description: "The version TO which to migrate users"},
			{Name: "percent", Description: "Percentage (between 1 and 100) of users to migrate"},
			{Name: "promote", Description: "Promote a specific version to public access"},
			{Name: "push", Description: "Build and upload the current integration"},
			{Name: "register", Description: "Register a new integration in your account"},
			{Name: "title", Description: "Your integrations's public title. Asked interactively if not present"},
			{Name: "scaffold", Description: "Add a starting trigger, create, search, or resource to your integration"},
			{Name: "team:add", Description: "Add a team member to your integration"},
			{Name: "team:get", Description: "Get team members involved with your integration"},
			{Name: "team:remove", Description: "Remove a team member from all versions of your integration"},
			{Name: "upload", Description: "Upload the latest build of your integration to Zapier"},
			{Name: "users:add", Description: "Add a user to some or all versions of your integration"},
			{Name: "users:get", Description: "Get a list of users who have been invited to your integration"},
			{Name: "users:links", Description: "Get a list of links that are used to invite users to your integration"},
			{Name: "users:remove", Description: "Remove a user from all versions of your integration"},
			{Name: "email", Description: "The user to be removed"},
			{Name: "validate", Description: "Validate your integration"},
			{Name: "versions", Description: "List the versions of your integration available for use in the Zapier editor"},
			{Name: "help", Description: "Display help for zapier"},
			{Name: "command", Description: "Command to show help for"},
		},
		Options: []spec.Option{
			{Name: "-f", Description: "Show extra debugging output"},
			{Name: "-m", Description: "Build a pushable zip from the current directory"},
			{Name: "-t", Description: "The template to start your integration with"},
			{Name: "-s", Description: "Deactivate your active deploy key and reset `~/.zapierrc`"},
			{Name: "-v", Description: "Filter logs to the specified version"},
			{Name: "--detailed", Description: "See extra info, like request/response body and headers"},
			{Name: "-u", Description: "Only show logs for this user. Defaults to your account"},
			{Name: "--limit", Description: "Cap the number of logs returned. Max is 50 (also the default)"},
			{Name: "--user", Description: "Migrate only this user"},
			{Name: "-d", Description: "Should we overwrite an existing trigger/search/create file?"},
			{Name: "--no-help", Description: "Add a team member to your integration"},
			{Name: "--skip-validate", Description: "Upload the latest build of your integration to Zapier"},
			{Name: "--without-style", Description: "Forgo pinging the Zapier server to run further checks"},
			{Name: "--all", Description: "See all commands in CLI"},
		},
	})
}
