border = "#A277FF"
accent = "#61FFCA"
muted = "#77738A"
text = "#EDECEE"
text_sel = "#FFFFFF"
match = "#72FFD3"
desc = "#A7A3B8"
desc_sel = "#FFFFFF"
sel_bg = "#4A426D"
scroll_info = "#B58CFF"
ghost_text = "#66636F"
hist = "#3BAE96"
hist_sel = "#61FFCA"
sys = "#B9576C"
sys_sel = "#FF677D"
alias = "#74A965"
alias_sel = "#A6FF8F"
