package jvm

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "dart",
		Description: "The Dart file containing the main function",
		Subcommands: []core.Subcommand{
			{Name: "analyze", Description: "Analyze Dart code in a directory"},
			{Name: "directory", Description: "Dart project directory to analyze"},
			{Name: "compile", Description: "Compile Dart to various formats"},
			{Name: "aot-snapshot", Description: "Compile Dart to an AOT snapshot"},
			{Name: "exe", Description: "Compile Dart to a self-contained executable"},
			{Name: "jit-snapshot", Description: "Compile Dart to a JIT snapshot"},
			{Name: "js", Description: "Compile Dart to JavaScript"},
			{Name: "kernel", Description: "Compile Dart to a kernel snapshot"},
			{Name: "create", Description: "Create a new Dart project"},
			{Name: "console", Description: "A simple command-line application"},
			{Name: "package", Description: "A starting point for Dart libraries or applications"},
			{Name: "server-shelf", Description: "A web server built using package:shelf"},
			{Name: "web", Description: "A web app that uses only core Dart libraries"},
			{Name: "fix", Description: "Apply automated fixes to Dart source code"},
			{Name: "format", Description: "Idiomatically format Dart source code"},
			{Name: "json", Description: "Print code and selection as JSON"},
			{Name: "none", Description: "Discard output"},
			{Name: "show", Description: "Print code to terminal"},
			{Name: "write", Description: "Overwrite formatted files on disk"},
			{Name: "all", Description: "All visited files and directories"},
			{Name: "changed", Description: "Nly the names of files whose formatting is changed"},
			{Name: "line", Description: "Single-line summary"},
			{Name: "profile", Description: "How long it took to format each file"},
			{Name: "line-length", Description: "Line length to wrap"},
			{Name: "files-or-directory", Description: "The files or directories to format"},
			{Name: "migrate", Description: "Perform null safety migration on a project"},
			{Name: "pub", Description: "Work with packages"},
			{Name: "add", Description: "Add a dependency to pubspec.yaml"},
			{Name: "cache", Description: "Work with the Pub system cache"},
			{Name: "repair", Description: "Reinstall a cached package"},
			{Name: "deps", Description: "Print package dependencies"},
			{Name: "downgrade", Description: "Downgrade packages in a Flutter project"},
			{Name: "get", Description: "Get packages in a Flutter project"},
			{Name: "global", Description: "Work with Pub global packages"},
			{Name: "activate", Description: "Make a package's executables globally available"},
			{Name: "deactivate", Description: "Remove a previously activated package"},
			{Name: "list", Description: "List globally activated packages"},
			{Name: "run", Description: "Run an executable from a globally activated package"},
			{Name: "login", Description: "Log into pub.dev"},
			{Name: "logout", Description: "Log out of pub.dev"},
			{Name: "outdated", Description: "Analyze dependencies to find which ones can be upgraded"},
			{Name: "publish", Description: "Publish the current package to pub.dartlang.org"},
			{Name: "remove", Description: "Removes a dependency from the current package"},
			{Name: "upgrade", Description: "Upgrade the current package's dependencies to latest versions"},
			{Name: "uploader", Description: "Manage uploaders for a package on pub.dev"},
			{Name: "const-functions", Description: "Allow more of the Dart language to be executed in const expressions"},
			{Name: "extension-methods", Description: "Extension methods (no-op - enabled by default)"},
			{Name: "extension-types", Description: "Extension types"},
			{Name: "non-nullable", Description: "Non-nullable by default. (no-op - on by default)"},
			{Name: "triple-shift", Description: "Triple-shift operator"},
		},
		Options: []core.Option{
			{Name: "--offline", Description: "Use cached packages instead of accessing the network"},
			{Name: "--no-offline", Description: "Do not use cached packages instead of accessing the network"},
			{Name: "-n", Description: "Report what dependencies would change but don't change any"},
			{Name: "--precompile", Description: "Precompile executables in immediate dependencies"},
			{Name: "--no-precompile", Description: "Do not precompile executables in immediate dependencies"},
			{Name: "--enable-asserts", Description: "Enable assert statements"},
			{Name: "--no-enable-asserts", Description: "Do not enable assert statements"},
			{Name: "-D", Description: "Key-value pairs to define in Dart script"},
			{Name: "--verbosity", Description: "Sets the verbosity level of the compilation"},
			{Name: "-h", Description: "Print this usage information"},
			{Name: "-o", Description: "Write the output to <file-name>"},
			{Name: "-p", Description: "The path to draw packages from"},
			{Name: "--no-sound-null-safety", Description: "Respect the nullability of types at runtime"},
			{Name: "-S", Description: "The path to write debugging info to"},
			{Name: "-v", Description: "Print verbose output"},
			{Name: "--version", Description: "Current Dart version"},
			{Name: "--enable-analytics", Description: "Enables analytics"},
			{Name: "--disable-analytics", Description: "Disables analytics"},
			{Name: "--fatal-infos", Description: "Treat info level issues as fatal"},
			{Name: "--fatal-warnings", Description: "Treat warning level issues as fatal (defaults to on)"},
			{Name: "--no-fatal-warnings", Description: "Do not treat warning level issues as fatal (defaults to on)"},
			{Name: "-m", Description: "Generate minified output"},
			{Name: "-t", Description: "The project template to use"},
			{Name: "--pub", Description: "Run 'pub get' after the project has been created. Default to on"},
			{Name: "--no-pub", Description: "Do not run 'pub get' after the project has been created. Default to on"},
			{Name: "--force", Description: "Force project generation, even if the target directory already exists"},
			{Name: "--apply", Description: "Apply the proposed changes"},
			{Name: "--show", Description: "Set which filenames to print"},
			{Name: "--summary", Description: "Show the specified summary after formatting"},
			{Name: "--set-exit-if-changed", Description: "Return exist code 1 if there are any formatting changes"},
			{Name: "--fix", Description: "Apply all style fixes"},
			{Name: "--fix-doc-comments", Description: "Use triple slash for documentation comments"},
			{Name: "--fix-function-typedefs", Description: "Use new syntax for function type typedefs"},
			{Name: "--fix-named-default-separator", Description: "Use '=' as the separator before named parameter default values"},
			{Name: "--fix-optional-const", Description: "Remove 'const' keyword inside constant context"},
			{Name: "--fix-optional-new", Description: "Remove 'new' keyword"},
			{Name: "-l", Description: "Wrap lines longer than this. Defaults to 80"},
			{Name: "-i", Description: "Add this many spaces of leading indentation"},
			{Name: "--follow-links", Description: "Follow links to files and directories. If unset, links will be ignored"},
			{Name: "--selection", Description: "Track selection (given as 'start:length') through formatting"},
		},
	})
}
