package jvm

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "flutter",
		Description: "Available emulators",
		Subcommands: []spec.Subcommand{
			{Name: "analyze", Description: "Analyze the project's Dart code"},
			{Name: "assemble", Description: "Assemble and build Flutter resources"},
			{Name: "attach", Description: "Attach to a running app"},
			{Name: "bash-completion", Description: "Output command line shell completion setup scripts"},
			{Name: "build", Description: "Build an executable app or install bundle"},
			{Name: "aar", Description: "Build a repository containing an AAR and a POM file"},
			{Name: "apk", Description: "Build an Android APK file from your app"},
			{Name: "appbundle", Description: "Build an Android App Bundle file from your app"},
			{Name: "bundle", Description: "Build the Flutter assets directory from your app"},
			{Name: "ios", Description: "Build an iOS application bundle (Mac OS X host only)"},
			{Name: "ipa", Description: "Build an iOS archive bundle (Mac OS X host only)"},
			{Name: "web", Description: "Build a web application bundle"},
			{Name: "channel", Description: "List or switch Flutter channels"},
			{Name: "channel-name", Description: "Switch to <channel name>. Leave this blank to see available channels"},
			{Name: "clean", Description: "Delete the build/ and .dart_tool/ directories"},
			{Name: "config", Description: "Configure Flutter settings"},
			{Name: "create", Description: "Create a new Flutter project"},
			{Name: "devices", Description: "List all connected devices"},
			{Name: "doctor", Description: "Show information about the installed tooling"},
			{Name: "downgrade", Description: "Downgrade Flutter to the last active version for the current channel"},
			{Name: "drive", Description: "Run integration tests for the project on an attached device or emulator"},
			{Name: "emulators", Description: "List, launch and create emulators"},
			{Name: "format", Description: "Format one or more Dart files"},
			{Name: "gen-l10n", Description: "Generate localizations for the current project"},
			{Name: "install", Description: "Install a Flutter app on an attached device"},
			{Name: "logs", Description: "Show log output for running Flutter apps"},
			{Name: "pub", Description: "Commands for managing Flutter packages"},
			{Name: "add", Description: "Add a dependency to pubspec.yaml"},
			{Name: "cache", Description: "Work with the Pub system cache"},
			{Name: "deps", Description: "Print package dependencies"},
			{Name: "get", Description: "Get packages in a Flutter project"},
			{Name: "global", Description: "Work with Pub global packages"},
			{Name: "login", Description: "Log into pub.dev"},
			{Name: "logout", Description: "Log out of pub.dev"},
			{Name: "outdated", Description: "Analyze dependencies to find which ones can be upgraded"},
			{Name: "publish", Description: "Publish the current package to pub.dartlang.org"},
			{Name: "remove", Description: "Removes a dependency from the current package"},
			{Name: "run", Description: "Run an executable from a package"},
			{Name: "upgrade", Description: "Upgrade the current package's dependencies to latest versions"},
			{Name: "uploader", Description: "Manage uploaders for a package on pub.dev"},
			{Name: "version", Description: "Print Pub version"},
			{Name: "screenshot", Description: "Take a screenshot from a connected device"},
			{Name: "symbolize", Description: "Symbolize a stack trace from an AOT-compiled Flutter app"},
			{Name: "file path", Description: "A file path for a symbolized stack trace to be written to"},
			{Name: "test", Description: "Run Flutter unit tests for the current project"},
		},
		Options: []spec.Option{
			{Name: "-h", Description: "Print this usage information"},
			{Name: "-v", Description: "Target device id or name (prefixes allowed)"},
			{Name: "--version", Description: "Reports the version of this tool"},
			{Name: "--suppress-analytics", Description: "Suppress analytics reporting when this command runs"},
			{Name: "--pub", Description: "Run 'flutter pub get' before executing this command"},
			{Name: "--no-pub", Description: "Don't run 'flutter pub get' before executing this command"},
			{Name: "--current-package", Description: "Analyze the current project, if applicable"},
			{Name: "--no-current-package", Description: "Don't analyze the current project, if applicable"},
			{Name: "--congratulate", Description: "Treat info level issues as fatal"},
			{Name: "--no-fatal-infos", Description: "Don't treat info level issues as fatal"},
			{Name: "--fatal-warnings", Description: "Treat warning level issues as fatal"},
			{Name: "--no-fatal-warnings", Description: "Don't treat warning level issues as fatal"},
			{Name: "--null-assertions", Description: "Exclude the assets bundle for build testing"},
			{Name: "--uninstall-only", Description: "Uninstall the app if already on the device. Skip install"},
			{Name: "--no-uninstall-only", Description: "Don't generate the Dart localization file with locales imported as deferred"},
			{Name: "--synthetic-package", Description: "Start in a paused mode and wait for a debugger to connect"},
			{Name: "--no-start-paused", Description: "When performing operations, overwrite existing files"},
			{Name: "--no-overwrite", Description: "Enable reporting anonymously tool usage statistics and crash reports"},
			{Name: "--no-analytics", Description: "Disable reporting anonymously tool usage statistics and crash reports"},
			{Name: "--enable-web", Description: "Enable Flutter for Fuchsia. This setting will take effect on the master channel"},
			{Name: "--no-enable-fuchsia", Description: "Disable Flutter for Fuchsia. This setting will take effect on the master channel"},
			{Name: "--profile", Description: "Build a version of your app specialized for performance profiling"},
			{Name: "-t", Description: "Build a release version of your app"},
			{Name: "--flavor", Description: "Trace application startup, then exit, saving the trace to a file"},
			{Name: "--verbose-system-logs", Description: "Include verbose logging from the flutter engine"},
			{Name: "--cache-sksl", Description: "Only cache the shader in SkSL instead of binary or GLSL"},
			{Name: "--vmservice-out-file", Description: "Run flutter command"},
			{Name: "--watch", Description: "Run analysis continuously, watching the filesystem for changes"},
			{Name: "--write", Description: "Assemble and build Flutter resources"},
			{Name: "-d", Description: "Allows passing configuration to a target with --define=target=key=value"},
			{Name: "-i", Description: "Treat warning level issues as fatal"},
			{Name: "--depfile", Description: "The maximum number of concurrent tasks the build system will run"},
			{Name: "--debug-uri", Description: "The URI at which the observatory is listening"},
			{Name: "--app-id", Description: "Output command line shell completion setup scripts"},
			{Name: "--clear-ios-signing-cert", Description: "The Android SDK directory"},
			{Name: "--android-studio-dir", Description: "The Android Studio install directory"},
			{Name: "--build-dir", Description: "The relative path to override a projects build directory"},
			{Name: "--clear-features", Description: "Remove all configured features and restore them to the default values"},
			{Name: "--description", Description: "[objc, swift (default)]"},
			{Name: "-a", Description: "[java, kotlin (default)]"},
		},
	})
}
