package js

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "deno",
		Description: "A modern JavaScript and TypeScript runtime",
		Subcommands: []spec.Subcommand{
			{Name: "bench", Description: "Run benchmarks"},
			{Name: "bundle", Description: "Bundle module and dependencies into single file"},
			{Name: "cache", Description: "Cache the dependencies"},
			{Name: "check", Description: "Type-check the dependencies"},
			{Name: "compile", Description: "UNSTABLE: Compile the script into a self contained executable"},
			{Name: "completions", Description: "Generate shell completions"},
			{Name: "coverage", Description: "Print coverage reports"},
			{Name: "doc", Description: "Show documentation for a module"},
			{Name: "eval", Description: "Eval script"},
			{Name: "fmt", Description: "Format source files"},
			{Name: "init", Description: "Initialize a new project"},
			{Name: "info", Description: "Show info about cache or info related to source file"},
			{Name: "install", Description: "Install script as an executable"},
			{Name: "uninstall", Description: "Uninstall a script previously installed with deno install"},
			{Name: "lsp", Description: "Start the language server"},
			{Name: "lint", Description: "Lint source files"},
			{Name: "repl", Description: "Read Eval Print Loop"},
			{Name: "run", Description: "Run a JavaScript or TypeScript program"},
			{Name: "task", Description: "Run a task defined in the configuration file"},
			{Name: "test", Description: "Run tests"},
			{Name: "types", Description: "Print runtime TypeScript declarations"},
			{Name: "upgrade", Description: "Upgrade deno executable to given version"},
			{Name: "vendor", Description: "Vendor remote modules into a local directory"},
			{Name: "help", Description: "Print this message or the help of the given subcommand(s)"},
		},
		Options: []spec.Option{
			{Name: "--import-map", Description: "Load import map file"},
			{Name: "-c", Description: "Specify the configuration file"},
			{Name: "--no-check", Description: "Skip type-checking modules"},
			{Name: "--check", Description: "Type-check modules"},
			{Name: "-r", Description: "Reload source code cache (recompile TypeScript)"},
			{Name: "--lock", Description: "Check the specified lock file"},
			{Name: "--cert", Description: "Load certificate authority from PEM encoded file"},
			{Name: "--allow-read", Description: "Allow file system read access"},
			{Name: "--allow-write", Description: "Allow file system write access"},
			{Name: "--allow-net", Description: "Allow network access"},
			{Name: "--allow-env", Description: "Allow environment access"},
			{Name: "--allow-run", Description: "Allow running subprocesses"},
			{Name: "--allow-ffi", Description: "Allow loading dynamic libraries"},
			{Name: "--location", Description: "Value of 'globalThis.location' used by some web APIs"},
			{Name: "--v8-flags", Description: "Set V8 command line options"},
			{Name: "--seed", Description: "Set the random number generator seed"},
			{Name: "--ignore", Description: "Ignore files"},
			{Name: "--filter", Description: "Run benchmarks with this string or pattern in the bench name"},
			{Name: "-L", Description: "Set log level"},
			{Name: "--no-remote", Description: "Do not resolve remote modules"},
			{Name: "--no-config", Description: "Disable automatic loading of the configuration file"},
			{Name: "--lock-write", Description: "Write lock file (use with --lock)"},
			{Name: "--allow-hrtime", Description: "Allow high resolution time measurement"},
			{Name: "-A", Description: "Allow all permissions"},
			{Name: "--prompt", Description: "Deprecated: Fallback to prompt if required permission wasn't passed"},
			{Name: "--no-prompt", Description: "Always throw if required permission wasn't passed"},
			{Name: "--cached-only", Description: "Require that remote dependencies are already cached"},
			{Name: "--compat", Description: "UNSTABLE: Node compatibility mode"},
			{Name: "--watch", Description: "Watch for file changes and restart automatically"},
			{Name: "--no-clear-screen", Description: "Do not clear terminal screen when under watch mode"},
			{Name: "-h", Description: "Print help information"},
			{Name: "--unstable", Description: "Enable unstable features and APIs"},
			{Name: "-q", Description: "Suppress diagnostic output"},
			{Name: "--remote", Description: "Type-check all modules, including remote"},
			{Name: "-o", Description: "Output file (defaults to $PWD/<inferred-name>)"},
			{Name: "--target", Description: "Target OS architecture"},
			{Name: "--include", Description: "Include source files in the report"},
			{Name: "--exclude", Description: "Exclude source files from the report"},
			{Name: "--output", Description: "Output file (defaults to stdout) for lcov"},
			{Name: "--lcov", Description: "Output coverage report in lcov format"},
		},
	})
}
