package js

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "meteor",
		Description: "Run the meteor command-line tool",
		Subcommands: []spec.Subcommand{
			{Name: "help", Description: "Get help on meteor command line usage"},
			{Name: "command", Description: "Built-in command"},
			{Name: "list", Description: "Lists the packages that you have explicitly added to your project"},
			{Name: "remove-platform", Description: "Removes a platform previously added to your Meteor project"},
			{Name: "list-platforms", Description: "Lists all of the platforms added to your project"},
			{Name: "ensure-cordova-dependencies", Description: "Check if the dependencies are installed, otherwise install them"},
			{Name: "lint", Description: "Run through the whole build process for the app and run all linters the app uses"},
			{Name: "reset", Description: "Reset the current project to a fresh state. Removes all local data"},
			{Name: "deploy", Description: "Deploys the project in your current directory to Meteor's servers"},
			{Name: "milliseconds", Description: "Milliseconds to wait"},
			{Name: "authorized", Description: "Manage authorized users and organizations"},
			{Name: "logout", Description: "Log out of your Meteor developer account"},
			{Name: "whoami", Description: "Prints the username of the currently logged-in Meteor developer"},
			{Name: "package", Description: "Package name"},
			{Name: "test", Description: "Runs tests against the application"},
			{Name: "admin", Description: "Rarely used commands for administering official Meteor services"},
			{Name: "maintainers", Description: "Manage users and organizations that are maintainers for a particular package"},
			{Name: "recommend-release", Description: "Recommend a version of a meteor release"},
			{Name: "change-homepage", Description: "Change the homepage containing package information"},
			{Name: "list-organizations", Description: "List the organizations of which you are a member"},
			{Name: "members", Description: "Manage members of an organization"},
			{Name: "publish-for-arch", Description: "Publish a package for the same architecture that you are currently on"},
		},
		Options: []spec.Option{
			{Name: "--port", Description: "Port to listen on (instead of the default 3000)"},
			{Name: "--inspect", Description: "Simulate production mode. Minify and bundle CSS and JS files"},
			{Name: "--raw-logs", Description: "Run without parsing logs from stdout and stderr"},
			{Name: "--settings", Description: "Set optional data for Meteor.settings on the server"},
			{Name: "--release", Description: "Specify the release of Meteor to use"},
			{Name: "--verbose", Description: "Print all output from builds logs"},
			{Name: "--no-lint", Description: "Don't run linters used by the app on every rebuild"},
			{Name: "--no-release-check", Description: "Don't run the release updater to check for new releases"},
			{Name: "--allow-incompatible-update", Description: "Specify the release of Meteor to use"},
			{Name: "--package", Description: "Create a new meteor package instead of an app"},
			{Name: "--example", Description: "Example template to use"},
			{Name: "--list", Description: "Show list of available examples"},
			{Name: "--bare", Description: "Create an empty app"},
			{Name: "--minimal", Description: "Create an app with as few Meteor packages as possible"},
			{Name: "--full", Description: "Create a fully scaffolded app"},
			{Name: "--react", Description: "Create a basic react-based app, same as default"},
			{Name: "--vue", Description: "Create a basic vue-based app"},
			{Name: "--apollo", Description: "Create a basic apollo-based app"},
			{Name: "--svelte", Description: "Create a basic svelte-based app"},
			{Name: "--typescript", Description: "Create a basic Typescript React-based app"},
			{Name: "--blaze", Description: "Create a basic blaze-based app"},
			{Name: "--tailwind", Description: "Create a basic react-based app, with tailwind configured"},
			{Name: "--packages-only", Description: "Update the package versions only. Do not update the release"},
			{Name: "--patch", Description: "Update the release to a patch release only"},
			{Name: "--tree", Description: "Outputs a tree showing how packages are referenced"},
			{Name: "--json", Description: "Outputs the tree in JSON format"},
			{Name: "--weak", Description: "Show weakly referenced dependencies in the tree"},
			{Name: "--details", Description: "Adds more package details to the JSON output"},
			{Name: "--debug", Description: "Build in debug mode (don't minify, etc)"},
			{Name: "--directory", Description: "Skip building mobile apps even if mobile platforms have been added"},
			{Name: "--mobile-settings", Description: "Builds only the specified platforms (when available)"},
			{Name: "--packageType", Description: "Choose between apk/bundle for android builds"},
			{Name: "--delete", Description: "Permanently delete this deployment"},
			{Name: "--no-wait", Description: "Reuses the build already created if the git commit hash is the same"},
			{Name: "--free", Description: "Change your app's container size using the deploy command"},
			{Name: "--add", Description: "Add an authorized user or organization"},
			{Name: "--remove", Description: "Remove an authorized user or organization"},
			{Name: "--transfer", Description: "Transfer the (Galaxy) app to a new user or organization"},
			{Name: "--email", Description: "Add an authorized user or organization"},
			{Name: "--ios", Description: "Print all output from builds logs"},
		},
	})
}
