package js

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "nx",
		Description: "All projects",
		Subcommands: []core.Subcommand{
			{Name: "init", Description: "Adds nx.json file and installs nx if not installed already"},
			{Name: "daemon", Description: "Prints information about the Nx Daemon process or starts a daemon process"},
			{Name: "graph", Description: "Graph dependencies within workspace"},
			{Name: "run-many", Description: "Run target for multiple listed projects"},
			{Name: "affected", Description: "Run target for affected projects"},
			{Name: "affected:graph", Description: "Graph dependencies affected by changes"},
			{Name: "print-affected", Description: "Prints information about the projects and targets affected by changes"},
			{Name: "format:check", Description: "Check for un-formatted files"},
			{Name: "format:write", Description: "Overwrite un-formatted files"},
			{Name: "migrate", Description: "Creates a migrations file or runs migrations from the migrations file"},
			{Name: "packageAndVersion", Description: "The target package and version (e.g, @nrwl/workspace@13.0.0)"},
			{Name: "report", Description: "Reports useful version numbers to copy into the Nx issue template"},
			{Name: "plugin", Description: "The name of an installed plugin to query"},
			{Name: "workspace-generator", Description: "Runs a workspace generator from the tools/generators directory"},
			{Name: "name", Description: "The name of your generator"},
			{Name: "connect", Description: "Connect workspace to Nx Cloud"},
			{Name: "repair", Description: "Repair any configuration that is no longer supported by Nx"},
			{Name: "exec", Description: "Executes any command as if it was a target on the project"},
			{Name: "watch", Description: "Watch for changes within projects, and execute commands"},
			{Name: "show", Description: "Show information about the workspace (e.g., list of projects)"},
			{Name: "object", Description: "What to show (e.g., projects)"},
		},
		Options: []core.Option{
			{Name: "--all", Description: "All projects"},
			{Name: "--base", Description: "Base of the current branch (usually main)"},
			{Name: "--commitPrefix", Description: "Automatically create a git commit after each migration runs"},
			{Name: "--defaults", Description: "When true, disables interactive input prompts for options with a default"},
			{Name: "--dryRun", Description: "When true, preview the changes without updating files"},
			{Name: "--exclude", Description: "Exclude certain projects from being processed"},
			{Name: "--excludeAppliedMigrations", Description: "Output file (e.g. --file=output.json or --file=dep-graph.html)"},
			{Name: "--files", Description: "When true, forces overwriting of existing files"},
			{Name: "--from", Description: "Show the task graph of the command"},
			{Name: "--groupByFolder", Description: "Group projects by folder in the project graph"},
			{Name: "--head", Description: "Latest commit of the current branch (usually HEAD)"},
			{Name: "--help", Description: "Show help"},
			{Name: "--host", Description: "Bind the project graph server to a specific ip address"},
			{Name: "--ifExists", Description: "Run migrations only if the migrations file exists, if not continues successfully"},
			{Name: "--includeDependentProjects", Description: "When watching selected projects, include dependent projects as well"},
			{Name: "--interactive", Description: "Enable/disable prompts"},
			{Name: "--libs-and-apps", Description: "Format only libraries and applications files"},
			{Name: "--list-generators", Description: "List the available workspace-generators"},
			{Name: "--nx-bail", Description: "Stop command execution after the first failed task"},
			{Name: "--nx-ignore-cycles", Description: "Ignore cycles in the task graph"},
			{Name: "--open", Description: "Open the project graph in the browser"},
			{Name: "--output-style", Description: "Defines how Nx emits outputs tasks logs"},
			{Name: "--parallel", Description: "Max number of parallel processes [default is 3]"},
			{Name: "--port", Description: "Bind the project graph server to a specific port"},
			{Name: "--project", Description: "Target project"},
			{Name: "--projects", Description: "Projects (comma/space delimited)"},
			{Name: "--runMigrations", Description: "This is the name of the tasks runner configured in nx.json"},
			{Name: "--select", Description: "Select the subset of the returned json document (e.g., --select=projects)"},
			{Name: "--skip-nx-cache", Description: "Rerun the tasks even when the results are available in the cache"},
			{Name: "--start", Description: "Targets (comma/space delimited)"},
			{Name: "--to", Description: "Select the type of projects to be returned (e.g., --type=app)"},
			{Name: "--uncommitted", Description: "Uncommitted changes"},
			{Name: "--untracked", Description: "Untracked changes"},
			{Name: "--verbose", Description: "Prints additional information about the commands (e.g., stack traces)"},
			{Name: "--version", Description: "Show version number"},
			{Name: "--view", Description: "Choose whether to view the projects or task graph"},
			{Name: "--watch", Description: "Watch for changes to project graph and update in-browser"},
		},
	})
}
