package js

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "remotion",
		Description: "Create videos programmatically in React",
		Subcommands: []spec.Subcommand{
			{Name: "versions", Description: "Prints and validates versions of all Remotion packages"},
			{Name: "gpu", Description: "Prints information about how Chrome uses the GPU"},
			{Name: "compositions", Description: "Prints the list of available compositions"},
			{Name: "entry", Description: "The entry point of your Remotion app"},
			{Name: "lambda", Description: "Access functionality of @remotion/lambda"},
			{Name: "policies", Description: "Manage AWS policies"},
			{Name: "role", Description: "Print policy to be added to the AWS role"},
			{Name: "user", Description: "Print policy to be added to the AWS user"},
			{Name: "validate", Description: "Validate the user policy was configured correctly"},
			{Name: "quotas", Description: "Show current AWS quota"},
			{Name: "us-east-1", Description: "North Virginia"},
			{Name: "us-east-2", Description: "Ohio"},
			{Name: "eu-central-1", Description: "Frankfurt"},
			{Name: "eu-west-1", Description: "Ireland"},
			{Name: "eu-west-2", Description: "London"},
			{Name: "us-west-2", Description: "Oregon"},
			{Name: "ap-south-1", Description: "Mumbai"},
			{Name: "ap-southeast-1", Description: "Singapore"},
			{Name: "ap-southeast-2", Description: "Sydney"},
			{Name: "ap-northeast-1", Description: "Tokyo"},
			{Name: "increase", Description: "Send a request to AWS to increase concurrency quotas"},
			{Name: "regions", Description: "Prints list of supported regions"},
			{Name: "render", Description: "Render media on Lambda"},
			{Name: "serve-url", Description: "URL or name of the site"},
			{Name: "composition-id", Description: "Name of the composition"},
			{Name: "out-name", Description: "Where the output should be downloaded. No download it omitted"},
			{Name: "still", Description: "Render a still on Lambda"},
			{Name: "functions", Description: "Manage functions on AWS Lambda"},
			{Name: "ls", Description: "List deployed functions"},
			{Name: "deploy", Description: "Deploy a function if one with the same parameters doesn't exist"},
			{Name: "rmall", Description: "Remove all functions in a region"},
			{Name: "rm", Description: "Remove a function"},
			{Name: "function-name", Description: "ID of your function"},
			{Name: "site-name", Description: "ID of your site"},
			{Name: "create", Description: "Create or update a site"},
			{Name: "comp-id", Description: "The composition ID"},
			{Name: "polling-interval", Description: "Polling interval in milliseconds"},
			{Name: "upgrade", Description: "Upgrade all Remotion-related dependencies to the newest version"},
			{Name: "benchmark", Description: "Try different render configurations and compare them"},
			{Name: "install", Description: "Ensure Remotion dependencies"},
		},
		Options: []spec.Option{
			{Name: "--props", Description: "Pass input props as filename or as JSON"},
			{Name: "--env-file", Description: "Specify a location for a dotenv file"},
			{Name: "--disable-headless", Description: "Run Chrome in normal mode rather than headless"},
			{Name: "--gl", Description: "Which OpenGL renderer to use"},
			{Name: "--user-agent", Description: "User agent to use for Chrome during rendering"},
			{Name: "--ignore-certificate-errors", Description: "Ignore SSL errors"},
			{Name: "--disable-web-security", Description: "Disable CORS and other web security features"},
			{Name: "--quiet", Description: "Print less output"},
			{Name: "-q", Description: "Print less output"},
			{Name: "--log", Description: "Custom location for a Remotion config file"},
			{Name: "--yes", Description: "Skip confirmation"},
			{Name: "--force", Description: "Skip confirmation"},
			{Name: "-y", Description: "Skip confirmation"},
			{Name: "-f", Description: "Skip confirmation"},
			{Name: "--region", Description: "The AWS region specifier"},
			{Name: "--default-only", Description: "Only print the regions enabled by default in a new AWS account"},
			{Name: "--max-retries", Description: "How many times a chunk can be retried before the render times out"},
			{Name: "--privacy", Description: "How many frames should be rendered per chunk"},
			{Name: "--concurrency-per-lambda", Description: "Concurrency with which each Lambda function should render"},
			{Name: "--overwrite", Description: "Overwrite a video if it already exists in the S3 bucket"},
			{Name: "--function-name", Description: "Name of the function that should be invoked"},
			{Name: "--renderer-function-name", Description: "The time in millisecond that a delayRender() may take before it times out"},
			{Name: "--quality", Description: "Quality for rendered frames, JPEG only, 0-100"},
			{Name: "--scale", Description: "Upscale or downscale or the dimensions of the video"},
			{Name: "--codec", Description: "Video or audio codec"},
			{Name: "--audio-codec", Description: "Codec to be used for the audio"},
			{Name: "--every-nth-frame", Description: "Render only every nth frame (only for GIFs)"},
			{Name: "--number-of-gif-loops", Description: "How many times a GIF should loop. 0 = No loop"},
			{Name: "--audio-bitrate", Description: "Customize the output audio bitrate"},
			{Name: "--video-bitrate", Description: "Customize the output video bitrate. Mutually exclusive with --crf"},
			{Name: "--crf", Description: "FFMPEG CRF value, controls quality, see docs for info"},
			{Name: "--frames", Description: "Render a portion or a still of a video, 0-9, 50"},
			{Name: "--prores-profile", Description: "ProRes profile, need --codec=prores to be set"},
			{Name: "--x264-preset", Description: "Custom pixel format, see docs for available values"},
			{Name: "--muted", Description: "Outputs no audio"},
			{Name: "--height", Description: "Override the composition height"},
			{Name: "--width", Description: "Override the composition width"},
			{Name: "--frame", Description: "Which frame to render (default 0)"},
			{Name: "--memory", Description: "Amount of memory in MB to allocate"},
			{Name: "--disk", Description: "Amount of disk space in MB to allocate"},
		},
	})
}
