package ops

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "eas",
		Description: "Log in with your Expo account",
		Subcommands: []core.Subcommand{
			{Name: "account:login", Description: "Log in with your Expo account"},
			{Name: "account:logout", Description: "Log out"},
			{Name: "account:view", Description: "Show the username you are logged in as"},
			{Name: "analytics", Description: "Display or change analytics settings"},
			{Name: "autocomplete", Description: "Display autocomplete installation instructions"},
			{Name: "Shell", Description: "Select the shell you'd like to display autocomplete information for"},
			{Name: "branch:create", Description: "Create a branch"},
			{Name: "Name", Description: "Name of the branch to create"},
			{Name: "branch:delete", Description: "Delete a branch"},
			{Name: "branch:list", Description: "List all branches"},
			{Name: "branch:rename", Description: "Rename a branch"},
			{Name: "branch:view", Description: "View a branch"},
			{Name: "build", Description: "Start a build"},
			{Name: "build:cancel", Description: "Cancel a build"},
			{Name: "build:configure", Description: "Configure the project to support EAS build"},
			{Name: "build:list", Description: "List all builds for your project"},
			{Name: "build:submit", Description: "Submit app binary to App Store and/or Play Store"},
			{Name: "build:version:set", Description: "Update version of an app"},
			{Name: "build:version:sync", Description: "Update a version in native code with a value stored on EAS servers"},
			{Name: "build:view", Description: "View a build for your project"},
			{Name: "channel:create", Description: "Create a channel"},
			{Name: "channel:edit", Description: "Point a channel at a new branch"},
			{Name: "channel:list", Description: "List all channels"},
			{Name: "channel:view", Description: "View a channel"},
			{Name: "config", Description: "Display project configuration (app.json + eas.json)"},
			{Name: "credentials", Description: "Manage credentials"},
			{Name: "device:create", Description: "Register new Apple devices to use for internal distribution"},
			{Name: "device:delete", Description: "Remove a registered device from your account"},
			{Name: "device:list", Description: "List all registered devices for your account"},
			{Name: "device:view", Description: "View a device for your project"},
			{Name: "diagnostics", Description: "Display environment info"},
			{Name: "help", Description: "Display help for eas-cli"},
			{Name: "Command", Description: "Command to show help for"},
			{Name: "metadata:pull", Description: "Generate the local store configuration from the app stores"},
			{Name: "metadata:push", Description: "Sync the local store configuration to the app stores"},
			{Name: "open", Description: "Open the project page in a web browser"},
			{Name: "project:info", Description: "Information about the current project"},
			{Name: "project:init", Description: "Create or link an EAS project"},
			{Name: "secret:create", Description: "Create an environment secret on the current project or owner account"},
			{Name: "secret:delete", Description: "Delete an environment secret by ID"},
			{Name: "secret:list", Description: "List environment secrets available for your current app"},
			{Name: "update", Description: "Publish an update group"},
			{Name: "update:configure", Description: "Configure the project to support EAS update"},
			{Name: "update:delete", Description: "Delete all the updates in an update group"},
			{Name: "Group ID", Description: "The ID of an update group to delete"},
			{Name: "update:list", Description: "View the recent updates"},
			{Name: "update:view", Description: "Update group details"},
			{Name: "webhook:create", Description: "Create a webhook"},
			{Name: "webhook:delete", Description: "Delete a webhook"},
			{Name: "ID", Description: "ID of the webhook to delete"},
		},
		Options: []core.Option{
			{Name: "-r", Description: "Refresh cache (ignores displaying instructions)"},
			{Name: "--json", Description: "Enable JSON output, non-JSON messages will be printed to stderr"},
			{Name: "--non-interactive", Description: "Run the command in non-interactive mode"},
			{Name: "--limit", Description: "The number of items to fetch each query. Defaults to 50 and is capped at 100"},
			{Name: "--offset", Description: "Start queries from specified index. Use for paginating results. Defaults to 0"},
			{Name: "--from", Description: "Current name of the branch"},
			{Name: "--to", Description: "New name of the branch"},
			{Name: "-e", Description: "A short message describing the build"},
			{Name: "-p", Description: "Submit on build complete using the submit profile with provided name"},
			{Name: "--clear-cache", Description: "Clear cache before the build"},
			{Name: "--local", Description: "Run build locally [experimental]"},
			{Name: "--output", Description: "Output path for local build"},
			{Name: "--no-wait", Description: "Don't wait for build(s) to complete"},
			{Name: "--wait", Description: "Wait for build(s) to complete"},
			{Name: "-s", Description: "Delete OUTPUT_DIRECTORY if it already exists"},
			{Name: "--appBuildVersion", Description: "Enable JSON output, non-JSON messages will be printed to stderr"},
			{Name: "--platform", Description: "Submit app binary to App Store and/or Play Store"},
			{Name: "--latest", Description: "Submit the latest build for specified platform"},
			{Name: "--path", Description: "Path to the .apk/.aab/.ipa file"},
			{Name: "--url", Description: "App archive url"},
			{Name: "--verbose", Description: "Always print logs from Submission Service"},
			{Name: "--branch", Description: "Name of the branch to point to"},
			{Name: "--apple-team-id", Description: "The Apple team ID on which to find the device"},
			{Name: "--udid", Description: "The Apple device ID to disable"},
			{Name: "-n", Description: "Include all nested commands in the output"},
			{Name: "--force", Description: "Whether to overwrite any existing project ID"},
			{Name: "--id", Description: "ID of the EAS project to link"},
			{Name: "--name", Description: "Name of the secret"},
			{Name: "--scope", Description: "[default: project] Scope for the secret"},
			{Name: "--type", Description: "The type of secret"},
			{Name: "--value", Description: "Text value or path to a file to store in the secret"},
			{Name: "--auto", Description: "Branch to publish the update group on"},
			{Name: "--group", Description: "Update group to republish"},
			{Name: "--input-dir", Description: "[default: dist] Location of the bundle"},
			{Name: "--message", Description: "A short message describing the update"},
			{Name: "--private-key-path", Description: "Republish an update group"},
			{Name: "--skip-bundler", Description: "Skip running Expo CLI to bundle the app before publishing"},
			{Name: "--all", Description: "List updates on all branches"},
			{Name: "--event", Description: "Event type that triggers the webhook"},
			{Name: "--secret", Description: "Webhook URL"},
		},
	})
}
