package ops

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "gcloud",
		Description: "Manage Google Cloud Platform resources and developer workflow",
		Subcommands: []core.Subcommand{
			{Name: "access-context-manager", Description: "Manage Access Context Manager resources"},
			{Name: "active-directory", Description: "Manage Managed Microsoft AD resources"},
			{Name: "ai-platform", Description: "Manage AI Platform jobs and models"},
			{Name: "alpha", Description: "*(ALPHA)*  Alpha versions of gcloud commands"},
			{Name: "anthos", Description: "Anthos command Group"},
			{Name: "apigee", Description: "Manage Apigee resources"},
			{Name: "app", Description: "Manage your App Engine deployments"},
			{Name: "artifacts", Description: "Manage Artifact Registry resources"},
			{Name: "asset", Description: "Manage the Cloud Asset Inventory"},
			{Name: "auth", Description: "Manage oauth2 credentials for the Google Cloud SDK"},
			{Name: "beta", Description: "*(BETA)*  Beta versions of gcloud commands"},
			{Name: "bigtable", Description: "Manage your Cloud Bigtable storage"},
			{Name: "builds", Description: "Create and manage builds for Google Cloud Build"},
			{Name: "cheat-sheet", Description: "Display gcloud cheat sheet"},
			{Name: "cloud-shell", Description: "Manage Google Cloud Shell"},
			{Name: "components", Description: "List, install, update, or remove Google Cloud SDK components"},
			{Name: "composer", Description: "Create and manage Cloud Composer Environments"},
			{Name: "compute", Description: "Create and manipulate Compute Engine resources"},
			{Name: "config", Description: "View and edit Cloud SDK properties"},
			{Name: "container", Description: "Deploy and manage clusters of machines for running containers"},
			{Name: "data-catalog", Description: "Manage Cloud Data Catalog resources"},
			{Name: "dataflow", Description: "Manage Google Cloud Dataflow resources"},
			{Name: "dataproc", Description: "Create and manage Google Cloud Dataproc clusters and jobs"},
			{Name: "datastore", Description: "Manage your Cloud Datastore resources"},
			{Name: "debug", Description: "Commands for interacting with the Cloud Debugger"},
			{Name: "deployment-manager", Description: "Manage deployments of cloud resources"},
			{Name: "dns", Description: "Manage your Cloud DNS managed-zones and record-sets"},
			{Name: "docker", Description: "*(DEPRECATED)*  Enable Docker CLI access to Google Container Registry"},
			{Name: "domains", Description: "Manage domains for your Google Cloud projects"},
			{Name: "endpoints", Description: "Create, enable and manage API services"},
			{Name: "feedback", Description: "Provide feedback to the Google Cloud SDK team"},
			{Name: "filestore", Description: "Create and manipulate Cloud Filestore resources"},
			{Name: "firebase", Description: "Work with Google Firebase"},
			{Name: "firestore", Description: "Manage your Cloud Firestore resources"},
			{Name: "functions", Description: "Manage Google Cloud Functions"},
			{Name: "game", Description: "Managed Cloud Game Services"},
			{Name: "healthcare", Description: "Manage Cloud Healthcare resources"},
			{Name: "help", Description: "Search gcloud help text"},
			{Name: "iam", Description: "Manage IAM service accounts and keys"},
			{Name: "iap", Description: "Manage IAP policies"},
			{Name: "identity", Description: "Manage Cloud Identity Groups and Memberships resources"},
			{Name: "info", Description: "Display information about the current gcloud environment"},
			{Name: "init", Description: "Initialize or reinitialize gcloud"},
			{Name: "iot", Description: "Manage Cloud IoT resources"},
			{Name: "kms", Description: "Manage cryptographic keys in the cloud"},
			{Name: "logging", Description: "Manage Cloud Logging"},
			{Name: "meta", Description: "Cloud meta introspection commands"},
			{Name: "ml", Description: "Use Google Cloud machine learning capabilities"},
			{Name: "ml-engine", Description: "Manage AI Platform jobs and models"},
			{Name: "monitoring", Description: "Manage Cloud Monitoring dashboards"},
		},
	})
}
