package runner

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "ant",
		Description: "Execute ${task} task",
		Options: []core.Option{
			{Name: "--help", Description: "Show help for ant"},
			{Name: "--noconfig", Description: "Enable use of jikes by default, unless set explicitly in configuration files"},
			{Name: "--execdebug", Description: "Print ant exec line generated by this launch script"},
			{Name: "-projecthelp", Description: "Print project help information and exit"},
			{Name: "-version", Description: "Print the version information and exit"},
			{Name: "-diagnostics", Description: "Print information that might be helpful to diagnose or report problems and exit"},
			{Name: "-quiet", Description: "Be extra quiet"},
			{Name: "-silent", Description: "Print nothing but task outputs and build failures"},
			{Name: "-verbose", Description: "Be extra verbose"},
			{Name: "-debug", Description: "Print debugging information"},
			{Name: "-emacs", Description: "Produce logging information without adornments"},
			{Name: "-lib", Description: "Specifies a path to search for jars and classes"},
			{Name: "-logfile", Description: "Use given file for log"},
			{Name: "-logger", Description: "The class which is to perform logging"},
			{Name: "-listener", Description: "Add an instance of class as a project listener"},
			{Name: "-noinput", Description: "Do not allow interactive input"},
			{Name: "-buildfile", Description: "Use given buildfile"},
			{Name: "-keep-going", Description: "Execute all targets that do not depend on failed target(s)"},
			{Name: "-propertyfile", Description: "Load all properties from file with -D properties taking precedence"},
			{Name: "-inputhandler", Description: "The class which will handle input requests"},
			{Name: "-find", Description: "Search for buildfile towards the root of the filesystem and use it"},
			{Name: "-nice", Description: "A niceness value for the main thread"},
			{Name: "-nouserlib", Description: "Run ant without using the jar files from ${user.home}/.ant/lib"},
			{Name: "-noclasspath", Description: "Run ant without using CLASSPATH"},
			{Name: "-autoproxy", Description: "Java1.5+: use the OS proxy settings"},
			{Name: "-main", Description: "Override Ant's normal entry point"},
		},
	})
}
