package runner

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "symfony",
		Description: "Symfony Binary",
		Subcommands: []core.Subcommand{
			{Name: "cloud:clear-cache", Description: "Clear the CLI cache"},
			{Name: "cloud:docs", Description: "Open the online documentation"},
			{Name: "cloud:multi", Description: "Execute a command on multiple projects"},
			{Name: "cloud:web", Description: "Open the Web UI"},
			{Name: "cloud:activity:cancel", Description: "Cancel an activity"},
			{Name: "cloud:activity:get", Description: "View detailed information on a single activity"},
			{Name: "cloud:activity:list", Description: "Get a list of activities for an environment or project"},
			{Name: "cloud:activity:log", Description: "Display the log for an activity"},
			{Name: "cloud:app:config-get", Description: "View the configuration of an app"},
			{Name: "cloud:app:list", Description: "List apps in the project"},
			{Name: "cloud:auth:api-token-login", Description: "Log in to Platform.sh using an API token"},
			{Name: "cloud:auth:browser-login", Description: "Log in to Platform.sh via a browse"},
			{Name: "cloud:auth:info", Description: "Display your account information"},
			{Name: "cloud:auth:logout", Description: "Log out of Platform.sh"},
			{Name: "cloud:backup:create", Description: "Make a backup of an environment"},
			{Name: "cloud:backup:list", Description: "List available backups of an environment"},
			{Name: "cloud:backup:restore", Description: "Restore an environment backup"},
			{Name: "cloud:certificate:add", Description: "Add an SSL certificate to the project"},
			{Name: "cloud:certificate:delete", Description: "Delete a certificate from the project"},
			{Name: "cloud:certificate:get", Description: "View a certificate"},
			{Name: "cloud:certificate:list", Description: "List project certificates"},
			{Name: "cloud:commit:get", Description: "Show commit details"},
			{Name: "cloud:commit:list", Description: "List commits"},
			{Name: "cloud:db:dump", Description: "Create a local dump of the remote database"},
			{Name: "cloud:db:size", Description: "Estimate the disk usage of a database"},
			{Name: "cloud:db:sql", Description: "Run SQL on the remote database"},
			{Name: "cloud:domain:add", Description: "Add a new domain to the project"},
			{Name: "cloud:domain:delete", Description: "Delete a domain from the project"},
			{Name: "cloud:domain:get", Description: "Show detailed information for a domain"},
			{Name: "cloud:domain:list", Description: "Get a list of all domains"},
			{Name: "cloud:domain:update", Description: "Update a domain"},
			{Name: "coud:environment:activate", Description: "Activate an environment"},
			{Name: "cloud:environment:branch", Description: "Branch an environment"},
			{Name: "cloud:environment:checkout", Description: "Check out an environment"},
			{Name: "cloud:environment:debug", Description: "Debug an environment by switching Symfony to the debug mode temporarily"},
			{Name: "cloud:environment:delete", Description: "Delete one or more environments"},
			{Name: "cloud:environment:http-access", Description: "Update HTTP access settings for an environment"},
			{Name: "cloud:environment:info", Description: "Read or set properties for an environment"},
			{Name: "cloud:environment:init", Description: "Initialize an environment from a public Git repository"},
			{Name: "cloud:environment:list", Description: "Get a list of environments"},
			{Name: "cloud:environment:logs", Description: "Read an environment's logs"},
			{Name: "cloud:environment:merge", Description: "Merge an environment"},
			{Name: "cloud:environment:push", Description: "Push code to an environment"},
			{Name: "cloud:environment:redeploy", Description: "Redeploy an environment"},
			{Name: "cloud:environment:relationships", Description: "Show an environment's relationships"},
			{Name: "cloud:environment:scp", Description: "Copy files to and from current environment using scp"},
			{Name: "cloud:environment:ssh", Description: "SSH to the current environment"},
			{Name: "cloud:environment:synchronize", Description: "Synchronize an environment's code and/or data from its parent"},
			{Name: "cloud:environment:url", Description: "Get the public URLs of an environment"},
			{Name: "cloud:environment:xdebug", Description: "Open a tunnel to Xdebug on the environment"},
		},
		Options: []core.Option{
			{Name: "-h", Description: "Show help"},
			{Name: "-q", Description: "Do not output any message"},
			{Name: "--no-ansi", Description: "Disable ANSI output"},
			{Name: "--ansi", Description: "Force ANSI output"},
			{Name: "--no-interaction", Description: "Do not ask any interactive question"},
			{Name: "-v", Description: "Print the version"},
		},
	})
}
