package runner

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "valet",
		Description: "Do not output any message",
		Subcommands: []core.Subcommand{
			{Name: "diagnose", Description: "Output diagnostics to aid in debugging Valet"},
			{Name: "fetch-share-url", Description: "Get the URL to the current share tunnel (for Expose or ngrok)"},
			{Name: "forget", Description: "Remove the current working (or specified) directory from Valet's list of paths"},
			{Name: "help", Description: "Display help for a command"},
			{Name: "install", Description: "Install the Valet services"},
			{Name: "link", Description: "Link the current working directory to Valet"},
			{Name: "links", Description: "Display all of the registered Valet links"},
			{Name: "list", Description: "List commands"},
			{Name: "log", Description: "Tail log file"},
			{Name: "loopback", Description: "Get or set the loopback address used for Valet sites"},
			{Name: "on-latest-version", Description: "Determine if this is the latest version of Valet"},
			{Name: "open", Description: "Open the site for the current (or specified) directory in your browser"},
			{Name: "park", Description: "Register the current working (or specified) directory with Valet"},
			{Name: "parked", Description: "Display all the current sites within parked paths"},
			{Name: "paths", Description: "Get all of the paths registered with Valet"},
			{Name: "proxies", Description: "Display all of the proxy sites"},
			{Name: "restart", Description: "Restart the Valet services"},
			{Name: "secure", Description: "Secure the given domain with a trusted TLS certificate"},
			{Name: "share", Description: "Generate a publicly accessible URL for your project"},
			{Name: "start", Description: "Start the Valet services"},
			{Name: "stop", Description: "Stop the Valet services"},
			{Name: "tld", Description: "Get or set the TLD used for Valet sites"},
			{Name: "uninstall", Description: "Uninstall the Valet services"},
			{Name: "unlink", Description: "Remove the specified Valet link"},
			{Name: "unproxy", Description: "Delete an Nginx proxy config"},
			{Name: "unsecure", Description: "Stop serving the given domain over HTTPS and remove the trusted TLS certificate"},
			{Name: "use", Description: "Change the version of PHP used by valet"},
			{Name: "which", Description: "Determine which Valet driver serves the current working directory"},
			{Name: "isolate", Description: "Change the version of PHP used by Valet to serve the current working directory"},
			{Name: "isolated", Description: "List all sites using isolated versions of PHP"},
			{Name: "which-php", Description: "Get the PHP executable path for a site"},
			{Name: "completion", Description: "Dump the shell completion script"},
			{Name: "secured", Description: "Display all of the currently secured sites"},
			{Name: "set-ngrok-token", Description: "Set the Ngrok auth token"},
			{Name: "share-tool", Description: "Get the name of the current share tool (Expose or ngrok)"},
			{Name: "status", Description: "Output the status of Valet and its installed services and config"},
		},
		Options: []core.Option{
			{Name: "-h", Description: "Do not output any message"},
			{Name: "-V", Description: "Display this application version"},
			{Name: "--ansi", Description: "Force (or disable --no-ansi) ANSI output"},
			{Name: "--no-ansi", Description: "Force (or disable --no-ansi) ANSI output"},
			{Name: "-n", Description: "Do not ask any interactive question"},
			{Name: "-v", Description: "Normal output"},
			{Name: "--secure", Description: "Valet is a Laravel development environment for macOS minimalists"},
			{Name: "-p", Description: "Print diagnostics output while running"},
			{Name: "--plain", Description: "Format clipboard output as plain text"},
			{Name: "--format", Description: "The output format (txt, xml, json, or md) [default: 'txt']"},
			{Name: "--raw", Description: "To output raw command help"},
			{Name: "--isolate", Description: "Display all of the registered Valet links"},
			{Name: "--short", Description: "To skip describing commands' arguments"},
			{Name: "-l", Description: "Get or set the loopback address used for Valet sites"},
			{Name: "--auth", Description: "Enforce basic auth on tunnel endpoint, 'user:password'"},
			{Name: "--authtoken", Description: "Ngrok.com authtoken identifying a user"},
			{Name: "--bind-tls", Description: "Listen for http, https or both: true/false/both"},
			{Name: "--config", Description: "Path to config files; they are merged if multiple"},
			{Name: "--host-header", Description: "Set Host header; if 'rewrite' use local address hostname"},
			{Name: "--hostname", Description: "Host tunnel on custom hostname (requires DNS CNAME)"},
			{Name: "--inspect", Description: "Enable/disable http introspection"},
			{Name: "--log", Description: "Path to log file, 'stdout', 'stderr' or 'false'"},
			{Name: "--log-format", Description: "Log record format: 'term', 'logfmt', 'json'"},
			{Name: "--log-level", Description: "Logging level"},
			{Name: "--region", Description: "Ngrok server region [us, eu, au, ap, sa, jp, in] (default: us)"},
			{Name: "--subdomain", Description: "Host tunnel on a custom subdomain"},
			{Name: "--off", Description: "Remove the sudoers files so normal sudo password prompts are required"},
			{Name: "--force", Description: "Do a forceful uninstall of Valet and related Homebrew pkgs"},
			{Name: "--site", Description: "Name of the website you want to isolate"},
			{Name: "--debug", Description: "Tail the completion debug log"},
		},
	})
}
