package rust

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "rustup",
		Description: "The Rust toolchain installer",
		Subcommands: []spec.Subcommand{
			{Name: "show", Description: "Show the active and installed toolchains or profiles"},
			{Name: "active-toolchain", Description: "Show the active toolchain"},
			{Name: "home", Description: "Display the computed value of RUSTUP_HOME"},
			{Name: "profile", Description: "Show the current profile"},
			{Name: "keys", Description: "Display the known PGP keys"},
			{Name: "help", Description: "Prints this message or the help of the given subcommand(s)"},
			{Name: "update", Description: "Update Rust toolchains and rustup"},
			{Name: "toolchain", Description: "Toolchain name. For more information see `rustup help toolchain`"},
			{Name: "check", Description: "Check for updates to Rust toolchains and rustup"},
			{Name: "target", Description: "Modify a toolchain's supported targets"},
			{Name: "list", Description: "List installed and available targets"},
			{Name: "add", Description: "Add a target to a Rust toolchain"},
			{Name: "remove", Description: "Remove a target from a Rust toolchain"},
			{Name: "install", Description: "Install or update a given toolchain"},
			{Name: "path", Description: "Path to the directory"},
			{Name: "component", Description: "Modify a toolchain's installed components"},
			{Name: "override", Description: "Modify directory toolchain overrides"},
			{Name: "set", Description: "Set the override toolchain for a directory"},
			{Name: "run", Description: "Run a command with an environment configured for a given toolchain"},
			{Name: "which", Description: "Display which binary will be run for a given command"},
			{Name: "doc", Description: "Open the documentation for the current toolchain"},
			{Name: "man", Description: "View the man page for a given command"},
			{Name: "self", Description: "Modify the rustup installation"},
			{Name: "uninstall", Description: "Uninstall rustup"},
			{Name: "upgrade-data", Description: "Upgrade the internal data format"},
			{Name: "auto-self-update", Description: "The rustup auto self update mode"},
			{Name: "completions", Description: "Generate tab-completion scripts for your shell"},
		},
		Options: []spec.Option{
			{Name: "-h", Description: "Prints help information"},
			{Name: "--force", Description: "Force an update, even if some components are missing"},
			{Name: "--force-non-host", Description: "Prints help information"},
			{Name: "--no-self-update", Description: "Don't perform self update when running the `rustup update` command"},
			{Name: "-V", Description: "Prints version information"},
			{Name: "--toolchain", Description: "Toolchain name"},
			{Name: "-t", Description: "Add specific targets on installation"},
			{Name: "-c", Description: "Add specific components on installation"},
			{Name: "--profile", Description: "Allow rustup to downgrade the toolchain to satisfy your component choice"},
			{Name: "--install", Description: "Install the requested toolchain if needed"},
			{Name: "--alloc", Description: "The Rust core allocation and collections library"},
			{Name: "--book", Description: "The Rust Programming Language book"},
			{Name: "--cargo", Description: "The Cargo Book"},
			{Name: "--core", Description: "The Rust Core Library"},
			{Name: "--edition-guide", Description: "The Rust Edition Guide"},
			{Name: "--embedded-book", Description: "The Embedded Rust Book"},
			{Name: "--nomicon", Description: "The Dark Arts of Advanced and Unsafe Rust Programming"},
			{Name: "--path", Description: "Only print the path to the documentation"},
			{Name: "--proc_macro", Description: "A support library for macro authors when defining new macros"},
			{Name: "--reference", Description: "The Rust Reference"},
			{Name: "--rust-by-example", Description: "The compiler for the Rust programming language"},
			{Name: "--rustdoc", Description: "Generate documentation for Rust projects"},
			{Name: "--std", Description: "Standard library API documentation"},
			{Name: "--test", Description: "Support code for rustc's built in unit-test and micro-benchmarking framework"},
			{Name: "--unstable-book", Description: "--unstable-book"},
			{Name: "-q", Description: "Disable progress output"},
			{Name: "-v", Description: "Enable verbose output"},
		},
	})
}
