border = "#8839ef"
accent = "#179299"
muted = "#9ca0b0"
text = "#4c4f69"
text_sel = "#4c4f69"
key = "#8839ef"
match = "#40a02b"
desc = "#6c6f85"
desc_sel = "#4c4f69"
sel_bg = "#acb0be"
sel_text = "#eff1f5"
scroll_info = "#8839ef"
ghost_text = "#acb0be"
sys = "#ccd0da"
sys_sel = "#fe640b"
hist = "#e6e9ef"
hist_sel = "#179299"
alias = "#ccd0da"
alias_sel = "#8839ef"
