package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "argo",
		Description: "If True, Use the HTTP client. Defaults to the ARGO_HTTP1 environment variable",
		Subcommands: []spec.Subcommand{
			{Name: "archive", Description: "Manage the workflow archive"},
			{Name: "delete", Description: "Delete a workflow in the archive"},
			{Name: "get", Description: "Get a workflow in the archive"},
			{Name: "list", Description: "List workflows in the archive"},
			{Name: "list-label-keys", Description: "List workflows label keys in the archive"},
			{Name: "list-label-values", Description: "Get workflow label values in the archive"},
			{Name: "resubmit", Description: "Resubmit one or more workflows"},
			{Name: "retry", Description: "Retry zero or more workflows"},
			{Name: "auth", Description: "Manage authentication settings"},
			{Name: "token", Description: "Print the auth token"},
			{Name: "cluster-template", Description: "Manipulate cluster workflow templates"},
			{Name: "create", Description: "Create a cluster workflow template"},
			{Name: "lint", Description: "Validate files or directories of cluster workflow template manifests"},
			{Name: "completion", Description: "Output shell completion code for the specified shell (bash or zsh)"},
			{Name: "cp", Description: "Copy artifacts from workflow"},
			{Name: "cron", Description: "Manage cron workflows"},
			{Name: "resume", Description: "Resume zero or more cron workflows"},
			{Name: "suspend", Description: "Suspend zero or more cron workflows"},
			{Name: "executor-plugin", Description: "Manage executor plugins"},
			{Name: "build", Description: "Build an executor plugin"},
			{Name: "help", Description: "Help about any command"},
			{Name: "logs", Description: "View logs of a pod or workflow"},
			{Name: "node", Description: "Perform action on a node in a workflow"},
			{Name: "server", Description: "Start the Argo Server"},
			{Name: "stop", Description: "Stop zero or more workflows allowing all exit handlers to run"},
			{Name: "submit", Description: "Submit a workflow"},
			{Name: "template", Description: "Manipulate workflow templates"},
			{Name: "terminate", Description: "Terminate zero or more workflows immediately"},
			{Name: "version", Description: "Print version information"},
			{Name: "wait", Description: "Waits for workflows to complete"},
			{Name: "watch", Description: "Watch a workflow until it completes"},
		},
		Options: []spec.Option{
			{Name: "--argo-base-href", Description: "If True, Use the HTTP client. Defaults to the ARGO_HTTP1 environment variable"},
			{Name: "--argo-server", Description: "Username to impersonate for the operation"},
			{Name: "--as-group", Description: "UID to impersonate for the operation"},
			{Name: "--certificate-authorityk", Description: "Path to a cert file for the certificate authority"},
			{Name: "--client-certificate", Description: "Path to a client certificate file for TLS"},
			{Name: "--client-key", Description: "Path to a client key file for TLS"},
			{Name: "--cluster", Description: "The name of the kubeconfig cluster to use"},
			{Name: "--context", Description: "The name of the kubeconfig context to use"},
			{Name: "--gloglevel", Description: "Set the glog logging level"},
			{Name: "--header", Description: "Help for argo"},
			{Name: "--insecure-skip-tls-verify", Description: "Path to a kube config. Only required if out-of-cluster"},
			{Name: "--loglevel", Description: "If present the namespace scope for this CLI request"},
			{Name: "--password", Description: "Password for basic authentication to the API server"},
			{Name: "--proxy-url", Description: "This URL will be used to connect via proxy"},
			{Name: "--request-timeout", Description: "The address and port of the Kubernetes API server"},
			{Name: "--tls-server-name", Description: "Bearer token for authentication to the API server"},
			{Name: "--user", Description: "The name of the kubeconfig user to use"},
			{Name: "--username", Description: "Username for basic authentication to the API server"},
			{Name: "--verbose", Description: "Enabled verbose logging i.e. --loglevel debug"},
			{Name: "--output", Description: "List workflows in the archive"},
			{Name: "--chunk-size", Description: "Return large lists in chunks rather than all at once. Pass 0 to disable"},
			{Name: "--help", Description: "Help for list"},
			{Name: "--selector", Description: "Resubmit one or more workflows"},
			{Name: "--field-selector", Description: "Help for resubmit"},
			{Name: "--log", Description: "Log the workflow until it completes"},
			{Name: "--memoized", Description: "Re-use successful steps & outputs from the previous run"},
			{Name: "--parameter", Description: "Input parameter to override on the original workflow spec"},
			{Name: "--priority", Description: "Workflow priority"},
			{Name: "--node-field-selector", Description: "Output format. One of: name|json|yaml|wide"},
			{Name: "--restart-successful", Description: "Indicates to restart successful nodes matching the --node-field-selector"},
			{Name: "--watch", Description: "Manage authentication settings"},
			{Name: "--strict", Description: "Perform strict workflow validation (default true)"},
			{Name: "--all", Description: "Delete all cluster workflow templates"},
			{Name: "--artifact-name", Description: "Name of output artifact in workflow"},
			{Name: "--node-id", Description: "Id of node in workflow"},
			{Name: "--path", Description: "Name of template in workflow"},
			{Name: "--entrypoint", Description: "Override entrypoint"},
			{Name: "--generate-name", Description: "Override metadata.generateName"},
			{Name: "--labels", Description: "Comma separated labels to apply to the workflow. Will override previous values"},
			{Name: "--name", Description: "Override metadata.name"},
		},
	})
}
