package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "bit",
		Description: "Bit documentation: https://bit.dev/docs",
		Subcommands: []spec.Subcommand{
			{Name: "init", Description: "Create or reinitialize an empty workspace"},
			{Name: "new", Description: "Create a new workspace from a template"},
			{Name: "config", Description: "Global config management"},
			{Name: "set", Description: "Set a global configuration"},
			{Name: "del", Description: "Delete given key from global configuration"},
			{Name: "get", Description: "Get a value from global configuration"},
			{Name: "list", Description: "List all configuration(s)"},
			{Name: "scope-config", Description: "Scope config management"},
			{Name: "login", Description: "Log in to Bit cloud"},
			{Name: "logout", Description: "Log the CLI out of Bit"},
			{Name: "doctor", Description: "Diagnose a bit workspace"},
			{Name: "filePath", Description: "Path to save diagnoses to a file"},
			{Name: "completion", Description: "Enable bash/zsh-completion shortcuts for commands and options"},
			{Name: "cli", Description: "EXPERIMENTAL. Enters bit cli program and generates commands list"},
			{Name: "generate", Description: "Generate an .md file with all commands details"},
			{Name: "help", Description: "Shows help"},
			{Name: "clear-cache", Description: "Clears Bit's cache from current working machine"},
			{Name: "remote", Description: "Manage set of tracked bit scope(s)"},
			{Name: "add", Description: "Add a bare-scope as a remote, usage: remote add <url>"},
			{Name: "remove", Description: "Remove component(s) from the workspace, or a remote scope"},
			{Name: "import", Description: "Import components from their remote scopes to the local workspace"},
			{Name: "pack", Description: "Create tar for npm publish"},
			{Name: "deprecate", Description: "Deprecate a component"},
			{Name: "undeprecate", Description: "Undeprecate a deprecated component (local/remote)"},
			{Name: "rename", Description: "Rename a component"},
			{Name: "export", Description: "Export components from the workspace to remote scopes"},
			{Name: "string", Description: "Resume export using an export-id"},
			{Name: "dependents", Description: "EXPERIMENTAL. Show dependents of the given component"},
			{Name: "show", Description: "Display the component's essential information"},
			{Name: "dependencies", Description: "Manage dependencies"},
			{Name: "deps", Description: "Manage dependencies"},
			{Name: "unset", Description: "Unset a dependency to component(s) that was previously set by 'bit deps set'"},
			{Name: "debug", Description: "Show the immediate dependencies and how their versions were determined"},
			{Name: "reset", Description: "Reset dependencies to the default values (revert any previously 'bit deps set')"},
			{Name: "eject", Description: "Write dependencies that were previously set via 'bit deps set' into .bitmap"},
			{Name: "blame", Description: "EXPERIMENTAL: Find out which snap/tag changed a dependency version"},
			{Name: "usage", Description: "EXPERIMENTAL: Find components that use the specified dependency"},
			{Name: "log", Description: "Show components(s) version history"},
			{Name: "move", Description: "Move a component to a different filesystem path"},
			{Name: "diff", Description: "Show the diff between the components' source files and config"},
			{Name: "envs", Description: "List all components maintained by the workspace and their corresponding envs"},
			{Name: "replace", Description: "Replace an existing env with another env for all components using the old env"},
			{Name: "update", Description: "Update a version of an env for all components using that env"},
			{Name: "start", Description: "Run the ui/development server"},
			{Name: "ui-build", Description: "Build production assets for deployment"},
			{Name: "checkout", Description: "Switch between component versions or remove local changes"},
			{Name: "install", Description: "Installs workspace dependencies"},
			{Name: "uninstall", Description: "Uninstall dependencies"},
			{Name: "component-names", Description: "Names or IDs of the components to link"},
			{Name: "component-issues", Description: "List available component-issues"},
		},
		Options: []spec.Option{
			{Name: "--bare", Description: "Initialize an empty bit bare scope"},
			{Name: "--shared", Description: "Add group write permissions to a scope"},
			{Name: "--standalone", Description: "Do not nest component store within .git"},
			{Name: "--reset", Description: "Write missing or damaged Bit files"},
			{Name: "--reset-new", Description: "Reset .bitmap file as if components were newly added"},
			{Name: "--reset-lane-new", Description: "Reset only components belonging to lanes"},
			{Name: "--reset-hard", Description: "Delete all Bit files and directories"},
			{Name: "--reset-scope", Description: "Removes local scope"},
			{Name: "--default-directory", Description: "Set the default directory pattern"},
			{Name: "--default-scope", Description: "Set the default scope for components"},
			{Name: "--package-manager", Description: "Set the package manager to be used"},
			{Name: "--force", Description: "Force workspace initialization without clearing local objects"},
			{Name: "--harmony", Description: "DEPRECATED: Harmony is the default now"},
			{Name: "--interactive", Description: "Start an interactive process"},
			{Name: "--aspect", Description: "ID of the aspect that registered the template"},
			{Name: "--template", Description: "Env-ID of the template's owner. Alias for --env"},
			{Name: "--env", Description: "Env-ID of the template. Alias for -t"},
			{Name: "--skip-git", Description: "Skip generation of Git repository in the new workspace"},
			{Name: "--empty", Description: "Skip template's default component creation"},
			{Name: "--load-from", Description: "Local path to the workspace containing the template"},
			{Name: "--cloud-domain", Description: "Login cloud domain (default bit.cloud)"},
			{Name: "--port", Description: "Port number to open for localhost server"},
			{Name: "--suppress-browser-launch", Description: "Do not open a browser for authentication"},
			{Name: "--npmrc-path", Description: "Path to npmrc file to configure bit.cloud registry"},
			{Name: "--skip-registry-config", Description: "Don't configure bit.cloud registry"},
			{Name: "--machine-name", Description: "Specify machine-name to pair with the token"},
			{Name: "--json", Description: "Return diagnoses in json format"},
			{Name: "--list", Description: "List all available diagnoses"},
			{Name: "--save", Description: "Path to save diagnoses to a file"},
			{Name: "--archive", Description: "Path to archive the workspace including diagnosis info"},
			{Name: "--metadata", Description: "Metadata/front-matter to place at the top of the .md file"},
			{Name: "--docs", Description: "Generate the cli-reference.docs.mdx file"},
			{Name: "--internal", Description: "Show internal commands"},
			{Name: "--remote", Description: "Clear memory cache from a remote scope"},
			{Name: "--global", Description: "Configure a remote bit scope"},
			{Name: "--track", Description: "Keep tracking component in .bitmap"},
			{Name: "--keep-files", Description: "Keep component files"},
			{Name: "--silent", Description: "Skip confirmation"},
			{Name: "--path", Description: "Import components into a specific directory"},
			{Name: "--objects", Description: "Import components objects without checkout"},
		},
	})
}
