package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "bosh",
		Description: "Deployment",
		Subcommands: []spec.Subcommand{
			{Name: "add-blob", Description: "Add blob"},
			{Name: "unignore", Description: "Unignore an instance"},
			{Name: "update-cloud-config", Description: "Update current cloud config"},
			{Name: "update-config", Description: "Update config"},
			{Name: "update-cpi-config", Description: "Update current CPI config"},
			{Name: "update-resurrection", Description: "Enable/disable resurrection"},
			{Name: "update-runtime-config", Description: "Update current runtime config"},
			{Name: "upload-blobs", Description: "Upload blobs"},
			{Name: "upload-release", Description: "Upload release"},
			{Name: "upload-stemcell", Description: "Upload stemcell"},
			{Name: "variables", Description: "List variables"},
			{Name: "vendor-package", Description: "Vendor package"},
			{Name: "vms", Description: "List all VMs in all deployments"},
			{Name: "orphan-disk", Description: "Orphan disk"},
			{Name: "networks", Description: "List networks"},
			{Name: "manifest", Description: "Show deployment manifest"},
			{Name: "tasks", Description: "List running or recent tasks"},
			{Name: "task", Description: "Show task status and start tracking its output"},
			{Name: "take-snapshot", Description: "Take snapshot"},
			{Name: "sync-blobs", Description: "Sync blobs"},
			{Name: "stop-env", Description: "Stop BOSH environment"},
			{Name: "stop", Description: "Stop instance(s)"},
			{Name: "stemcells", Description: "List stemcells"},
			{Name: "start-env", Description: "Start BOSH environment"},
			{Name: "start", Description: "Start instance(s)"},
			{Name: "ssh", Description: "SSH into instance(s)"},
			{Name: "snapshots", Description: "List snapshots"},
			{Name: "sha2ify-release", Description: "Convert release tarball to use SHA256"},
			{Name: "sha1ify-release", Description: "Convert release tarball to use SHA1"},
			{Name: "runtime-config", Description: "Show current runtime config"},
			{Name: "run-errand", Description: "Run errand"},
			{Name: "restart", Description: "Restart instance(s)"},
			{Name: "reset-release", Description: "Reset release"},
			{Name: "repack-stemcell", Description: "Repack stemcell"},
			{Name: "remove-blob", Description: "Remove blob"},
			{Name: "releases", Description: "List releases"},
			{Name: "recreate", Description: "Recreate instance(s)"},
			{Name: "orphaned-vms", Description: "List all the orphaned VMs in all deployments"},
			{Name: "scp", Description: "SCP to/from instance(s)"},
			{Name: "help", Description: "Show this help message"},
			{Name: "ignore", Description: "Ignore an instance"},
			{Name: "init-release", Description: "Initialize release"},
			{Name: "inspect-local-release", Description: "Display information from release metadata"},
			{Name: "inspect-local-stemcell", Description: "Display information from stemcell metadata"},
			{Name: "inspect-release", Description: "List release contents such as jobs"},
			{Name: "instances", Description: "List all instances in a deployment"},
			{Name: "interpolate", Description: "Interpolates variables into a manifest"},
			{Name: "locks", Description: "List current locks"},
			{Name: "log-in", Description: "Login"},
			{Name: "log-out", Description: "Log out"},
		},
		Options: []spec.Option{
			{Name: "--version", Description: "Show CLI version"},
			{Name: "--config", Description: "Config file path (default: ~/.bosh/config)"},
			{Name: "-e", Description: "Director environment name or URL"},
			{Name: "--ca-cert", Description: "Director CA certificate path or value"},
			{Name: "--sha2", Description: "Use SHA256 checksums"},
			{Name: "--parallel", Description: "The max number of parallel operations (default: 5)"},
			{Name: "--client", Description: "Override username or UAA client [$BOSH_CLIENT]"},
			{Name: "--client-secret", Description: "Override password or UAA client secret [$BOSH_CLIENT_SECRET]"},
			{Name: "--deployment", Description: "Deployment name [$BOSH_DEPLOYMENT]"},
			{Name: "--column", Description: "Filter to show only given column(s)"},
			{Name: "--json", Description: "Output as JSON"},
			{Name: "--tty", Description: "Force TTY-like output"},
			{Name: "--no-color", Description: "Toggle colorized output"},
			{Name: "-n", Description: "Don't ask for user input [$BOSH_NON_INTERACTIVE]"},
		},
	})
}
