package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "cf",
		Description: "Cloudfoundry cli",
		Subcommands: []spec.Subcommand{
			{Name: "app", Description: "Display health and status for app"},
			{Name: "APP_NAME", Description: "The app you want to get health and status for"},
			{Name: "ssh", Description: "Display health and status for app"},
			{Name: "env", Description: "Show all env variables for an app"},
			{Name: "orgs", Description: "List all orgs"},
			{Name: "version", Description: "Print the version of cf"},
			{Name: "login", Description: "Log user in"},
			{Name: "logout", Description: "Log user out"},
			{Name: "password", Description: "Change user password"},
			{Name: "target", Description: "Set or view the targeted org or space"},
			{Name: "api", Description: "Set or view target api url"},
			{Name: "url", Description: "API endpoint"},
			{Name: "auth", Description: "Auth user non-interactively"},
			{Name: "apps", Description: "List all apps in the target space"},
			{Name: "push", Description: "Push a new app or sync changes to an existing app"},
			{Name: "scale", Description: "Change or view the instance count, disk space limit, and memory limit for an app"},
			{Name: "delete", Description: "Delete an app"},
			{Name: "rename", Description: "Rename an app"},
			{Name: "start", Description: "Start an app"},
			{Name: "stop", Description: "Stop an app"},
			{Name: "restart", Description: "Stop all instances of the app, then start them again. This may cause downtime"},
			{Name: "run-task", Description: "Run a one-off task on an app"},
			{Name: "tasks", Description: "List tasks of an app"},
			{Name: "terminate-task", Description: "Terminate a running task of an app"},
			{Name: "events", Description: "Show recent app events"},
			{Name: "logs", Description: "Trail or show recent logs for an app"},
			{Name: "set-env", Description: "Set an environment variable for an app"},
			{Name: "unset-env", Description: "Remove an environment variable"},
			{Name: "create-app-manifest", Description: "Create an app manifest for an app that has been pushed successfully"},
			{Name: "get-health-check", Description: "Show the type of health check performed on an app"},
			{Name: "set-health-check", Description: "Change type of health check performed on an app"},
			{Name: "type of health check", Description: "Process, port or http"},
			{Name: "enable-ssh", Description: "Enable ssh for the application"},
			{Name: "disable-ssh", Description: "Disable ssh for the application"},
			{Name: "ssh-enabled", Description: "Reports whether SSH is enabled on an application container instance"},
			{Name: "marketplace", Description: "List available offerings in the marketplace"},
			{Name: "services", Description: "List all service instances in the target space"},
			{Name: "create-service", Description: "Create a service instance"},
			{Name: "update-service", Description: "Update a service instance"},
			{Name: "delete-service", Description: "Delete a service instance"},
			{Name: "rename-service", Description: "Rename a service instance"},
			{Name: "create-service-key", Description: "Create key for a service instance"},
			{Name: "service-keys", Description: "List keys for a service instance"},
			{Name: "service-key", Description: "Show service key info"},
			{Name: "delete-service-key", Description: "Delete a service key"},
			{Name: "bind-service", Description: "Bind a service instance to an app"},
			{Name: "unbind-service", Description: "Unbind a service instance from an app"},
			{Name: "bind-route-service", Description: "Bind a service instance to an HTTP route"},
			{Name: "unbind-route-service", Description: "Unbind a service instance from an HTTP route"},
			{Name: "create-user-provided-service", Description: "Make a user-provided service instance available to CF apps"},
		},
		Options: []spec.Option{
			{Name: "--guid", Description: "Display health and status for app"},
			{Name: "-v", Description: "Verbose output"},
			{Name: "-a", Description: "API endpoint (e.g. https://api.example.com)"},
			{Name: "-o", Description: "Org"},
			{Name: "-s", Description: "Space"},
			{Name: "-p", Description: "Password"},
			{Name: "-u", Description: "Username"},
			{Name: "--skip-ssl-validation", Description: "Skip verification of the API endpoint. Not recommended!"},
			{Name: "--unset", Description: "Remove all api endpoint targeting"},
			{Name: "-b", Description: "Custom buildpack by name or git url"},
			{Name: "-c", Description: "Startup command, set to null to reset to default start command"},
			{Name: "-d", Description: "Domain"},
			{Name: "-f", Description: "Path to manifest"},
			{Name: "-n", Description: "Hostname"},
			{Name: "-i", Description: "Number of instances"},
			{Name: "-k", Description: "Disk limit"},
			{Name: "-m", Description: "Memory limit"},
			{Name: "-r", Description: "Also delete any mapped routes"},
			{Name: "--name", Description: "Name for task"},
			{Name: "--recent", Description: "Dump recent logs instead of tailing"},
			{Name: "--no-restart", Description: "Create an app manifest for an app that has been pushed successfully"},
			{Name: "-t", Description: "User provided tags"},
			{Name: "--path", Description: "Path used in combination with HOSTNAME and DOMAIN to specify the route to bind"},
			{Name: "--router-group", Description: "Routes for this domain will be configured only on the specified router group"},
			{Name: "--orglevel", Description: "List all the routes for all spaces of current organization"},
			{Name: "--hostname", Description: "Hostname for the HTTP route (required for shared domains)"},
			{Name: "--port", Description: "Port for the TCP route"},
			{Name: "--random-port", Description: "Create a random port for the TCP route"},
			{Name: "--origin", Description: "Origin for mapping a user account to a user in an external identity provider"},
			{Name: "--reserved-route-ports", Description: "Maximum number of routes that may be created with reserved ports (Default: 0)"},
			{Name: "--allow-paid-service-plans", Description: "Can provision instances of paid service plans"},
			{Name: "--disallow-paid-service-plans", Description: "Cannot provision instances of paid service plans"},
			{Name: "-H", Description: "Custom headers to include in the request, flag can be specified multiple times"},
			{Name: "-X", Description: "HTTP method (GET,POST,PUT,DELETE,etc)"},
			{Name: "--checksum", Description: "Compute and show the sha1 value of the plugin binary file"},
			{Name: "--help", Description: "Show help for Cloud Foundry command line tool"},
		},
	})
}
