package ops

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "circleci",
		Description: "CircleCI CLI",
		Subcommands: []core.Subcommand{
			{Name: "completion", Description: "Generate shell completion scripts"},
			{Name: "bash", Description: "Generate bash completion scripts"},
			{Name: "zsh", Description: "Generate zsh completion scripts"},
			{Name: "config", Description: "Operate on build config files"},
			{Name: "pack", Description: "Pack CircleCI config files into a single file"},
			{Name: "process", Description: "Validate and display extended config"},
			{Name: "validate", Description: "Checks that config is valid"},
			{Name: "context", Description: "Secure and share environment variables across projects"},
			{Name: "create", Description: "Create a new context"},
			{Name: "vcs-type", Description: "Your VCS provider, can be either 'github' or 'bitbucket'"},
			{Name: "org-name", Description: "The name of your organization"},
			{Name: "delete", Description: "Delete the named context"},
			{Name: "context-name", Description: "The name for your context"},
			{Name: "list", Description: "List all contexts"},
			{Name: "remove-secret", Description: "Remove environment variable from a context"},
			{Name: "secret name", Description: "The name of the env variable to remove"},
			{Name: "show", Description: "Show a context"},
			{Name: "store-secret", Description: "Store environment variables"},
			{Name: "diagnostic", Description: "Check the status of your CircleCI CLI"},
			{Name: "follow", Description: "Attempt to follow the project for the current git repo"},
			{Name: "help", Description: "Help about any command"},
			{Name: "local", Description: "Debug jobs on the local machine"},
			{Name: "execute", Description: "Run a job in a container on the local machine"},
			{Name: "namespace", Description: "Operate on namespaces"},
			{Name: "open", Description: "Open the current project in the browser"},
			{Name: "orb", Description: "Operate on orbs"},
			{Name: "add-to-category", Description: "Add an orb to a category"},
			{Name: "namespace/orb", Description: "The namespace and orb to add to a category"},
			{Name: "category name", Description: "The name of the category to add the orb to, in quotes"},
			{Name: "info", Description: "Show metadata of an orb"},
			{Name: "init", Description: "Initialize a new orb"},
			{Name: "path", Description: "The /path/to/myProject-orb"},
			{Name: "list-categories", Description: "List orb categories"},
			{Name: "publish", Description: "Publish an orb to the registry"},
			{Name: "remove-from-category", Description: "Remove an orb from a category"},
			{Name: "source", Description: "Show source code of an orb"},
			{Name: "unlist", Description: "Disable/enable an orb's listing in the registry"},
			{Name: "condition", Description: "Use either true|false"},
			{Name: "policy", Description: "Manage security policies"},
			{Name: "decide", Description: "Make a decision"},
			{Name: "diff", Description: "Get diff between local and remote policy bundles"},
			{Name: "policy_dir_path", Description: "Policy file or directory path"},
			{Name: "eval", Description: "Perform raw opa evaluation locally"},
			{Name: "fetch", Description: "Fetch policy bundle (or a single policy)"},
			{Name: "policy name", Description: "Name of policy to fetch"},
			{Name: "logs", Description: "Get policy decision logs / decision log (or policy bundle) by decision ID"},
			{Name: "decision ID", Description: "Decision ID to get logs for"},
			{Name: "push", Description: "Push policy bundle (or a single policy)"},
			{Name: "runner", Description: "Operate on runners"},
			{Name: "instance", Description: "Operate on runner instances"},
		},
		Options: []core.Option{
			{Name: "--private", Description: "Show metadata of an orb"},
			{Name: "-u", Description: "Include uncertified orbs"},
			{Name: "--input", Description: "Path to input file, i.e. ./.circleci/config.yml"},
			{Name: "--metafile", Description: "Path to decision metadata file"},
			{Name: "--owner-id", Description: "The id of the policy's owner"},
			{Name: "--strict", Description: "Return non-zero status code for decision resulting in HARD_FAIL"},
			{Name: "--context", Description: "Policy context for decision, default is 'config'"},
			{Name: "--query", Description: "Policy decision query, default is 'data'"},
			{Name: "--after", Description: "Filter decision logs triggered AFTER this datetime"},
			{Name: "--before", Description: "Filter decision logs triggered BEFORE this datetime"},
			{Name: "--branch", Description: "Filter decision logs based on branch name"},
			{Name: "--out", Description: "Specify output file name"},
			{Name: "--policy-bundle", Description: "Get only the policy bundle for given decisionID"},
			{Name: "--project-id", Description: "Filter decision logs based on project-id"},
			{Name: "--status", Description: "Filter decision logs based on their status"},
			{Name: "--no-prompt", Description: "Removes the prompt"},
			{Name: "--enabled", Description: "Enable/disable policy decision evaluation in build pipeline"},
			{Name: "--help", Description: "Show help for CircleCI"},
			{Name: "--skip-update-check", Description: "Skip update check before every command"},
		},
	})
}
