package ops

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "doctl",
		Description: "The official DigitalOcean command line interface (CLI)",
		Subcommands: []core.Subcommand{
			{Name: "help", Description: "Display help about commands"},
			{Name: "get", Description: "Retrieve account profile details"},
			{Name: "ratelimit", Description: "Retrieve your API usage and the remaining quota"},
			{Name: "apps", Description: "Display commands for working with apps"},
			{Name: "create", Description: "Create an app"},
			{Name: "create-deployment", Description: "Create a deployment"},
			{Name: "delete", Description: "Deletes an app"},
			{Name: "get-deployment", Description: "Get a deployment"},
			{Name: "list", Description: "List all apps"},
			{Name: "list-alerts", Description: "List alerts on an app"},
			{Name: "list-deployments", Description: "List all deployments"},
			{Name: "list-regions", Description: "List App Platform regions"},
			{Name: "logs", Description: "Get logs"},
			{Name: "propose", Description: "Propose an app spec"},
			{Name: "spec", Description: "Display commands for working with app specs"},
			{Name: "tier", Description: "Display commands for working with app tiers"},
			{Name: "update", Description: "Update an app"},
			{Name: "update-alert-destinations", Description: "Update alert destinations"},
			{Name: "auth", Description: "Display commands for authenticating doctl with an account"},
			{Name: "init", Description: "Initialize doctl to use a specific account"},
			{Name: "remove", Description: "Remove authentication contexts"},
			{Name: "switch", Description: "Switches between authentication contexts"},
			{Name: "balance", Description: "Display commands for retrieving your account balance"},
			{Name: "billing-history", Description: "Display commands for retrieving your billing history"},
			{Name: "compute", Description: "Display commands that manage infrastructure"},
			{Name: "action", Description: "Display commands for retrieving resource action history"},
			{Name: "cdn", Description: "Display commands that manage CDNs"},
			{Name: "certificate", Description: "Display commands that manage SSL certificates and private keys"},
			{Name: "domain", Description: "Display commands that manage domains"},
			{Name: "droplet", Description: "Manage virtual machines (Droplets)"},
			{Name: "droplet-action", Description: "Display Droplet action commands"},
			{Name: "firewall", Description: "Display commands to manage cloud firewalls"},
			{Name: "floating-ip", Description: "Display commands to manage floating IP addresses"},
			{Name: "floating-ip-action", Description: "Display commands to associate floating IP addresses with Droplets"},
			{Name: "image", Description: "Display commands to manage images"},
			{Name: "image-action", Description: "Display commands to perform actions on images"},
			{Name: "load-balancer", Description: "Display commands to manage load balancers"},
			{Name: "region", Description: "Display commands to list datacenter regions"},
			{Name: "size", Description: "List available Droplet sizes"},
			{Name: "snapshot", Description: "Access and manage snapshots"},
			{Name: "ssh", Description: "Access a Droplet using SSH"},
			{Name: "ssh-key", Description: "Display commands to manage SSH keys on your account"},
			{Name: "tag", Description: "Display commands to manage tags"},
			{Name: "volume", Description: "Display commands to manage block storage volumes"},
			{Name: "volume-action", Description: "Display commands to perform actions on a volume"},
			{Name: "databases", Description: "Display commands that manage databases"},
			{Name: "backups", Description: "List database cluster backups"},
			{Name: "connection", Description: "Retrieve connection details for a database cluster"},
			{Name: "db", Description: "Display commands for managing individual databases within a cluster"},
			{Name: "maintenance-window", Description: "Display commands for scheduling automatic maintenance on your database cluster"},
		},
		Options: []core.Option{
			{Name: "-h", Description: "Help for doctl"},
			{Name: "-v", Description: "Enable verbose output"},
			{Name: "-o", Description: "Desired output format"},
			{Name: "--trace", Description: "Show a log of network activity while performing a command"},
			{Name: "-c", Description: "Override default API endpoint"},
			{Name: "-t", Description: "API V2 access token"},
		},
	})
}
