package ops

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "hugo",
		Description: "The world's fastest framework for building websites",
		Subcommands: []core.Subcommand{
			{Name: "check", Description: "Contains some verification checks"},
			{Name: "ulimit", Description: "Check system ulimit settings"},
			{Name: "config", Description: "Print the site configuration"},
			{Name: "mounts", Description: "Print the configured file mounts"},
			{Name: "convert", Description: "Convert your content to different formats"},
			{Name: "toJSON", Description: "Convert front matter to JSON"},
			{Name: "toTOML", Description: "Convert front matter to TOML"},
			{Name: "toYAML", Description: "Convert front matter to YAML"},
			{Name: "deploy", Description: "Deploy your site to a Cloud provider"},
			{Name: "env", Description: "Print Hugo version and environment info"},
			{Name: "gen", Description: "A collection of several useful generators"},
			{Name: "autocomplete", Description: "Generate shell autocompletion script for Hugo (default outputs to stdout)"},
			{Name: "bash", Description: "Default"},
			{Name: "friendly", Description: "Default"},
			{Name: "doc", Description: "Generate Markdown documentation for the Hugo CLI (default '/tmp/hugodoc/')"},
			{Name: "man", Description: "Generate man pages for the Hugo CLI (default 'man/')"},
			{Name: "help", Description: "Help about any command"},
			{Name: "import", Description: "Import your site from others"},
			{Name: "list", Description: "Listing out various types of content"},
			{Name: "drafts", Description: "List all drafts"},
			{Name: "future", Description: "List all posts dated in the future"},
			{Name: "expired", Description: "List all posts already expired"},
			{Name: "all", Description: "List all posts"},
			{Name: "mod", Description: "Various Hugo Modules helpers"},
			{Name: "clean", Description: "Delete the Hugo Module cache for the current project"},
			{Name: "get", Description: "Resolves dependencies in your current Hugo Project"},
			{Name: "init", Description: "Initialize this project as a Hugo Module"},
			{Name: "npm", Description: "Various npm helpers"},
			{Name: "pack", Description: "Experimental: Prepares and writes a composite package.json file for your project"},
			{Name: "tidy", Description: "Remove unused entries in go.mod and go.sum"},
			{Name: "vendor", Description: "Vendor all module dependencies into the _vendor directory"},
			{Name: "verify", Description: "Verify dependencies"},
			{Name: "new", Description: "Create new content for your site"},
			{Name: "site", Description: "Create a new site (skeleton)"},
			{Name: "toml", Description: "Default"},
			{Name: "theme", Description: "Create a new theme"},
			{Name: "server", Description: "A high performance webserver"},
			{Name: "version", Description: "Print the version number of Hugo"},
		},
		Options: []core.Option{
			{Name: "-h", Description: "Config file (default is path/config.yaml|json|toml)"},
			{Name: "--configDir", Description: "Config dir (default 'config')"},
			{Name: "--debug", Description: "Debug output (default false)"},
			{Name: "-e", Description: "Build environment"},
			{Name: "--ignoreVendor", Description: "Ignores any _vendor directory (default false)"},
			{Name: "--ignoreVendorPaths", Description: "Ignores any _vendor for module paths matching the given Glob pattern"},
			{Name: "--log", Description: "Enable Logging (default false)"},
			{Name: "--logFile", Description: "Log File path (if set, logging enabled automatically)"},
			{Name: "--quiet", Description: "Build in quiet mode (default false)"},
			{Name: "-s", Description: "Filesystem path to read files relative from"},
			{Name: "--themesDir", Description: "Filesystem path to themes directory"},
			{Name: "-v", Description: "Verbose output (default false)"},
			{Name: "--verboseLog", Description: "Verbose logging (default false)"},
			{Name: "-b", Description: "Hostname (and path) to the root, e.g. http://spf13.com/"},
			{Name: "-D", Description: "Include content marked as draft (default false)"},
			{Name: "-E", Description: "Include expired content (default false)"},
			{Name: "-F", Description: "Include content with publishdate in the future (default false)"},
			{Name: "--cacheDir", Description: "Filesystem path to cache directory. Defaults: $TMPDIR/hugo_cache/"},
			{Name: "--cleanDestinationDir", Description: "Remove files from destination not found in static directories (default false)"},
			{Name: "-c", Description: "Filesystem path to content directory"},
			{Name: "-d", Description: "Filesystem path to write files to"},
			{Name: "--disableKinds", Description: "Disable different kind of pages (home, RSS etc.)"},
			{Name: "--enableGitInfo", Description: "Add Git revision, date and author info to the pages (default false)"},
			{Name: "--forceSyncStatic", Description: "Copy all files when static is changed (default false)"},
			{Name: "--gc", Description: "Print missing translations (default false)"},
			{Name: "--ignoreCache", Description: "Ignores the cache directory (default false)"},
			{Name: "-l", Description: "Filesystem path to layout directory"},
			{Name: "--minify", Description: "Minify any supported output format (HTML, XML etc.) (default false)"},
			{Name: "--noChmod", Description: "Don't sync permission mode of files (default false)"},
			{Name: "--noTimes", Description: "Don't sync modification time of files (default false)"},
			{Name: "--path-warnings", Description: "Print warnings on duplicate target paths etc (default false)"},
			{Name: "--poll", Description: "Print memory usage to screen at intervals (default false)"},
			{Name: "--templateMetrics", Description: "Display metrics about template executions (default false)"},
			{Name: "--templateMetricsHints", Description: "Themes to use (located in /themes/THEMENAME/)"},
			{Name: "--trace", Description: "Write trace to file (not useful in general)"},
			{Name: "-w", Description: "Watch filesystem for changes and recreate as needed (default true)"},
			{Name: "-o", Description: "Filesystem path to write files to"},
			{Name: "--unsafe", Description: "Enable less safe operations, please backup first"},
			{Name: "--confirm", Description: "Ask for confirmation before making changes to the target"},
			{Name: "--dryRun", Description: "Dry run"},
		},
	})
}
