package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "lpass",
		Description: "Command line interface for LastPass",
		Subcommands: []spec.Subcommand{
			{Name: "login", Description: "Log in to LastPass"},
			{Name: "USERNAME", Description: "LastPass account username (email address)"},
			{Name: "logout", Description: "Log out of LastPass"},
			{Name: "ls", Description: "List names in groups in a tree structure"},
			{Name: "GROUP", Description: "Group of entries to list"},
			{Name: "passwd", Description: "Change LastPass password and reencrypt all entries"},
			{Name: "show", Description: "Show password or selected field"},
			{Name: "FIELD", Description: "Show only this field"},
			{Name: "ATTACHID", Description: "Attachment ID"},
			{Name: "UNIQENAME|UNIQUEID", Description: "Shows entry with this unique name or ID"},
			{Name: "mv", Description: "Move LastPass entry to a different group"},
			{Name: "UNIQUENAME|UNIQUEID", Description: "Unique name or ID to move"},
			{Name: "add", Description: "Add a new entry"},
			{Name: "NOTETYPE", Description: "Type of note to add"},
			{Name: "NAME|UNIQUEID", Description: "Name or unique ID of the entry to add"},
			{Name: "edit", Description: "Edit existing entry"},
			{Name: "generate", Description: "Create randomly generated password"},
			{Name: "URL", Description: "URL to generate the password for"},
			{Name: "LENGTH", Description: "Length of the password to create"},
			{Name: "duplicate", Description: "Duplicate existing entry"},
			{Name: "rm", Description: "Removes existing entry"},
			{Name: "status", Description: "Show the LastPass login status"},
			{Name: "sync", Description: "Sync the local cache against the LastPass server"},
			{Name: "import", Description: "Import account information from an unencrypted CSV"},
			{Name: "FILENAME", Description: "CSV filename to import from"},
			{Name: "export", Description: "Export account information to an unencrypted CSV"},
			{Name: "share", Description: "LastPass Sharing Center functionality"},
			{Name: "userls", Description: "List the LastPass users which have access to the Shared Folders"},
			{Name: "useradd", Description: "Add user to Shared Folders"},
			{Name: "true", Description: "Grant read only access"},
			{Name: "false", Description: "Grant write access"},
			{Name: "SHARE", Description: "Entry to share"},
			{Name: "usermod", Description: "Modify user on Shared Folders"},
			{Name: "userdel", Description: "Remove user from Shared Folders"},
			{Name: "create", Description: "Create new LastPass Shared Folder"},
			{Name: "limit", Description: "Manipulate LastPass Shared Folder access"},
			{Name: "sites", Description: "LastPass sites to manipulate"},
		},
		Options: []spec.Option{
			{Name: "--trust", Description: "Subsequent logins will not require multifactor authentication"},
			{Name: "--plaintext-key", Description: "Save decryption key to the hard disk in plaintext"},
			{Name: "--force", Description: "Skip user confirmation"},
			{Name: "--color", Description: "Control colored output to the terminal"},
			{Name: "--long", Description: "Show the last modification time"},
			{Name: "-m", Description: "Show the last modified time"},
			{Name: "-u", Description: "Show the last used time"},
			{Name: "--sync", Description: "When the current operation syncs to server"},
			{Name: "--clip", Description: "Copy to the clipboard"},
			{Name: "--quiet", Description: "Display no output and only sets return code"},
			{Name: "--expand-multi", Description: "Show information from all matching sites"},
			{Name: "--json", Description: "Generate json output instead of human-readable text"},
			{Name: "--all", Description: "Show all fields"},
			{Name: "--username", Description: "Show only the username"},
			{Name: "--password", Description: "Show only the password"},
			{Name: "--url", Description: "Show only the URL"},
			{Name: "--notes", Description: "Show only the notes"},
			{Name: "--field", Description: "Show only the field"},
			{Name: "--id", Description: "Show only the ID"},
			{Name: "--name", Description: "Show only the name"},
			{Name: "--attach", Description: "Show only the attachment"},
			{Name: "--basic-regexp", Description: "Show sites matching case-insensitive regular expression"},
			{Name: "--fixed-strings", Description: "Show sites matching this exact substring"},
			{Name: "--non-interactive", Description: "Control colored output to the terminal"},
			{Name: "--note-type", Description: "Add only the note"},
			{Name: "--no-symbols", Description: "Generate password without symbols"},
			{Name: "--background", Description: "Synchronization occurs in a daemonized process"},
			{Name: "--keep-dupes", Description: "Keeps any duplicate entries"},
			{Name: "--fields", Description: "CSV filename to export to"},
			{Name: "--read-only", Description: "Control read or write access"},
			{Name: "--hidden", Description: "Share user view permission"},
			{Name: "--admin", Description: "Share user administer permission"},
			{Name: "--deny", Description: "Deny or allow access"},
			{Name: "--add", Description: "Add, remove, or clear access"},
			{Name: "--help", Description: "Display the help for lpass"},
			{Name: "--version", Description: "Display the version of lpass"},
		},
	})
}
