package ops

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "okteto",
		Description: "Context",
		Subcommands: []core.Subcommand{
			{Name: "analytics", Description: "Enable / Disable analytics"},
			{Name: "build", Description: "Build (and optionally push) a Docker image"},
			{Name: "completion", Description: "Generate the autocompletion script for the specified shell"},
			{Name: "bash", Description: "Generate the autocompletion script for bash"},
			{Name: "fish", Description: "Generate the autocompletion script for fish"},
			{Name: "powershell", Description: "Generate the autocompletion script for powershell"},
			{Name: "zsh", Description: "Generate the autocompletion script for zsh"},
			{Name: "ctx", Description: "Set the default context"},
			{Name: "delete", Description: "Delete a context"},
			{Name: "ls", Description: "List available contexts"},
			{Name: "show", Description: "Print the current context"},
			{Name: "use", Description: "Set the default context"},
			{Name: "doctor", Description: "Generate a zip file with the okteto logs"},
			{Name: "down", Description: "Deactivate your development container"},
			{Name: "exec", Description: "Execute a command in your development container"},
			{Name: "init", Description: "Automatically generate your okteto manifest file"},
			{Name: "kubeconfig", Description: "Download credentials for the Kubernetes cluster selected via 'okteto context'"},
			{Name: "ns", Description: "Configure the current namespace of the okteto context"},
			{Name: "create", Description: "Create a namespace"},
			{Name: "pipeline", Description: "Pipeline management commands"},
			{Name: "deploy", Description: "Deploy an okteto pipeline"},
			{Name: "destroy", Description: "Destroy an okteto pipeline"},
			{Name: "preview", Description: "Preview environment management commands"},
			{Name: "endpoints", Description: "Show endpoints for a preview environment"},
			{Name: "list", Description: "List all preview environments"},
			{Name: "push", Description: "Build, push and redeploy source code to the target app"},
			{Name: "restart", Description: "Restart the deployments listed in the services field of the okteto manifest"},
			{Name: "stack", Description: "Stack management commands"},
			{Name: "status", Description: "Status of the synchronization process"},
			{Name: "up", Description: "Activate your development container"},
			{Name: "update", Description: "Update okteto version"},
			{Name: "version", Description: "View the version of the okteto binary"},
			{Name: "help", Description: "Help about any command"},
		},
		Options: []core.Option{
			{Name: "--loglevel", Description: "Amount of information outputted (debug, info, warn, error)"},
			{Name: "--output", Description: "Output format (tty, plain, json)"},
			{Name: "--disable", Description: "Disable analytics"},
			{Name: "--help", Description: "Help for analytics"},
			{Name: "--build-arg", Description: "Set build-time variables"},
			{Name: "--cache-from", Description: "Cache source images"},
			{Name: "--file", Description: "Name of the Dockerfile (Default is 'PATH/Dockerfile')"},
			{Name: "--namespace", Description: "Do not use cache when building the image"},
			{Name: "--progress", Description: "Show plain/tty build output"},
			{Name: "--secret", Description: "Secret files exposed to the build. Format: id=mysecret,src=/local/secret"},
			{Name: "--tag", Description: "Name and optionally a tag in the 'name:tag' format (it is automatically pushed)"},
			{Name: "--target", Description: "Set the target build stage to build"},
			{Name: "--no-descriptions", Description: "Disable completion descriptions"},
			{Name: "--builder", Description: "Url of the builder service"},
			{Name: "--okteto", Description: "Only shows okteto cluster options"},
			{Name: "--token", Description: "API token for authentication"},
			{Name: "--context", Description: "Context where the up command was executing"},
			{Name: "--volumes", Description: "Remove persistent volume"},
			{Name: "--overwrite", Description: "Overwrite existing manifest file"},
			{Name: "--members", Description: "Members of the namespace, it can the username or email"},
			{Name: "--personal", Description: "Load personal account"},
			{Name: "--branch", Description: "The branch to deploy (defaults to the current branch)"},
			{Name: "--repository", Description: "The repository to deploy (defaults to the current repository)"},
			{Name: "--skip-if-exists", Description: "Set a pipeline variable (can be set more than once)"},
			{Name: "--wait", Description: "Wait until the pipeline finishes (defaults to false)"},
			{Name: "--name", Description: "Name of the pipeline (defaults to the git config name)"},
			{Name: "--timeout", Description: "Destroy persistent volumes created by the pipeline (defaults to false)"},
			{Name: "--scope", Description: "The URL of the original pull/merge request"},
			{Name: "--deploy", Description: "Create deployment when the app doesn't exist in a namespace"},
			{Name: "--no-cache", Description: "Do not use cache when building the image"},
			{Name: "--build", Description: "Build images before starting any Stack service"},
			{Name: "--info", Description: "Show syncthing links for troubleshooting the synchronization service"},
			{Name: "--watch", Description: "Watch for changes"},
			{Name: "--pull", Description: "Force dev image pull"},
			{Name: "--remote", Description: "Configures remote execution on the specified port"},
			{Name: "--reset", Description: "Reset the file synchronization database"},
		},
	})
}
