package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "podman",
		Description: "Build an image using instructions from Containerfiles",
		Subcommands: []spec.Subcommand{
			{Name: "events", Description: "Show podman system events"},
			{Name: "info", Description: "Display podman system information"},
			{Name: "inspect", Description: "Display the configuration of object denoted by ID"},
			{Name: "login", Description: "Log in to a container registry"},
			{Name: "logout", Description: "Log out of a container registry"},
			{Name: "search", Description: "Search registry for image"},
			{Name: "TERM", Description: "Search term"},
			{Name: "version", Description: "Display the Podman version information"},
			{Name: "container", Description: "Manage containers"},
			{Name: "prune", Description: "Remove all stopped containers"},
			{Name: "image", Description: "Manage images"},
			{Name: "network", Description: "Manage networks"},
			{Name: "connect", Description: "Connect a container to a network"},
			{Name: "create", Description: "Create a network"},
			{Name: "disconnect", Description: "Disconnect a container from a network"},
			{Name: "ls", Description: "List networks"},
			{Name: "rm", Description: "Remove one or more networks"},
			{Name: "secret", Description: "Manage secrets"},
			{Name: "system", Description: "Manage podman"},
			{Name: "df", Description: "Show podman disk usage"},
			{Name: "volume", Description: "Manage volumes"},
			{Name: "generate", Description: "Generate structured data based on containers, pods or volumes"},
			{Name: "healthcheck", Description: "Manage health checks on containers"},
			{Name: "help", Description: "Help about any command"},
			{Name: "init", Description: "Initialize one or more containers"},
			{Name: "kube", Description: "Play containers, pods or volumes from a structured file"},
			{Name: "machine", Description: "Manage a virtual machine"},
			{Name: "list", Description: "List machines"},
			{Name: "os", Description: "Manage a Podman virtual machine's OS"},
			{Name: "set", Description: "Set a virtual machine setting"},
			{Name: "ssh", Description: "SSH into an existing machine"},
			{Name: "start", Description: "Start an existing machine"},
			{Name: "stop", Description: "Stop an existing machine"},
			{Name: "manifest", Description: "Manipulate manifest lists and image indexes"},
			{Name: "pod", Description: "Manage pods"},
			{Name: "untag", Description: "Remove a name from a local image"},
		},
		Options: []spec.Option{
			{Name: "--add-host", Description: "Add a custom host-to-IP mapping (host:ip)"},
			{Name: "--build-arg", Description: "Set build-time variables"},
			{Name: "--cache-from", Description: "Images to consider as cache sources"},
			{Name: "--disable-content-trust", Description: "Skip image verification (default true)"},
			{Name: "-f", Description: "Name of the Dockerfile (Default is 'PATH/Dockerfile')"},
			{Name: "--iidfile", Description: "Write the image ID to the file"},
			{Name: "--isolation", Description: "Container isolation technology"},
			{Name: "--label", Description: "Set metadata for an image"},
			{Name: "--network", Description: "Do not use cache when building the image"},
			{Name: "-o", Description: "Output destination (format: type=local,dest=path)"},
			{Name: "--platform", Description: "Set platform if server is multi-platform capable"},
			{Name: "--progress", Description: "Always attempt to pull a newer version of the image"},
			{Name: "-q", Description: "Suppress the build output and print image ID on success"},
			{Name: "--secret", Description: "Squash newly built layers into a single new layer"},
			{Name: "--ssh", Description: "Name and optionally a tag in the 'name:tag' format"},
			{Name: "--target", Description: "Set the target build stage to build"},
			{Name: "--detach-keys", Description: "Override the key sequence for detaching a container"},
			{Name: "--no-stdin", Description: "Do not attach STDIN"},
			{Name: "--sig-proxy", Description: "Proxy all received signals to the process (default true)"},
			{Name: "-it", Description: "Launch an interactive session"},
			{Name: "-l", Description: "Remove the specified link"},
			{Name: "-v", Description: "Remove the anonymous volumes associated with the container"},
			{Name: "-a", Description: "Attach to STDIN, STDOUT or STDERR"},
			{Name: "--blkio-weight", Description: "Block IO (relative weight), between 10 and 1000, or 0 to disable (default 0)"},
			{Name: "--blkio-weight-device", Description: "Block IO weight (relative device weight) (default [])"},
			{Name: "--cap-add", Description: "Add Linux capabilities"},
			{Name: "--cap-drop", Description: "Drop Linux capabilities"},
			{Name: "--cgroup-parent", Description: "Optional parent cgroup for the container"},
			{Name: "--cgroupns", Description: "Write the container ID to the file"},
			{Name: "--cpu-period", Description: "Limit CPU CFS (Completely Fair Scheduler) period"},
			{Name: "--cpu-quota", Description: "Limit CPU CFS (Completely Fair Scheduler) quota"},
			{Name: "--cpu-rt-period", Description: "Limit CPU real-time period in microseconds"},
			{Name: "--cpu-rt-runtime", Description: "Limit CPU real-time runtime in microseconds"},
			{Name: "-c", Description: "CPU shares (relative weight)"},
			{Name: "--cpus", Description: "Number of CPUs"},
			{Name: "--cpuset-cpus", Description: "CPUs in which to allow execution (0-3, 0,1)"},
			{Name: "--cpuset-mems", Description: "MEMs in which to allow execution (0-3, 0,1)"},
			{Name: "-d", Description: "Run container in background and print container ID"},
			{Name: "--device", Description: "Add a host device to the container"},
			{Name: "--device-cgroup-rule", Description: "Add a rule to the cgroup allowed devices list"},
		},
	})
}
