package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "pulumi",
		Description: "The name of the stack to operate on. Defaults to the current stack",
		Subcommands: []spec.Subcommand{
			{Name: "about", Description: "Print information about the Pulumi environment"},
			{Name: "cancel", Description: "Cancel a stack’s currently running update, if any"},
			{Name: "config", Description: "Manage configuration"},
			{Name: "cp", Description: "Copy config to another stack"},
			{Name: "get", Description: "Get a single configuration value"},
			{Name: "refresh", Description: "Update the local configuration based on the most recent deployment of the stack"},
			{Name: "rm", Description: "Remove configuration value"},
			{Name: "rm-all", Description: "Remove multiple configuration values"},
			{Name: "set", Description: "Set configuration value"},
			{Name: "set-all", Description: "Set multiple configuration values"},
			{Name: "console", Description: "Opens the current stack in the Pulumi Console"},
			{Name: "destroy", Description: "Destroy an existing stack and its resources"},
			{Name: "import", Description: "Import resources into an existing stack"},
			{Name: "login", Description: "Log in to the Pulumi service"},
			{Name: "logout", Description: "Log out of the Pulumi service"},
			{Name: "logs", Description: "[PREVIEW] Show aggregated resource logs for a stack"},
			{Name: "new", Description: "Create a new Pulumi project"},
			{Name: "org", Description: "Manage Organization configuration"},
			{Name: "get-default", Description: "Get the default org for the current backend"},
			{Name: "set-default", Description: "Set the default organization for the current backend"},
			{Name: "plugin", Description: "Manage language and resource provider plugins"},
			{Name: "install", Description: "Install one or more plugins"},
			{Name: "ls", Description: "List plugins"},
			{Name: "policy", Description: "Manage resource policies"},
			{Name: "disable", Description: "Disable a Policy Pack for a Pulumi organization"},
			{Name: "enable", Description: "Enable a Policy Pack for a Pulumi organization"},
			{Name: "group", Description: "Manage policy groups"},
			{Name: "publish", Description: "Publish a Policy Pack to the Pulumi service"},
			{Name: "validate-config", Description: "Validate a Policy Pack configuration"},
			{Name: "preview", Description: "Show a preview of updates to a stack’s resources"},
			{Name: "schema", Description: "Analyze package schemas"},
			{Name: "check", Description: "Check a Pulumi package schema for errors"},
			{Name: "stack", Description: "Manage stacks"},
			{Name: "change-secrets-provider", Description: "Change the secrets provider for the current stack"},
			{Name: "export", Description: "Export a stack’s deployment to standard out"},
			{Name: "graph", Description: "Export a stack’s dependency graph to a file"},
			{Name: "history", Description: "[PREVIEW] Display history for a stack"},
			{Name: "init", Description: "Create an empty stack with the given name, ready for updates"},
			{Name: "output", Description: "Show a stack’s output properties"},
			{Name: "rename", Description: "Rename an existing stack"},
			{Name: "select", Description: "Switch the current workspace to the given stack"},
			{Name: "tag", Description: "Manage stack tags"},
			{Name: "state", Description: "Edit the current stack’s state"},
			{Name: "delete", Description: "Deletes a resource from a stack’s state"},
			{Name: "unprotect", Description: "Unprotect resources in a stack’s state"},
			{Name: "up", Description: "Deploy code and/or resource changes"},
			{Name: "version", Description: "Print Pulumi’s version number"},
			{Name: "watch", Description: "[PREVIEW] Continuously update the resources in a stack"},
			{Name: "whoami", Description: "Displays the username of the currently logged in user"},
		},
		Options: []spec.Option{
			{Name: "-s", Description: "The name of the stack to operate on. Defaults to the current stack"},
			{Name: "-y", Description: "Skip confirmation prompts, and proceed with cancellation anyway"},
			{Name: "-j", Description: "Emit output as JSON"},
			{Name: "--config-file", Description: "Optional message to associate with the destroy operation"},
			{Name: "-p", Description: "Display operation as a rich diff showing the overall change"},
			{Name: "-d", Description: "Print detailed debugging output during resource operations"},
			{Name: "-l", Description: "Use Pulumi in local-only mode"},
			{Name: "-f", Description: "Do not perform a preview before performing the destroy"},
			{Name: "-t", Description: "The key contains a path to a property in a map or list to set"},
			{Name: "--path", Description: "Parse the keys as paths in a map or list rather than raw strings"},
			{Name: "--suppress-permalink", Description: "Suppress display of the state permalink"},
			{Name: "--secrets-provider", Description: "Run pulumi as if it had been started in another directory"},
			{Name: "--disable-integrity-checking", Description: "Disable integrity checking of checkpoint files"},
			{Name: "-e", Description: "Enable emojis in the output"},
			{Name: "--logflow", Description: "Flow log settings to child processes (like plugins)"},
			{Name: "--logtostderr", Description: "Log to stderr instead of to files"},
			{Name: "--non-interactive", Description: "Disable interactive mode for all commands"},
			{Name: "--profiling", Description: "Enable verbose logging (e.g., v=3); anything >3 is very verbose"},
			{Name: "-r", Description: "Refresh the state of the stack's resources before this update"},
			{Name: "--show-config", Description: "Show configuration keys and variables"},
			{Name: "--show-replacement-steps", Description: "Show detailed resource replacement creates and deletes instead of a single step"},
			{Name: "--show-sames", Description: "Suppress display of stack outputs (in case they contain sensitive values)"},
			{Name: "--target-dependents", Description: "Print information about the Pulumi environment"},
			{Name: "--plaintext", Description: "Save the value as plaintext (unencrypted)"},
			{Name: "--secret", Description: "Encrypt the value instead of storing it in plaintext"},
			{Name: "--show-secrets", Description: "Show secret values when listing config instead of displaying blinded values"},
			{Name: "--exclude-protected", Description: "Do not destroy protected resources. Destroy all other resources"},
			{Name: "-o", Description: "The path to the file that will contain the generated resource declarations"},
			{Name: "--parent", Description: "Suppress display of stack outputs (in case they contain sensitive values)"},
			{Name: "-c", Description: "A cloud URL to log in to"},
			{Name: "--default-org", Description: "Log out of the Pulumi service"},
			{Name: "--all", Description: "Logout of all backends"},
			{Name: "--config-path", Description: "Config keys contain a path to a property in a map or list to set"},
			{Name: "--dir", Description: "Forces content to be generated even if it would change existing files"},
			{Name: "-g", Description: "The project name; if not specified, a prompt will request it"},
			{Name: "--exact", Description: "Force installation of an exact version match (usually >= is accepted)"},
			{Name: "--reinstall", Description: "Reinstall a plugin even if it already exists"},
			{Name: "--server", Description: "A URL to download plugins from"},
			{Name: "-a", Description: "Remove all plugins"},
			{Name: "--policy-group", Description: "Enable a Policy Pack for a Pulumi organization"},
		},
	})
}
