package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "sfdx",
		Description: "Analyze (lint) Aura component code",
		Subcommands: []spec.Subcommand{
			{Name: "force:lightning:lint", Description: "Analyze (lint) Aura component code"},
			{Name: "fig-completion", Description: "Generate a Fig completion spec"},
			{Name: "commands", Description: "List all the commands"},
			{Name: "plugins", Description: "List installed plugins"},
			{Name: "plugins:inspect", Description: "Displays installation properties of a plugin"},
			{Name: "plugin", Description: "Plugin to inspect"},
			{Name: "plugins:install", Description: "Installs a plugin into the CLI"},
			{Name: "plugins:link", Description: "Links a plugin into the CLI for development"},
			{Name: "path", Description: "Path to plugin"},
			{Name: "plugins:uninstall", Description: "Removes a plugin from the CLI"},
			{Name: "plugins:update", Description: "Update installed plugins"},
			{Name: "autocomplete", Description: "Display autocomplete installation instructions"},
			{Name: "shell", Description: "Shell type"},
			{Name: "update", Description: "Update the sfdx CLI"},
			{Name: "which", Description: "Show which plugin a command is in"},
			{Name: "force:cmdt:create", Description: "Creates a new custom metadata type in the current project"},
			{Name: "force:cmdt:field:create", Description: "Generate a custom metadata field based on the field type provided"},
			{Name: "force:cmdt:generate", Description: "Generates a custom metadata type and all its records for the provided sObject"},
			{Name: "force:cmdt:record:create", Description: "Create a new record for a given custom metadata type in the current project"},
			{Name: "force:cmdt:record:insert", Description: "Create new custom metadata type records from a CSV file"},
			{Name: "alias:list", Description: "List username aliases for the Salesforce CLI"},
			{Name: "alias:set", Description: "Set username aliases for the Salesforce CLI"},
			{Name: "alias:unset", Description: "Unsets aliases for the Salesforce CLI"},
			{Name: "force:apex:execute", Description: "Executes anonymous Apex code"},
			{Name: "force:apex:log:get", Description: "Fetch debug logs"},
			{Name: "force:apex:log:list", Description: "Display a list of IDs and general information about debug logs"},
			{Name: "force:apex:test:report", Description: "Display test results for a specific asynchronous test run"},
			{Name: "force:apex:test:run", Description: "Invoke Apex tests"},
			{Name: "config:get", Description: "Get config var values for given names"},
			{Name: "config:unset", Description: "Unsets the local and global configuration variables for the Salesforce CLI"},
			{Name: "force:data:bulk:delete", Description: "Bulk delete records from a csv file"},
			{Name: "force:data:bulk:status", Description: "View the status of a bulk data load job or batch"},
			{Name: "force:data:bulk:upsert", Description: "Bulk upsert records from a CSV file"},
			{Name: "force:data:record:create", Description: "Creates and inserts a record"},
			{Name: "force:data:record:delete", Description: "Deletes a single record"},
			{Name: "force:data:record:get", Description: "Displays a single record"},
			{Name: "force:data:record:update", Description: "Updates a single record"},
			{Name: "force:data:soql:query", Description: "Execute a SOQL query"},
			{Name: "force:data:tree:export", Description: "Export data from an org"},
			{Name: "force:data:tree:import", Description: "Import data into an org"},
			{Name: "auth:accesstoken:store", Description: "Authorize an org using an existing Salesforce access token"},
			{Name: "auth:device:login", Description: "Authorize an org using a device code"},
			{Name: "auth:jwt:grant", Description: "Authorize an org using the JWT flow"},
			{Name: "auth:list", Description: "List auth connection information"},
			{Name: "auth:logout", Description: "Log out from authorized orgs"},
			{Name: "auth:sfdxurl:store", Description: "Authorize an org using an SFDX auth URL"},
			{Name: "auth:web:login", Description: "Authorize an org using the web login flow"},
			{Name: "force:limits:api:display", Description: "Display current org’s limits"},
			{Name: "force:limits:recordcounts:display", Description: "Display record counts for the specified standard and custom objects"},
			{Name: "force:org:display", Description: "Get the description for the current or target org"},
		},
		Options: []spec.Option{
			{Name: "--json", Description: "Format output as json"},
			{Name: "--loglevel", Description: "Logging level for this command invocation"},
			{Name: "-i", Description: "Pattern used to ignore some folders"},
			{Name: "--files", Description: "Pattern used to include specific files"},
			{Name: "--config", Description: "Path to a custom ESLint configuration file"},
			{Name: "--verbose", Description: "Report warnings in addition to errors"},
			{Name: "--exit", Description: "Exit with error code 1 if there are lint issues"},
			{Name: "-h", Description: "Show CLI help"},
			{Name: "-o", Description: "Filepath to export completion spec (do not specify file extension)"},
			{Name: "-l", Description: "List all the commands"},
			{Name: "-j", Description: "Display unfiltered api data in json format"},
			{Name: "--hidden", Description: "Show hidden commands"},
			{Name: "--columns", Description: "Only show provided columns (comma-separated)"},
			{Name: "--sort", Description: "Property to sort by (prepend '-' for descending)"},
			{Name: "--filter", Description: "Filter property by partial string matching, ex: name=foo"},
			{Name: "--csv", Description: "Output is csv format [alias: --output=csv]"},
			{Name: "--output", Description: "Output in a more machine friendly format"},
			{Name: "-x", Description: "Show extra columns"},
			{Name: "--no-truncate", Description: "Do not truncate output to fit screen"},
			{Name: "--no-header", Description: "Hide table header from output"},
			{Name: "--core", Description: "Show core plugins"},
			{Name: "-v", Description: "Plugin to inspect"},
			{Name: "-r", Description: "Refresh cache (ignores displaying instructions)"},
			{Name: "--from-local", Description: "Interactively choose an already installed version"},
			{Name: "-n", Description: "Unique object name for the custom metadata type"},
			{Name: "-p", Description: "Plural version of the label value; if blank, uses label"},
			{Name: "-d", Description: "Directory to store the newly-created custom metadata type files"},
			{Name: "-f", Description: "Type of field"},
			{Name: "-s", Description: "Number of decimal places to use for Number or Percent fields"},
			{Name: "-u", Description: "Username or alias for the target org; overrides default target org"},
			{Name: "--apiversion", Description: "Override the api version used for api requests made by this command"},
			{Name: "-t", Description: "API name of the custom metadata type to create a record for"},
			{Name: "-c", Description: "Retrieves code coverage results"},
			{Name: "-w", Description: "Invoke Apex tests"},
			{Name: "-g", Description: "Set config var globally (to be used from any directory)"},
			{Name: "-b", Description: "The ID of the batch whose status you want to view"},
			{Name: "--perflog", Description: "Get API performance data"},
			{Name: "-q", Description: "SOQL query to execute"},
			{Name: "--confighelp", Description: "Authorize an org using an existing Salesforce access token"},
			{Name: "-a", Description: "Set an alias for the authenticated org"},
		},
	})
}
