package ops

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "stripe",
		Description: "Occurs whenever a previously uncaptured charge is captured",
		Subcommands: []core.Subcommand{
			{Name: "login", Description: "Connects to your Stripe account"},
			{Name: "config", Description: "Installs a tool in your toolchain"},
			{Name: "option", Description: "Config option"},
			{Name: "value", Description: "Value for config option"},
			{Name: "completion", Description: "Generates shell autocompletions"},
			{Name: "platform", Description: "The shell to generate completion commands for"},
			{Name: "logs tail", Description: "Logs from your Stripe requests"},
			{Name: "connect_in", Description: "Incoming Connect requests"},
			{Name: "connect_out", Description: "Outgoing Connect requests"},
			{Name: "self", Description: "Non-Connect requests"},
			{Name: "GET", Description: "HTTP GET requests"},
			{Name: "POST", Description: "HTTP POST requests"},
			{Name: "DELETE", Description: "HTTP DELETE requests"},
			{Name: "SUCCEEDED", Description: "Requests that succeeded"},
			{Name: "FAILED", Description: "Requests that failed"},
			{Name: "API", Description: "Requests created with the Stripe API"},
			{Name: "DASHBOARD", Description: "Requests created from the Dashboard"},
			{Name: "2XX", Description: "HTTP 2xx status codes"},
			{Name: "4XX", Description: "HTTP 4xx status codes"},
			{Name: "5XX", Description: "HTTP 5xx status codes"},
			{Name: "JSON", Description: "Output logs in JSON format"},
			{Name: "status", Description: "Displays Stripe's system status and service availability"},
			{Name: "default", Description: "Render the status using standard output"},
			{Name: "seconds", Description: "Min: 5, default: 60"},
			{Name: "open", Description: "Displays Stripe's system status and service availability"},
			{Name: "listen", Description: "Receives webhook events from Stripe locally"},
			{Name: "account.updated", Description: "Occurs whenever an account status or property has changed"},
			{Name: "account.external_account.created", Description: "Occurs whenever an external account is created"},
			{Name: "account.external_account.deleted", Description: "Occurs whenever an external account is deleted"},
			{Name: "account.external_account.updated", Description: "Occurs whenever an external account is updated"},
			{Name: "application_fee.created", Description: "Occurs whenever an application fee is created on a charge"},
			{Name: "application_fee.refund.updated", Description: "Occurs whenever an application fee refund is updated"},
			{Name: "billing_portal.configuration.created", Description: "Occurs whenever a portal configuration is created"},
			{Name: "billing_portal.configuration.updated", Description: "Occurs whenever a portal configuration is updated"},
			{Name: "capability.updated", Description: "Occurs whenever a capability has new requirements or a new status"},
			{Name: "charge.expired", Description: "Occurs whenever an uncaptured charge expires"},
			{Name: "charge.pending", Description: "Occurs whenever a pending charge is created"},
			{Name: "charge.updated", Description: "Occurs whenever a charge description or metadata is updated"},
			{Name: "charge.dispute.funds_withdrawn", Description: "Occurs when funds are removed from your account due to a dispute"},
			{Name: "charge.dispute.updated", Description: "Occurs when the dispute is updated (usually with evidence)"},
			{Name: "charge.refund.updated", Description: "Occurs whenever a refund is updated, on selected payment methods"},
			{Name: "checkout.session.async_payment_failed", Description: "Occurs when a payment intent using a delayed payment method fails"},
			{Name: "coupon.created", Description: "Occurs whenever a coupon is created"},
			{Name: "coupon.deleted", Description: "Occurs whenever a coupon is deleted"},
			{Name: "coupon.updated", Description: "Occurs whenever a coupon is updated"},
			{Name: "credit_note.created", Description: "Occurs whenever a credit note is created"},
			{Name: "credit_note.updated", Description: "Occurs whenever a credit note is updated"},
			{Name: "credit_note.voided", Description: "Occurs whenever a credit note is voided"},
			{Name: "customer.discount.created", Description: "Occurs whenever a coupon is attached to a customer"},
			{Name: "customer.discount.deleted", Description: "Occurs whenever a coupon is removed from a customer"},
		},
		Options: []core.Option{
			{Name: "--api-key", Description: "Sets your API key to use for the command"},
			{Name: "--color", Description: "Enables or disables color output"},
			{Name: "--config", Description: "Sets your config file"},
			{Name: "--device-name", Description: "Runs command on behlaf of another device"},
			{Name: "-h", Description: "Provides the help documentation for commands, flags, and arguments"},
			{Name: "--log-level", Description: "Set the level of detail for log messages"},
			{Name: "-v", Description: "Prints the version of the Stripe CLI"},
			{Name: "-s", Description: "Shows response HTTP headers"},
			{Name: "-c", Description: "Skips the warning prompt and automatically confirms the command being entered"},
			{Name: "--dark-style", Description: "Uses a darker color scheme"},
			{Name: "-d", Description: "Additional data to send with an API request"},
			{Name: "-e", Description: "Response attributes to expand inline"},
			{Name: "-i", Description: "Makes a live request"},
			{Name: "--stripe-account", Description: "Specify the Stripe account to use for this request"},
			{Name: "--list", Description: "List all configured options"},
			{Name: "--set", Description: "Set a value for the specified configuration option"},
			{Name: "--unset", Description: "Remove a key-value pair from the config file"},
			{Name: "--shell", Description: "Opens the configuration file in your default editor"},
			{Name: "--filter-account", Description: "Filters request logs by the source and destination account"},
			{Name: "--filter-http-method", Description: "Filters request logs by HTTP method"},
			{Name: "--filter-ip-address", Description: "Filters request logs by IP address"},
			{Name: "--filter-request-path", Description: "Filters request logs that directly match any Stripe path"},
			{Name: "--filter-request-status", Description: "Filters request logs by the response status"},
			{Name: "--filter-source", Description: "Filters request logs by the source of each request"},
			{Name: "--filter-status-code", Description: "Filters request logs by HTTP status code"},
			{Name: "--filter-status-code-type", Description: "Filters request logs by the type of HTTP status code"},
			{Name: "--format", Description: "Specify the output format for request logs"},
			{Name: "--hide-spinner", Description: "Hides the loading spinner when polling"},
			{Name: "--poll", Description: "Keeps polling for status updates"},
			{Name: "--poll-rate", Description: "The number of seconds (min 5) to wait between status updates"},
			{Name: "--verbose", Description: "Shows the status of all Stripe systems"},
			{Name: "--live", Description: "Opens the Dashboard for your live integrations"},
			{Name: "--connect-headers", Description: "A comma-separated list of custom HTTP headers to any connected accounts"},
			{Name: "-f", Description: "The URL that webhook events will be forwarded to"},
			{Name: "-H", Description: "A comma-separated list of custom HTTP headers to forward"},
			{Name: "-l", Description: "Receive events used in the latest API version"},
			{Name: "-a", Description: "Listen for all webhook events based on existing webhook endpoints"},
			{Name: "-j", Description: "Print JSON objects to stdout"},
			{Name: "--skip-verify", Description: "Skip certificate verification when forwarding to HTTPS endpoints"},
			{Name: "--account", Description: "Resend the event to the given Stripe account"},
		},
	})
}
