package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "tkn",
		Description: "CLI for tekton pipelines",
		Subcommands: []spec.Subcommand{
			{Name: "tkb", Description: "Manage Tekton Bundles"},
			{Name: "list", Description: "List and print a Tekton bundle's contents"},
			{Name: "push", Description: "Create or replace a Tekton bundle"},
			{Name: "chains", Description: "Manage Chains"},
			{Name: "payload", Description: "Print Tekton Chains' payload for a specific taskrun"},
			{Name: "signature", Description: "Print Tekton Chains' signature for a specific taskrun"},
			{Name: "ct", Description: "Manage ClusterTasks"},
			{Name: "create", Description: "Create a ClusterTask from Task"},
			{Name: "rm", Description: "Delete ClusterTasks in a cluster"},
			{Name: "desc", Description: "Describe a ClusterTask"},
			{Name: "ls", Description: "Lists ClusterTasks"},
			{Name: "logs", Description: "Show ClusterTask logs"},
			{Name: "start", Description: "Start ClusterTasks"},
			{Name: "ctb", Description: "Manage ClusterTriggerBindings"},
			{Name: "completion", Description: "Prints shell completion scripts"},
			{Name: "el", Description: "Manage EventListeners"},
			{Name: "hub", Description: "Interact with tekton hub"},
			{Name: "check-upgrade", Description: "Check for upgrades of resources if present"},
			{Name: "task", Description: "Check updates for Task installed via Hub CLI"},
			{Name: "downgrade", Description: "Downgrade an installed resource"},
			{Name: "get", Description: "Get resource manifest by its name, kind, catalog, and version"},
			{Name: "pipeline", Description: "Get Pipeline by name, catalog and version"},
			{Name: "info", Description: "Display info of resource by its name, kind, catalog, and version"},
			{Name: "install", Description: "Install a resource from a catalog by its kind, name and version"},
			{Name: "reinstall", Description: "Reinstall a resource by its kind and name"},
			{Name: "search", Description: "Search resource by a combination of name, kind, categories, platforms, and tags"},
			{Name: "upgrade", Description: "Upgrade an installed resource"},
			{Name: "p", Description: "Manage pipelines"},
			{Name: "export", Description: "Export Pipeline"},
			{Name: "sign", Description: "Sign Tekton Pipeline"},
			{Name: "verify", Description: "Verify Tekton Pipeline"},
			{Name: "pr", Description: "Manage PipelineRuns"},
			{Name: "cancel", Description: "Cancel a PipelineRun in a namespace"},
			{Name: "res", Description: "Manage pipeline resources"},
			{Name: "t", Description: "Manage Tasks"},
			{Name: "tr", Description: "Manage TaskRuns"},
			{Name: "tb", Description: "Manage TriggerBindings"},
			{Name: "tt", Description: "Manage TriggerTemplates"},
			{Name: "version", Description: "Prints version information"},
			{Name: "help", Description: "Help about any command"},
		},
		Options: []spec.Option{
			{Name: "--allow-missing-template-keys", Description: "A directory to cache Tekton bundles in"},
			{Name: "--no-cache", Description: "A Bearer token to authenticate against the repository"},
			{Name: "--remote-password", Description: "If set to true, skips TLS check when connecting to the registry"},
			{Name: "--remote-username", Description: "If true, keep the managedFields when printing objects in JSON or YAML format"},
			{Name: "--template", Description: "Create or replace a Tekton bundle"},
			{Name: "--filenames", Description: "A Bearer token to authenticate against the repository"},
			{Name: "--kubeconfig", Description: "Kubectl config file (default: $HOME/.kube/config)"},
			{Name: "--namespace", Description: "Namespace to use (default: from $KUBECONFIG)"},
			{Name: "--no-color", Description: "Disable coloring (default: false)"},
			{Name: "--nocolour", Description: "Disable colouring (default: false)"},
			{Name: "--skip-verify", Description: "Skip verifying the payload'signature"},
			{Name: "--chains-namespace", Description: "Namespace in which chains is installed"},
			{Name: "--context", Description: "Name of the kubeconfig context to use (default: kubectl config current-context)"},
			{Name: "--from", Description: "Create a ClusterTask from Task in a particular namespace"},
			{Name: "--all", Description: "Delete all ClusterTasks (default: false)"},
			{Name: "--output", Description: "If true, keep the managedFields when printing objects in JSON or YAML format"},
			{Name: "--follow", Description: "Stream live logs"},
			{Name: "--last", Description: "Show logs for last TaskRun"},
			{Name: "--limit", Description: "Lists number of TaskRuns"},
			{Name: "--timestamps", Description: "Show logs with timestamp"},
			{Name: "--dry-run", Description: "Preview TaskRun without running it"},
			{Name: "--inputresource", Description: "Pass the input resource name and ref as name=ref"},
			{Name: "--labels", Description: "Pass labels as label=value"},
			{Name: "--outputresource", Description: "Pass the output resource name and ref as name=ref"},
			{Name: "--param", Description: "Local or remote file containing a PodTemplate definition"},
			{Name: "--prefix-name", Description: "Pass the serviceaccount name"},
			{Name: "--showlog", Description: "Show logs right after starting the ClusterTask"},
			{Name: "--skip-optional-workspace", Description: "Skips the prompt for optional workspaces"},
			{Name: "--timeout", Description: "Timeout for TaskRun"},
			{Name: "--use-param-defaults", Description: "Use default parameter values without prompting for input"},
			{Name: "--use-taskrun", Description: "Specify a TaskRun name to use its values to re-run the TaskRun"},
			{Name: "--workspace", Description: "Pass one or more workspaces to map to the corresponding physical volumes"},
			{Name: "--all-namespaces", Description: "List EventListeners from all namespaces"},
			{Name: "--tail", Description: "Number of most recent log lines to show. Specify -1 for all logs from each pod"},
			{Name: "--to", Description: "Version of Resource"},
			{Name: "--as-clustertask", Description: "Get the Task as ClusterTask"},
			{Name: "--version", Description: "Version of Resource"},
			{Name: "--categories", Description: "Accepts a comma separated list of categories"},
			{Name: "--kinds", Description: "Accepts a comma separated list of kinds"},
			{Name: "--match", Description: "Accept type of search. 'exact' or 'contains'"},
		},
	})
}
