package ops

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "vault",
		Description: "Display help",
		Subcommands: []core.Subcommand{
			{Name: "read", Description: "Reads data from Vault at the given path"},
			{Name: "write", Description: "Writes data from Vault at the given path"},
			{Name: "delete", Description: "Deletes secrets and configuration from Vault at the given path"},
			{Name: "list", Description: "Lists data from Vault at the given path"},
			{Name: "login", Description: "Authenticates users or machines to Vault using the provided arguments"},
			{Name: "PATH", Description: "Disable the audit device enabled at this path"},
			{Name: "enable", Description: "Enables an audit device at a given path"},
			{Name: "enable-versioning", Description: "This command turns on versioning for the backend at the provided path"},
			{Name: "lookup", Description: "Lookup the lease information of a secret"},
			{Name: "lock", Description: "Lock the current namespace, and all descendants"},
			{Name: "unlock", Description: "Unlock the current namespace, and all descendants, with unlock key"},
			{Name: "members", Description: "Provides the details of all the nodes in the cluster"},
			{Name: "autopilot", Description: "Raft auto pilot"},
			{Name: "get-config", Description: "Returns the configuration of the autopilot subsystem under integrated storage"},
			{Name: "set-config", Description: "Modify the configuration of the autopilot subsystem under integrated storage"},
			{Name: "join", Description: "Joins a node to the Raft cluster"},
			{Name: "list-peers", Description: "Returns the Raft peer set"},
			{Name: "remove-peer", Description: "Removes a node from the Raft cluster"},
			{Name: "snapshot", Description: "Restores and saves snapshots from the Raft cluster"},
			{Name: "restore", Description: "Installs the provided snapshot, returning the cluster to the state defined in it"},
			{Name: "snapshot_file", Description: "Save snapshot to this file"},
			{Name: "save", Description: "Saves a snapshot of the current state of the Raft cluster into a file"},
			{Name: "usage", Description: "List the client counts for the default reporting period"},
			{Name: "type", Description: "Plugin type"},
			{Name: "name", Description: "Plugin name"},
			{Name: "print", Description: "This command groups subcommands for interacting with Vault's runtime values"},
			{Name: "ssh", Description: "Establishes an SSH connection with the target machine"},
			{Name: "version-history", Description: "Prints the version history of the target Vault server"},
		},
		Options: []core.Option{
			{Name: "--help", Description: "Display help"},
			{Name: "-address", Description: "Key to unlock a namespace API lock. The default is (not set)"},
			{Name: "-wrap-ttl", Description: "Exit the vault server if the vault core is shutdown. The default is false"},
			{Name: "-log-format", Description: "Log format. Supported values are 'standard' and 'json'. The default is (not set)"},
			{Name: "-log-level", Description: "Toggles whether to compress output package The default is true"},
			{Name: "-duration", Description: "Duration to run the command. The default is 2m0s"},
			{Name: "-interval", Description: "The polling interval at which to collect metrics data. The default is 10s"},
			{Name: "-output", Description: "Specifies the output path for the debug package"},
			{Name: "-target", Description: "Human-friendly description for the purpose of this audit device"},
			{Name: "-local", Description: "Specifies the version numbers"},
			{Name: "-cas-required", Description: "Dump all information collected by Diagnose"},
			{Name: "-format", Description: "The output format"},
			{Name: "-skip", Description: "Skip the health checks named as arguments"},
			{Name: "-cancel", Description: "OTP code to use with '-decode' or '-init'"},
			{Name: "-pgp-key", Description: "Reset the migration lock. No migration will occur. The default is false"},
			{Name: "-start", Description: "Only copy keys lexicographically at or after this value"},
			{Name: "-auto-join-port", Description: "CA cert to use when verifying the Raft leader certificate"},
			{Name: "-leader-client-cert", Description: "Client cert to use when authenticating with the Raft leader"},
			{Name: "-leader-client-key", Description: "Client key to use when authenticating with the Raft leader"},
			{Name: "-non-voter", Description: "Continuously retry joining the Raft cluster upon failures. The default is false"},
			{Name: "-dr-token", Description: "DR operation token used to authorize this request (if a DR secondary node)"},
			{Name: "-cleanup-dead-servers", Description: "Clean up dead servers"},
			{Name: "-last-contact-threshold", Description: "Last contact threshold"},
			{Name: "-max-trailing-logs", Description: "Max trailing logs"},
			{Name: "-min-quorum", Description: "Min quorum"},
			{Name: "-server-stabilization-time", Description: "Server stabilization time"},
			{Name: "-backup-retries", Description: "Discard any previously entered keys to the unseal process. The default is false"},
			{Name: "-end-time", Description: "End of report period. Defaults to end of last month"},
			{Name: "-start-time", Description: "Start of report period. Defaults to 'default_reporting_period' before end time"},
			{Name: "-args", Description: "SHA256 of the plugin binary. This is required for all plugins"},
			{Name: "-mounts", Description: "Array or comma-separated string mount paths of the plugin backends to reload"},
			{Name: "-plugin", Description: "The name of the plugin to reload, as registered in the plugin catalog"},
			{Name: "-scope", Description: "The scope of the reload, omitted for local, 'global', for replicated reloads"},
			{Name: "-allowed-managed-keys", Description: "Human-friendly description for the purpose of this engine"},
			{Name: "-external-entropy-access", Description: "Determines the visibility of the mount in the UI-specific listing endpoint"},
			{Name: "-details", Description: "Name of the authentication mode (ca, dynamic, otp)"},
			{Name: "-mount-point", Description: "Mount point to the SSH secrets engine. The default is ssh/"},
			{Name: "-no-exec", Description: "Name of the role to use to generate the key"},
			{Name: "-strict-host-key-checking", Description: "Allow the token to be renewed up to it's maximum TTL. The default is true"},
			{Name: "-role", Description: "The type of token to create. Can be 'service' or 'batch'. The default is service"},
		},
	})
}
