package ops

import (
	"github.com/versenilvis/iris/spec"
)

func init() {
	spec.Register(&spec.Spec{
		Name:        "vela",
		Description: "Show the reference doc for component, trait or workflow types",
		Subcommands: []spec.Subcommand{
			{Name: "show", Description: "Show the reference doc for component, trait or workflow types"},
			{Name: "env", Description: "Manage environments for vela applications to run"},
			{Name: "delete", Description: "Delete an environment"},
			{Name: "init", Description: "Delete an environment"},
			{Name: "ls", Description: "List all environments for vela applications to run"},
			{Name: "set", Description: "Set an environment as the default one for running vela applications"},
			{Name: "up", Description: "Deploy one application"},
			{Name: "cluster", Description: "Manage Kubernetes Clusters for Continuous Delivery"},
			{Name: "alias", Description: "Alias a named cluster"},
			{Name: "detach", Description: "Detach managed cluster"},
			{Name: "join", Description: "Join managed cluster by kubeconfig"},
			{Name: "labels", Description: "Manage Kubernetes Cluster Labels"},
			{Name: "add", Description: "Add labels to managed cluster"},
			{Name: "del", Description: "Delete labels for managed cluster"},
			{Name: "list", Description: "List managed clusters"},
			{Name: "probe", Description: "Health probe managed cluster"},
			{Name: "rename", Description: "Rename managed cluster"},
			{Name: "workflow", Description: "Operate the Workflow during Application Delivery"},
			{Name: "restart", Description: "Restart an application workflow"},
			{Name: "resume", Description: "Resume a suspend application workflow"},
			{Name: "rollback", Description: "Rollback an application workflow to the latest revision"},
			{Name: "suspend", Description: "Suspend an application workflow"},
			{Name: "terminate", Description: "Terminate an application workflow"},
			{Name: "addon", Description: "Manage addons for extension"},
			{Name: "disable", Description: "Disable an addon"},
			{Name: "enable", Description: "Enable an addon"},
			{Name: "registry", Description: "Manage addon registry"},
			{Name: "get", Description: "Get an addon registry"},
			{Name: "update", Description: "Update an addon registry"},
			{Name: "status", Description: "Get addon status"},
			{Name: "upgrade", Description: "Upgrade an addon"},
			{Name: "uischema", Description: "Manage UI schema for addons"},
			{Name: "apply", Description: "Apply UI schema from a file or dir"},
			{Name: "def", Description: "Manage X-Definition for addons"},
			{Name: "edit", Description: "Edit X-Definition"},
			{Name: "render", Description: "Render X-Definition"},
			{Name: "vet", Description: "Validate X-Definition"},
			{Name: "remove", Description: "Remove specified registry"},
			{Name: "component", Description: "List component types installed and discover more registry"},
			{Name: "trait", Description: "List trait types installed and discover more in registry"},
			{Name: "uninstall", Description: "Uninstalls KubeVela from a Kubernetes cluster"},
			{Name: "install", Description: "Installs KubeVela into a Kubernetes cluster"},
			{Name: "bash", Description: "Output bash completion code"},
			{Name: "zsh", Description: "Output zsh completion code"},
			{Name: "export", Description: "Export deploy manifests from appfile or application"},
			{Name: "version", Description: "Prints the version"},
		},
		Options: []spec.Option{
			{Name: "-e", Description: "Specify environment name for application"},
			{Name: "--help", Description: "Help for show command"},
			{Name: "-n", Description: "Specify the Kubernetes namespace to use"},
			{Name: "--namespace", Description: "Specify K8s namespace for env"},
			{Name: "--env", Description: "Specify environment name for application"},
			{Name: "--render-only", Description: "Rendering vela.yaml in current dir and do not deploy"},
			{Name: "--file", Description: "The file path for appfile or application. It could be a remote url"},
			{Name: "--publish-version", Description: "The publish version for deploying application"},
			{Name: "--revision", Description: "Manage Kubernetes Clusters for Continuous Delivery"},
			{Name: "--kubeconfig-path", Description: "Join managed cluster by kubeconfig"},
			{Name: "--create-namespace", Description: "Manage Kubernetes Cluster Labels"},
			{Name: "--force", Description: "Skip checking if applications are still using this addon"},
			{Name: "--clusters", Description: "Specify the runtime-clusters to enable"},
			{Name: "--bucket", Description: "Specify the OSS bucket name"},
			{Name: "--endpoint", Description: "Specify the addon registry endpoint"},
			{Name: "--gitToken", Description: "Specify the github repo token"},
			{Name: "--path", Description: "Specify the addon registry OSS path"},
			{Name: "--type", Description: "Specify the addon registry type"},
			{Name: "--dry-run", Description: "Delete X-Definition"},
			{Name: "--desc", Description: "Specify the description of the new definition"},
			{Name: "--interactive", Description: "Specify whether use interactive process to help generate definitions"},
			{Name: "--git", Description: "List X-Definition"},
			{Name: "--message", Description: "Validate X-Definition"},
			{Name: "--token", Description: "Github Repo token"},
			{Name: "--registry", Description: "Specify token when using --url to specify registry url"},
			{Name: "--url", Description: "Specify the registry url"},
			{Name: "--discover", Description: "Discover more registry"},
			{Name: "--label", Description: "A label to filter components, the format is --label type=terraform"},
			{Name: "--detail", Description: "Show detail log of uninstall information"},
			{Name: "--reuse", Description: "Will re-use the user's last supplied values. (default true)"},
			{Name: "--version", Description: "Specify the version of KubeVela to install"},
		},
	})
}
