package ops

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "vercel",
		Description: "CLI Interface for Vercel.com",
		Subcommands: []core.Subcommand{
			{Name: "deploy", Description: "Performs a deployment (default)"},
			{Name: "dev", Description: "Start a local development server"},
			{Name: "env", Description: "Manages the Environment Variables for your current Project"},
			{Name: "add", Description: "Add an environment variable"},
			{Name: "name", Description: "Name of the env variable to add"},
			{Name: "environment", Description: "Environment to add the variable to"},
			{Name: "rm", Description: "Remove an environment variable"},
			{Name: "pull", Description: "Download dev env variables from cloud and write to .env"},
			{Name: "file", Description: "The file to write downloaded variables to"},
			{Name: "ls", Description: "List environment variables for a specific environment"},
			{Name: "init", Description: "Initialize an example project"},
			{Name: "project name", Description: "Project name to initialize locally"},
			{Name: "new project name", Description: "Initialize specific project locally and rename directory"},
			{Name: "list", Description: "Lists deployments"},
			{Name: "inspect", Description: "Displays information related to a deployment"},
			{Name: "url", Description: "The URL of the deployment to inspect"},
			{Name: "login", Description: "Logs into your account or creates a new one"},
			{Name: "logout", Description: "Logs out of your account"},
			{Name: "switch", Description: "Switches between teams and your personal account"},
			{Name: "team name", Description: "Team to switch to"},
			{Name: "help", Description: "Displays complete help for [cmd]"},
			{Name: "command", Description: "Command to detailed information about"},
			{Name: "deployment url", Description: "URL of the deployment to remove"},
			{Name: "remove", Description: "Removes a deployment"},
			{Name: "domains", Description: "Manages your domain names"},
			{Name: "domain", Description: "Domain to inspect"},
			{Name: "buy", Description: "Buy a domain for an account"},
			{Name: "move", Description: "Removes a domain from an account"},
			{Name: "account name", Description: "Account to move the domain to"},
			{Name: "transfer-in", Description: "Transfers in a domain to an account"},
			{Name: "verify", Description: "Verifies a domain for an account"},
			{Name: "dns", Description: "Manages your DNS records"},
			{Name: "subdomain", Description: "Subdomain to add record to"},
			{Name: "record type", Description: "Type of record to add"},
			{Name: "A", Description: "A record"},
			{Name: "AAAA", Description: "AAAA record"},
			{Name: "ALIAS", Description: "ALIAS record"},
			{Name: "CNAME", Description: "CName record"},
			{Name: "TXT", Description: "TXT record"},
			{Name: "value", Description: "Record value"},
			{Name: "certs", Description: "Manages your SSL certificates"},
			{Name: "issue", Description: "Issue certificates for multiple domains"},
			{Name: "Domains", Description: "List of domains separated by commas to issue certificates for"},
			{Name: "certificate id", Description: "Id of the certificate to remove"},
			{Name: "secrets", Description: "Manages your global Secrets, for use in Environment Variables"},
			{Name: "secret name", Description: "Name of the secret to add"},
			{Name: "secret value", Description: "Value of the secret to add"},
			{Name: "rename", Description: "Rename a secret"},
			{Name: "old name", Description: "Old name of the secret to rename"},
			{Name: "new name", Description: "New name of the secret"},
		},
		Options: []core.Option{
			{Name: "-h", Description: "Output usage information"},
			{Name: "-v", Description: "Output the version number"},
			{Name: "-V", Description: "Set the platform version to deploy to"},
			{Name: "-A", Description: "Path to the local 'vercel.json' file"},
			{Name: "-Q", Description: "Path to the global '.vercel' directory"},
			{Name: "-d", Description: "Provides more verbose output"},
			{Name: "-f", Description: "Force a new deployment even if nothing has changed"},
			{Name: "-with-cache", Description: "Retain build cache when using --force"},
			{Name: "-t", Description: "Execute command with an auth token"},
			{Name: "-p", Description: "Deployment is public ('/_src' is exposed)"},
			{Name: "-e", Description: "Include an env var during run time (e.g.: '-e KEY=value'). Can appear many times"},
			{Name: "-b", Description: "Similar to `--env` but for build time only"},
			{Name: "-m", Description: "Add metadata for the deployment (e.g.: `-m KEY=value`). Can appear many times"},
			{Name: "-C", Description: "Do not attempt to copy URL to clipboard"},
			{Name: "-S", Description: "Set a custom scope"},
			{Name: "--regions", Description: "Set default regions to enable the deployment on"},
			{Name: "--prod", Description: "Create a production deployment"},
			{Name: "-c", Description: "Confirm default options and skip questions"},
			{Name: "--listen", Description: "Specifies which port to run on"},
			{Name: "-s", Description: "Skip removal of deployments with an active preview URL or production domain"},
			{Name: "-y", Description: "Skip confirmation step for a deployment or project removal"},
			{Name: "--challenge-only", Description: "Show challenges needed to issue a certificate"},
			{Name: "--crt", Description: "Include path to .crt"},
			{Name: "--key", Description: "Include path to .key"},
			{Name: "--ca", Description: "Include path to .ca"},
			{Name: "-a", Description: "Receive access logs in addition to regular logs"},
			{Name: "-n", Description: "Specify number of log lines to output"},
			{Name: "-o", Description: "Specifies format of logs output as 'short' or 'raw'"},
			{Name: "--since", Description: "Return logs after a specific ISO 8601 date"},
			{Name: "-q", Description: "Return logs against a search query"},
			{Name: "--until", Description: "Return logs up to a specific ISO 8601 date"},
		},
	})
}
