package python

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "conda",
		Description: "Name of environment",
		Subcommands: []core.Subcommand{
			{Name: "activate", Description: "Activate an environment"},
			{Name: "deactivate", Description: "Deactivate an environment"},
			{Name: "clean", Description: "Remove unused packages and caches"},
			{Name: "compare", Description: "Compare packages between conda environments"},
			{Name: "file", Description: "Path to the environment file that is to be compared against"},
			{Name: "create", Description: "Create a new conda environment from a list of specified packages"},
			{Name: "package_spec", Description: "Packages to install or update in the conda environment"},
			{Name: "help", Description: "Displays a list of available conda commands and their help strings"},
			{Name: "info", Description: "Display information about current conda install"},
			{Name: "init", Description: "Initialize conda for shell interaction. [Experimental]"},
			{Name: "install", Description: "Installs a list of packages into a specified conda environment"},
			{Name: "package spec", Description: "Packages to install or update in the conda environment"},
			{Name: "list", Description: "List linked packages in a conda environment"},
			{Name: "regex", Description: "List only packages matching this regular expression"},
			{Name: "package", Description: "Low-level conda package utility. (EXPERIMENTAL)"},
			{Name: "remove", Description: "Remove a list of packages from a specified conda environment"},
			{Name: "uninstall", Description: "Alias for conda remove"},
			{Name: "run", Description: "Run an executable in a conda environment. [Experimental]"},
			{Name: "update", Description: "Updates conda packages to the latest compatible version"},
			{Name: "conda", Description: "Update conda"},
			{Name: "upgrade", Description: "Alias for conda update"},
			{Name: "files", Description: "Package files to convert"},
		},
		Options: []core.Option{
			{Name: "-n", Description: "Name of environment"},
			{Name: "-p", Description: "Full path to environment location (i.e. prefix)"},
			{Name: "--dev", Description: "Use locally built packages. Identical to '-c local'"},
			{Name: "--override-channels", Description: "Do not search default or .condarc channels. Requires --channel"},
			{Name: "--repodata-fn", Description: "Remove all packages, i.e., the entire environment"},
			{Name: "--features", Description: "Remove features (instead of packages)"},
			{Name: "--force-remove", Description: "Ignore pinned file"},
			{Name: "-C", Description: "Use cache of channel index files, even if it has expired"},
			{Name: "-k", Description: "Offline mode. Don't connect to the Internet"},
			{Name: "-d", Description: "Only display what would have been done"},
			{Name: "--json", Description: "Report all output as json. Suitable for using conda programmatically"},
			{Name: "-q", Description: "Do not display progress bar"},
			{Name: "-v", Description: "Do not ask for confirmation"},
			{Name: "--file", Description: "Use locally built packages. Identical to '-c local'"},
			{Name: "--no-pin", Description: "Ignore pinned file"},
			{Name: "--force-reinstall", Description: "Do not update or change already-installed dependencies"},
			{Name: "--update-deps", Description: "Update dependencies"},
			{Name: "-S", Description: "Update all installed packages in the environment"},
			{Name: "--update-specs", Description: "Update based on provided specifications"},
			{Name: "--copy", Description: "Install all packages using copies instead of hard- or soft-linking"},
			{Name: "--clobber", Description: "Use cache of channel index files, even if it has expired"},
			{Name: "--download-only", Description: "Conda package manager"},
			{Name: "--stack", Description: "Stack the environment being activated on top of the previous active environment"},
			{Name: "--no-stack", Description: "Do not stack the environment. Overrides 'auto_stack' setting"},
			{Name: "-a", Description: "Remove index cache, lock files, unused cache packages, and tarballs"},
			{Name: "-i", Description: "Remove index cache"},
			{Name: "-t", Description: "Remove cached package tarballs"},
			{Name: "-f", Description: "Remove all writable package caches"},
			{Name: "-c", Description: "Only display what would have been done"},
			{Name: "-h", Description: "Show this help message and exit"},
			{Name: "--system", Description: "Write to the given file"},
			{Name: "--show", Description: "Display all identified configuration sources"},
			{Name: "--validate", Description: "Validate all configuration sources"},
			{Name: "--describe", Description: "Get a configuration value"},
			{Name: "--append", Description: "Add one configuration value to the end of a list key"},
			{Name: "--prepend", Description: "Add one configuration value to the beginning of a list key"},
			{Name: "--set", Description: "Set a boolean or string key"},
			{Name: "--remove", Description: "Remove a configuration key (and all its values)"},
			{Name: "--stdin", Description: "Apply configuration information given in yaml format piped through stdin"},
			{Name: "--clone", Description: "Path to (or name of) existing local environment"},
		},
	})
}
