package python

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "mamba",
		Description: "Mamba is a fast, robust, and cross-platform package manager",
		Subcommands: []core.Subcommand{
			{Name: "activate", Description: "Activate an environment"},
			{Name: "deactivate", Description: "Deactivate an environment"},
			{Name: "clean", Description: "Remove unused packages and caches"},
			{Name: "compare", Description: "Compare packages between conda environments"},
			{Name: "file", Description: "Path to the environment file that is to be compared against"},
			{Name: "create", Description: "Create a new conda environment from a list of specified packages"},
			{Name: "package_spec", Description: "Packages to install or update in the conda environment"},
			{Name: "info", Description: "Display information about current conda install"},
			{Name: "init", Description: "Initialize conda for shell interaction. [Experimental]"},
			{Name: "install", Description: "Installs a list of packages into a specified conda environment"},
			{Name: "package spec", Description: "Packages to install or update in the conda environment"},
			{Name: "list", Description: "List linked packages in a conda environment"},
			{Name: "regex", Description: "List only packages matching this regular expression"},
			{Name: "package", Description: "Low-level conda package utility. (EXPERIMENTAL)"},
			{Name: "remove", Description: "Remove a list of packages from a specified conda environment"},
			{Name: "uninstall", Description: "Alias for remove"},
			{Name: "run", Description: "Run an executable in a conda environment"},
			{Name: "update", Description: "Updates conda packages to the latest compatible version"},
			{Name: "mamba", Description: "Update mamba"},
			{Name: "upgrade", Description: "Alias for update"},
			{Name: "repoquery", Description: "Query repositories using mamba"},
			{Name: "xtensor>=0.18", Description: "Search for xtensor version which is more than 0.18"},
			{Name: "depends", Description: "List dependencies for a package"},
			{Name: "xtensor", Description: "List dependencies for xtensor package"},
			{Name: "whoneeds", Description: "List packages that require a given package"},
			{Name: "xtl", Description: "List packages that require xtl package"},
			{Name: "env", Description: "Manage environments"},
		},
		Options: []core.Option{
			{Name: "-n", Description: "Name of environment"},
			{Name: "-p", Description: "Full path to environment location (i.e. prefix)"},
			{Name: "--file", Description: "Use locally built packages. Identical to '-c local'"},
			{Name: "--override-channels", Description: "Do not search default or .condarc channels. Requires --channel"},
			{Name: "--repodata-fn", Description: "Only install dependencies"},
			{Name: "--no-pin", Description: "Ignore pinned file"},
			{Name: "--force-reinstall", Description: "Do not update or change already-installed dependencies"},
			{Name: "--update-deps", Description: "Update dependencies"},
			{Name: "-S", Description: "Update all installed packages in the environment"},
			{Name: "--update-specs", Description: "Update based on provided specifications"},
			{Name: "--copy", Description: "Install all packages using copies instead of hard- or soft-linking"},
			{Name: "--clobber", Description: "Use cache of channel index files, even if it has expired"},
			{Name: "-k", Description: "Offline mode. Don't connect to the Internet"},
			{Name: "-d", Description: "Only display what would have been done"},
			{Name: "--json", Description: "Report all output as json. Suitable for using conda programmatically"},
			{Name: "-q", Description: "Do not display progress bar"},
			{Name: "-v", Description: "Do not ask for confirmation"},
			{Name: "--download-only", Description: "Use locally built packages. Identical to '-c local'"},
			{Name: "--features", Description: "Remove features (instead of packages)"},
			{Name: "--force-remove", Description: "Ignore pinned file"},
			{Name: "-C", Description: "Use cache of channel index files, even if it has expired"},
			{Name: "-c", Description: "Use locally built packages. Identical to '-c local'"},
			{Name: "--stack", Description: "Stack the environment being activated on top of the previous active environment"},
			{Name: "--no-stack", Description: "Do not stack the environment. Overrides 'auto_stack' setting"},
			{Name: "-a", Description: "Remove index cache, lock files, unused cache packages, and tarballs"},
			{Name: "-i", Description: "Remove index cache"},
			{Name: "-t", Description: "Remove cached package tarballs"},
			{Name: "-f", Description: "Remove all writable package caches"},
			{Name: "-l", Description: "Remove log files"},
			{Name: "--locks", Description: "Remove lock files"},
			{Name: "-h", Description: "Show this help message and exit"},
			{Name: "--clone", Description: "Path to (or name of) existing local environment"},
			{Name: "--no-default-packages", Description: "Ignore create_default_packages in the .condarc file"},
			{Name: "--base", Description: "Display base environment path"},
			{Name: "-e", Description: "List all known conda environments"},
			{Name: "-s", Description: "List environment variables"},
			{Name: "--unsafe-channels", Description: "Display list of channels with tokens exposed"},
			{Name: "--revision", Description: "Revert to the specified REVISION"},
			{Name: "-m", Description: "Create the environment directory if necessary"},
			{Name: "--show-channel-urls", Description: "Output canonical names of packages only. Implies --no-pip"},
		},
	})
}
