package python

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "mypy",
		Description: "Mypy is a static type checker for Python",
		Options: []core.Option{
			{Name: "--module", Description: "Asks mypy to type check the provided module"},
			{Name: "--package", Description: "Asks mypy to type check the provided package"},
			{Name: "--command", Description: "Asks mypy to type check the provided string as a program"},
			{Name: "--exclude", Description: "Show help message and exit"},
			{Name: "--verbose", Description: "More verbose messages"},
			{Name: "--version", Description: "Show program's version number and exit"},
			{Name: "--config-file", Description: "This flag makes mypy read configuration settings from the given file"},
			{Name: "--warn-unused-configs", Description: "This flag makes mypy warn about unused [mypy-<pattern>] config file sections"},
			{Name: "--explicit-package-bases", Description: "This flag makes mypy ignore all missing imports"},
			{Name: "--python-executable", Description: "This flag will disable searching for PEP561 compliant packages"},
			{Name: "--no-silence-site-packages", Description: "This flag disables import discovery of namespace packages (see PEP420)"},
			{Name: "--python-version", Description: "This flag disallows all expressions in the module that have type Any"},
			{Name: "--disallow-any-decorated", Description: "This flag reports an error whenever a class subclasses a value of type Any"},
			{Name: "--disallow-untyped-calls", Description: "This flag disables strict checking of pydata~typing"},
			{Name: "--warn-redundant-casts", Description: "By default, mypy won't allow a variable to be redefined with an unrelated type"},
			{Name: "--local-partial-types", Description: "By default, mypy allows always-false comparisons like 42 == 'no'"},
			{Name: "--extra-checks", Description: "This flag mode enables all optional error checking flags"},
			{Name: "--disable-error-code", Description: "This flag allows disabling one or multiple error codes globally"},
			{Name: "--enable-error-code", Description: "This flag allows enabling one or multiple error codes globally"},
			{Name: "--show-error-context", Description: "This flag will add column offsets to error messages"},
			{Name: "--show-error-end", Description: "This flag will hide the error code [<code>] from error messages"},
			{Name: "--pretty", Description: "This flag will disable color output in error messages, enabled by default"},
			{Name: "--no-error-summary", Description: "This flag will disable error summary"},
			{Name: "--show-absolute-path", Description: "Show absolute paths to files"},
			{Name: "--soft-error-limit", Description: "By default, mypy stores all cache data inside of a folder named"},
			{Name: "--sqlite-cache", Description: "Use an SQLite_ database to store the cache"},
			{Name: "--cache-fine-grained", Description: "Include fine-grained dependency information in the cache for the mypy daemon"},
			{Name: "--skip-version-check", Description: "By default, mypy will ignore cache data generated by a different version of mypy"},
			{Name: "--skip-cache-mtime-checks", Description: "Skip cache internal consistency checks based on mtime"},
			{Name: "--pdb", Description: "This flag will invoke the Python debugger when mypy encounters a fatal error"},
			{Name: "--tb", Description: "Raise exception on fatal error"},
			{Name: "--custom-typing-module", Description: "Causes mypy to generate a Cobertura XML type checking coverage report"},
			{Name: "--html-report", Description: "Causes mypy to generate an HTML type checking coverage report"},
			{Name: "--linecount-report", Description: "Causes mypy to generate a text file type checking coverage report"},
			{Name: "--xml-report", Description: "Causes mypy to generate an XML type checking coverage report"},
			{Name: "--install-types", Description: "This flag will give command line arguments that appear to be scripts"},
		},
	})
}
