package python

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "pipenv",
		Description: "Python package manager",
		Subcommands: []core.Subcommand{
			{Name: "clean", Description: "Uninstalls all packages not specified in Pipfile.lock"},
			{Name: "graph", Description: "Displays currently-installed dependency graph information"},
			{Name: "install", Description: "Initializes a package manager or installs all packages from Pipfile"},
			{Name: "package", Description: "Package to install"},
			{Name: "lock", Description: "Generates Pipfile.lock"},
			{Name: "> requirements.txt", Description: "Write packages into requirements.txt"},
			{Name: "open", Description: "View a given module in your editor"},
			{Name: "run", Description: "Spawns a command installed into the virtualenv"},
			{Name: "scripts", Description: "Lists scripts in current environment config"},
			{Name: "shell", Description: "Start a shell within the environment"},
			{Name: "sync", Description: "Installs all packages specified in Pipfile.lock"},
			{Name: "uninstall", Description: "Uninstalls a provided package and removes it from Pipfile"},
			{Name: "update", Description: "Runs lock, then sync"},
		},
		Options: []core.Option{
			{Name: "--unused", Description: "Given a code path, show potentially unused dependencies"},
			{Name: "--db", Description: "Ignore specified vulnerability during PyUp Safety checks"},
			{Name: "--output", Description: "Translates to –json, –full-report or –bare from PyUp Safety check"},
			{Name: "--key", Description: "Quiet standard output, except vulnerability report"},
			{Name: "--python", Description: "Specify which version of Python virtualenv should use"},
			{Name: "--three", Description: "Use Python 3 when creating virtualenv"},
			{Name: "--two", Description: "Use Python 2 when creating virtualenv"},
			{Name: "--clear", Description: "Clears caches (pipenv, pip, and pip-tools)"},
			{Name: "-v", Description: "Verbose mode"},
			{Name: "--pypi-mirror", Description: "Specify a PyPI mirror"},
			{Name: "--system", Description: "System pip management"},
			{Name: "--bare", Description: "Minimal output"},
			{Name: "--dry-run", Description: "Just output unneeded packages"},
			{Name: "--json", Description: "Output JSON"},
			{Name: "--json-tree", Description: "Output JSON in nested tree"},
			{Name: "--reverse", Description: "Reversed dependency graph"},
			{Name: "-c", Description: "Install packages automatically discovered from import statements"},
			{Name: "--deploy", Description: "Enforce that your Pipfile.lock is up to date in deployment"},
			{Name: "--site-packages", Description: "Enable site-packages for the virtualenv [env var: PIPENV_SITE_PACKAGES]"},
			{Name: "--no-site-packages", Description: "Enable site-packages for the virtualenv [env var: PIPENV_SITE_PACKAGES]"},
			{Name: "--skip-lock", Description: "Skip locking mechanisms and use the Pipfile instead during operation"},
			{Name: "-e", Description: "An editable Python package URL or path, often to a VCS repository"},
			{Name: "--ignore-pipfile", Description: "Ignore Pipfile when installing, using the Pipfile.lock"},
			{Name: "--selective-upgrade", Description: "Update specified packages"},
			{Name: "-r", Description: "Import a requirements.txt file"},
			{Name: "--extra-index-url", Description: "URLs to the extra PyPI compatible indexes to query for package look-ups"},
			{Name: "-i", Description: "Target PyPI-compatible package index url"},
			{Name: "--sequential", Description: "Install dependencies one-at-a-time, instead of concurrently"},
			{Name: "-d", Description: "Install both develop and default packages"},
			{Name: "--keep-outdated", Description: "Keep out-dated dependencies from being updated in Pipfile.lock"},
			{Name: "--pre", Description: "Allow pre-releases"},
			{Name: "--dev-only", Description: "Generate a requirements file with only the development requirements"},
			{Name: "--header", Description: "Add header to generated requirements"},
			{Name: "--no-header", Description: "Generate requirements with no header"},
			{Name: "--fancy", Description: "Specify which version of Python virtualenv should use"},
			{Name: "--anyway", Description: "Always spawn a sub-shell, even if one is already spawned"},
			{Name: "--all-dev", Description: "Uninstall all package from [dev-packages]"},
			{Name: "--all", Description: "Purge all package(s) from virtualenv. Does not edit Pipfile"},
			{Name: "--outdated", Description: "List out-of-date dependencies"},
			{Name: "--venv", Description: "View virtualenv information"},
		},
	})
}
