package js

import (
	"github.com/versenilvis/iris/commands/core"
)

func init() {
	core.Register(&core.Spec{
		Name:        "ionic",
		Description: "Target engine (e.g. browser, cordova)",
		Subcommands: []core.Subcommand{
			{Name: "completion", Description: "Enables tab-completion for Ionic CLI commands"},
			{Name: "id", Description: "The Appflow ID of the app to link (e.g. a1b2c3d4)"},
			{Name: "email", Description: "Your email address"},
			{Name: "password", Description: "Your password"},
			{Name: "logout", Description: "Log out of Ionic"},
			{Name: "signup", Description: "Create an Ionic account"},
			{Name: "template", Description: "The starter template to use (e.g. blank, tabs; use --list to see all)"},
			{Name: "config", Description: "Config commands for Ionic"},
			{Name: "property", Description: "The property name you wish to get"},
			{Name: "value", Description: "The new value of the given property"},
			{Name: "capacitor", Description: "Capacitor commands Ionic"},
			{Name: "platform", Description: "The platform to add (e.g. android, ios)"},
			{Name: "configuration", Description: "Specify the configuration to use"},
			{Name: "deploy", Description: "AppFlow deploy commands for Ionic"},
			{Name: "manifest", Description: "Generates a manifest file for the deploy service from a built app directory"},
			{Name: "git", Description: "Git commands for Ionic"},
			{Name: "remote", Description: "Adds/updates the Appflow git remote to your local Ionic app"},
			{Name: "package", Description: "Package commands for Ionic"},
			{Name: "type", Description: "The build type (debug, release, development, ad-hoc, app-store, enterprise)"},
			{Name: "build-id", Description: "The build id of the desired successful package build"},
			{Name: "destination", Description: "The destination to deploy the build artifact to the app store"},
			{Name: "ssl", Description: "SSL commands for Ionic"},
			{Name: "ssh", Description: "SSH commands for Ionic"},
			{Name: "pubkey-path", Description: "Location of public key file to add to Ionic"},
			{Name: "key-id", Description: "The ID of the public key to delete"},
			{Name: "key-path", Description: "Destination of private key file"},
			{Name: "setup", Description: "Setup your Ionic SSH keys automatically"},
			{Name: "doctor", Description: "Doctor commands for Ionic"},
			{Name: "list", Description: "List all issues and their identifiers"},
			{Name: "integrations", Description: "Integration commands for Ionic"},
			{Name: "name", Description: "The integration to disable (e.g. capacitor, cordova, enterprise)"},
			{Name: "enterprise", Description: "Enterprise commands for Ionic"},
			{Name: "cordova", Description: "Cordova commands for Ionic"},
			{Name: "action", Description: "Add, remove, or update a platform; ls, check, or save all project platforms"},
			{Name: "plugin", Description: "The name of the plugin (corresponds to add and remove)"},
		},
		Options: []core.Option{
			{Name: "--engine", Description: "Target engine (e.g. browser, cordova)"},
			{Name: "--platform", Description: "Target platform on chosen engine (e.g. ios, android)"},
			{Name: "--prod", Description: "Flag to use the production configuration"},
			{Name: "--configuration", Description: "Specify the configuration to use"},
			{Name: "--source-map", Description: "Output source maps"},
			{Name: "--watch", Description: "Rebuild when files change"},
			{Name: "--browser", Description: "Specifies the browser to use (safari, firefox, google chrome)"},
			{Name: "--json", Description: "Print system/environment info in JSON format"},
			{Name: "--type", Description: "Type of project (e.g. angular, react, vue, custom)"},
			{Name: "--force", Description: "Initialize even if a project already exists"},
			{Name: "--multi-app", Description: "Initialize a multi-app project"},
			{Name: "--project-id", Description: "Specify a slug for your app"},
			{Name: "--default", Description: "Mark the initialized app as the default project"},
			{Name: "--cordova", Description: "Only perform the repair steps for Cordova platforms and plugins"},
			{Name: "--external", Description: "Host dev server on all network interfaces (i.e. --host=0.0.0.0)"},
			{Name: "--host", Description: "Use specific host for the dev server"},
			{Name: "--port", Description: "Use specific port for the dev server"},
			{Name: "--public-host", Description: "The host used for the browser or web view"},
			{Name: "--no-livereload", Description: "Do not spin up dev server--just serve files"},
			{Name: "--lab-host", Description: "Use specific host for Ionic Lab server"},
			{Name: "--lab-port", Description: "Use specific port for Ionic Lab server"},
			{Name: "--no-open", Description: "Do not open a browser window"},
			{Name: "--browseroption", Description: "Specifies a path to open to (/#/tab/dash)"},
			{Name: "--lab", Description: "Test your apps on multiple platform types in the browser"},
			{Name: "--ssl", Description: "Use HTTPS for the dev server"},
			{Name: "--consolelogs", Description: "Print app console logs to the terminal"},
			{Name: "--consolelogs-port", Description: "Use specific port for console logs server"},
			{Name: "--list", Description: "List available starter templates"},
			{Name: "--capacitor", Description: "Include Capacitor integration"},
			{Name: "--no-deps", Description: "Do not install npm/yarn dependencies"},
			{Name: "--no-git", Description: "Do not initialize a git repo"},
			{Name: "--link", Description: "Connect your new app to Ionic"},
			{Name: "--id", Description: "Specify an Ionic App ID to link"},
			{Name: "--package-id", Description: "Specify the bundle ID/application ID for your app (reverse-DNS notation)"},
			{Name: "--global", Description: "Use global CLI config"},
			{Name: "--root", Description: "Operate on root of ionic.config.json"},
			{Name: "--no-build", Description: "Do not invoke Ionic build"},
			{Name: "--target", Description: "Deploy to a specific device by its ID (use --list to see all)"},
			{Name: "--open", Description: "Open native IDE instead of using capacitor run"},
			{Name: "--livereload", Description: "Spin up dev server to live-reload www files"},
		},
	})
}
